import { DataManagement } from './DataManagement.tsx';
import type { Repository } from '../data/repository.ts';
import type { PersonalData } from '../domain/types.ts';
import { Shopping } from './Shopping.tsx';
import { useState } from 'react';
import type { CustomRecipe, MenuTemplate, PersonalStore, RecipeSnapshot, ShoppingSource, TrashEntry } from '../domain/types.ts';
import { localDate } from '../domain/dates.ts';
import { summarizeActuals } from '../history/recap.ts';
import { ClearEditor, CustomEditor, DeleteEditor, FavoriteEditor, RestoreEditor, TemplateEditor, TYPE_LABELS, type LocalActions } from './PersonalActions.tsx';
import { MEAL_LABELS, RecipeFacts } from './components.tsx';
import type { StorageStatus } from '../data/storage-status.ts';
function entryName(entry:TrashEntry){return entry.store==='customRecipes'||entry.store==='favorites'?entry.data.snapshot.name:entry.store==='menuTemplates'?entry.data.name:entry.store==='shoppingLists'?'采购清单 '+entry.data.createdAt:entry.data.snapshots.map(s=>s.name).join('、');}
export function SnapshotDetails({snapshot}:{snapshot:RecipeSnapshot}){return <details><summary>查看食材、步骤和来源</summary><RecipeFacts snapshot={snapshot}/></details>;}
export function My({actions,storageStatus,persisted,onPersistence,shoppingSeed,draftSource,repository=null,memoryData=actions.data,metadataKnown=false}:{actions:LocalActions;metadataKnown?:boolean;repository?:Repository|null;memoryData?:PersonalData;shoppingSeed?:{id:string;sources:ShoppingSource[]}|null;draftSource?:ShoppingSource|null;storageStatus:StorageStatus;persisted:boolean|null;onPersistence:()=>void}){
  const [custom,setCustom]=useState<CustomRecipe|null|undefined>(undefined),[template,setTemplate]=useState<MenuTemplate|null>(null),[favorite,setFavorite]=useState<RecipeSnapshot|null>(null),[deletion,setDeletion]=useState<{store:PersonalStore;id:string}|null>(null),[restore,setRestore]=useState<TrashEntry|null>(null),[clearing,setClearing]=useState(false),[days,setDays]=useState<7|30>(7);
  const today=localDate(new Date(),Intl.DateTimeFormat().resolvedOptions().timeZone as Parameters<typeof localDate>[1]),recap=summarizeActuals(actions.data.actualMeals,today,days);
  function done(){setCustom(undefined);setTemplate(null);setFavorite(null);setDeletion(null);setRestore(null);setClearing(false);}
  function favoriteAction(snapshot:RecipeSnapshot){const existing=actions.data.favorites.find(f=>f.recipeId===snapshot.recipeId);done();if(existing)setDeletion({store:'favorites',id:existing.id});else setFavorite(snapshot);}
  const disabled=actions.pending||!actions.writable;
  return <section aria-labelledby="my-title"><h2 id="my-title">我的</h2><p>以下个人内容在当前浏览器，在线菜谱不可用时仍可手选和管理。</p>
    {custom!==undefined&&<CustomEditor key={custom?.id??'new'} actions={actions} {...(custom?{recipe:custom}:{})} onDone={done}/>}{template&&<TemplateEditor key={template.id} actions={actions} template={template} onDone={done}/>}{favorite&&<FavoriteEditor key={favorite.recipeId} actions={actions} snapshot={favorite} onDone={done}/>}{deletion&&<DeleteEditor key={deletion.id} actions={actions} {...deletion} onDone={done}/>}{restore&&<RestoreEditor key={restore.id} actions={actions} entry={restore} onDone={done}/>}{clearing&&<ClearEditor actions={actions} onDone={done}/>}
    <Shopping key={shoppingSeed?.id??'shopping'} actions={actions} initialSources={shoppingSeed?.sources??[]} draftSource={draftSource??null}/>
    <div className="workspace-grid"><div className="card"><h3>收藏</h3>{actions.data.favorites.length?<ul>{actions.data.favorites.map(f=><li key={f.id}><p>{f.snapshot.name}</p>{(!actions.catalog?.ok||!actions.catalog.value.recipes.some(r=>r.recipeId===f.recipeId))&&<p>当前菜库已不收录或尚未读取</p>}<SnapshotDetails snapshot={f.snapshot}/><button disabled={actions.pending} aria-label={`手选收藏 ${f.snapshot.name}`} onClick={()=>actions.onSelect(f.snapshot)}>手选收藏菜</button>{' '}<button disabled={disabled} aria-label={`取消收藏 ${f.snapshot.name}`} onClick={()=>{done();setDeletion({store:'favorites',id:f.id});}}>取消收藏</button></li>)}</ul>:<p>还没有收藏。可从在线菜谱或自定义菜谱收藏。</p>}</div>
    <div className="card"><h3>自定义菜谱</h3><button disabled={disabled} onClick={()=>{done();setCustom(null);}}>新建自定义菜谱</button>{actions.data.customRecipes.length?<ul>{actions.data.customRecipes.map(r=><li key={r.id}><p>{r.snapshot.name}</p><p>仅供手选，食材信息未经审核</p><SnapshotDetails snapshot={r.snapshot}/><button disabled={actions.pending} aria-label={`手选 ${r.snapshot.name}`} onClick={()=>actions.onSelect(r.snapshot)}>手选这道菜</button>{' '}<button disabled={disabled} aria-label={`${actions.data.favorites.some(f=>f.recipeId===r.id)?'取消收藏':'收藏'} ${r.snapshot.name}`} onClick={()=>favoriteAction(r.snapshot)}>{actions.data.favorites.some(f=>f.recipeId===r.id)?'取消收藏':'收藏'}</button>{' '}<button disabled={disabled} aria-label={`编辑自定义 ${r.snapshot.name}`} onClick={()=>{done();setCustom(r);}}>编辑自定义</button>{' '}<button disabled={disabled} aria-label={`删除自定义 ${r.snapshot.name}`} onClick={()=>{done();setDeletion({store:'customRecipes',id:r.id});}}>删除自定义</button></li>)}</ul>:<p>没有自定义菜谱。菜名必填，其他信息可留空。</p>}</div>
    <div className="card"><h3>菜单模板</h3><p>模板不算实际记录。保存本餐组合可在“今天吃什么”操作。</p>{actions.data.menuTemplates.length?<ul>{actions.data.menuTemplates.map(t=><li key={t.id}><p>{t.name} · {t.servings} 人</p><p>{t.snapshots.map(s=>s.name).join('、')}</p><button disabled={actions.pending} aria-label={`使用模板 ${t.name}`} onClick={()=>actions.onUseTemplate(t)}>使用模板</button>{' '}<button disabled={disabled} aria-label={`更新模板 ${t.name}`} onClick={()=>{done();setTemplate(t);}}>更新模板快照</button>{' '}<button disabled={disabled} aria-label={`删除模板 ${t.name}`} onClick={()=>{done();setDeletion({store:'menuTemplates',id:t.id});}}>删除模板</button></li>)}</ul>:<p>还没有菜单模板。</p>}</div>
    <div className="card"><h3>饮食回顾</h3><button aria-pressed={days===7} onClick={()=>setDays(7)}>最近 7 天</button>{' '}<button aria-pressed={days===30} onClick={()=>setDays(30)}>最近 30 天</button><p>只统计实际饮食记录。没有记录的日期标为“未记录”，不代表没有吃饭。</p><ul>{recap.days.map(day=><li key={day.date}>{day.date} · {day.status==='recorded'?`已记录 ${day.recordCount} 条`:'未记录'}</li>)}</ul><h4>菜品出现次数</h4>{recap.dishCounts.length?<ul>{recap.dishCounts.map(row=><li key={row.recipeId}>{actions.data.actualMeals.flatMap(a=>a.snapshots).find(s=>s.recipeId===row.recipeId)?.name??row.recipeId} · {row.count} 次</li>)}</ul>:<p>没有实际记录，计划不计入回顾。</p>}<h4>已记录餐次</h4><ul>{Object.entries(recap.mealCounts).map(([meal,count])=><li key={meal}>{MEAL_LABELS[meal as keyof typeof MEAL_LABELS]} · {count} 条</li>)}</ul><h4>记录当时分类</h4><p>分类标签可重叠，只描述记录中的菜品，不代表营养比例。</p>{Object.entries(recap.categoryCounts).map(([type,count])=><p key={type}>{TYPE_LABELS[type as keyof typeof TYPE_LABELS]} · {count} 次</p>)}</div>
    <div className="card"><h3>回收站</h3><p>保留 30×24 小时，到期项目在下次打开应用时清理。不承诺后台定时清理。</p>{actions.data.trash.length?<ul>{actions.data.trash.map(entry=><li key={entry.id}><p>{entryName(entry)} · {entry.store}</p><p>删除时间 {entry.deletedAt} · 过期时间 {entry.expiresAt}</p><button disabled={disabled||entry.expiresAt<=new Date().toISOString()} aria-label={`恢复 ${entryName(entry)}`} onClick={()=>{done();setRestore(entry);}}>恢复</button></li>)}</ul>:<p>回收站为空</p>}</div>
    </div><DataManagement actions={actions} metadataKnown={metadataKnown} repository={repository} memoryData={memoryData} storageStatus={storageStatus} persisted={persisted} onPersistence={onPersistence} onClear={()=>{done();setClearing(true);}}/>
  </section>;
}
