import { useState } from 'react';
import type { ShoppingItem, ShoppingList, ShoppingListInput, ShoppingSource } from '../domain/types.ts';
import { buildShopping, diffShopping, sourceFromPlan, sourceState } from '../shopping/shopping.ts';
import { formatQuantity } from '../shopping/quantities.ts';
import { isText } from '../domain/validation.ts';
import { DeleteEditor, useLocalMutation, type LocalActions } from './PersonalActions.tsx';
import { Dialog, MEAL_LABELS, Notice, SourceLink } from './components.tsx';
function SourceDetails({source,actions,draftSource}:{source:ShoppingSource;actions:LocalActions;draftSource:ShoppingSource|null}){
  const state=sourceState(source,actions.data,draftSource);
  return <div>{state==='changed'&&<p>来源已变更</p>}{state==='deleted'&&<p>{source.kind==='plan'?'来源计划已删除，快照仍保留':'来源草稿已移除，快照仍保留'}</p>}<details><summary>{source.kind==='plan'?'计划':'当前本地草稿'} · {source.id} · {source.servings} 人 · 来源版本 {source.revision??'未保存'}</summary>
    <p>内容指纹：{source.digest}</p>{source.snapshots.map((snapshot,i)=><div key={i}><h4>{snapshot.name}</h4><p>菜品身份 {snapshot.recipeId} · 来源组 {snapshot.familyId} · 变体 {snapshot.variantId??'未知'} · 基准 {snapshot.baseServings??'未知'} 人</p><p>分类 {snapshot.types.join('、')||'未知'}</p><ul>{snapshot.ingredients.map((ingredient,n)=><li key={n}>{ingredient.raw} · 原量 {formatQuantity(ingredient.quantity)} · 形态 {ingredient.form||'未知'} · 部位 {ingredient.part??'未知'} · 原料身份 {ingredient.ingredientId??'未知'} · {ingredient.trust==='reviewed'?'来源有审核记录':'未经审核'} · 复合成分 {ingredient.compoundResolved?'已解析':'未知'}</li>)}</ul><ol>{snapshot.steps.map((step,n)=><li key={n}>{step}</li>)}</ol><p>来源 <SourceLink url={snapshot.source.url}/> · 提交 {snapshot.source.commit??'未知'} · 许可 {snapshot.source.license??'未知'} · 菜库版本 {snapshot.catalogVersion??'未知'} · 内容版本 {snapshot.contentVersion??'未知'}</p></div>)}
  </details></div>;
}
function ItemFacts({item}:{item:ShoppingItem}){
  return <><p>{item.name}{item.manual?' · 手动项':''} · 形态 {item.form||'未知'} · 部位 {item.part??'未知'}</p><p>{formatQuantity(item.quantity)}</p>{item.unknownEntries.length>0&&<p>待确认 {item.unknownEntries.length} 项</p>}{item.userQuantity!==null&&<p>手改用量：{item.userQuantity}</p>}{item.purchased&&<p>已购</p>}
    {item.sources.length>0&&<details><summary>查看条目计算和原文</summary>{item.sources.map((f,i)=><div key={i}><p>{f.snapshot.name} · {f.sourceKind==='plan'?'计划':'草稿'} {f.sourceId} · 版本 {f.sourceRevision??'未保存'} · 第 {f.recipeIndex+1} 菜 / 第 {f.ingredientIndex+1} 原料</p><p>{f.scaled.ingredient.raw} · 原量 {formatQuantity(f.scaled.originalQuantity)} · {f.scaled.ingredient.trust==='reviewed'?'来源有审核记录':'未经审核'}</p><p>基准人数 {f.scaled.baseServings??'未知'} · 倍数 {f.scaled.factor??'未换算'} · 计算量 {formatQuantity(f.scaled.quantity)}</p>{f.scaled.reason&&<p>{f.scaled.reason}</p>}</div>)}</details>}
  </>;
}
function ShoppingBuilder({actions,initial,previous,draftSource,onDone}:{actions:LocalActions;initial:ShoppingSource[];previous?:ShoppingList;draftSource:ShoppingSource|null;onDone:()=>void}){
  const mutation=useLocalMutation(actions);
  const [selected,setSelected]=useState(()=>structuredClone(initial)),[preview,setPreview]=useState<ShoppingListInput|null>(null),[error,setError]=useState('');
  const missing=previous&&initial.length<previous.sources.length;
  const disabled=mutation.disabled;
  function toggle(source:ShoppingSource,checked:boolean){setSelected(current=>checked?[...current.filter(s=>!(s.kind===source.kind&&s.id===source.id)),source]:current.filter(s=>!(s.kind===source.kind&&s.id===source.id)));setPreview(null);setError('');}
  function generate(){try{setPreview(buildShopping(selected));setError('');}catch(e){setError(e instanceof Error?e.message:'无法生成清单');}}
  async function save(){if(preview&&await mutation.run({type:'saveShoppingList',list:preview,expectedObjectRevision:null},'采购清单已保存'))onDone();}
  const diff=previous&&preview?diffShopping(previous,preview):null;
  return <div className="card"><h3>{previous?'重新生成采购清单':'新建采购清单'}</h3><p>仅选计划或当前草稿，实际饮食记录不能作为采购来源。确认后完整快照只保存在本地。</p>{missing&&<p>有来源已删除或不可用，请重新选择来源；旧版快照仍保留。</p>}
    {!preview?<><h4>选择来源</h4>{draftSource&&<label>{draftSource.revision===null?'当前本地未保存草稿':'当前本地草稿'}<input aria-label="选择当前本地草稿" type="checkbox" disabled={disabled} checked={selected.some(s=>s.kind==='draft')} onChange={e=>toggle(draftSource,e.target.checked)}/></label>}{actions.data.plans.map(p=><label key={p.id}>{p.date} {MEAL_LABELS[p.meal]} · {p.servings} 人 · {p.snapshots.map(s=>s.name).join('、')}<input aria-label={`选择计划 ${p.date} ${MEAL_LABELS[p.meal]} ${p.snapshots.map(s=>s.name).join('、')}`} type="checkbox" disabled={disabled} checked={selected.some(s=>s.kind==='plan'&&s.id===p.id)} onChange={e=>toggle(sourceFromPlan(p),e.target.checked)}/></label>)}{!draftSource&&!actions.data.plans.length&&<p>没有可选来源。可先手选菜到当前草稿，或保存计划。</p>}{selected.map(s=><SourceDetails key={`${s.kind}/${s.id}`} source={s} actions={actions} draftSource={draftSource}/>)}<button disabled={disabled||!selected.length} onClick={generate}>预览采购合计</button></>
      :<><h4>采购合计预览</h4><p>仅白名单单位与审核原料身份可合并。未知项要自行确认，适量不会估算成克数。显示最多六位小数，四舍五入标“约”；保存值不取整。</p>{preview.items.length?<ul>{preview.items.map(item=><li key={item.key}><ItemFacts item={item}/></li>)}</ul>:<p>来源未提供原料，暂无生成条目。保存后可添加手动项。</p>}{diff&&<div className="notice"><h4>与旧版差异</h4><p>新增 {diff.added.length} 项</p><p>移除 {diff.removed.length} 项</p><p>变化 {diff.changed.length} 项</p>{diff.added.map(i=><p key={i.key}>新增：{i.name} · {formatQuantity(i.quantity)} · 待确认 {i.unknownEntries.length} 项</p>)}{diff.removed.map(i=><p key={i.key}>移除：{i.name} · {formatQuantity(i.quantity)} · 待确认 {i.unknownEntries.length} 项</p>)}{diff.changed.map(({previous:old,next})=><p key={next.key}>变化：{next.name} · {formatQuantity(old.quantity)} → {formatQuantity(next.quantity)} · 待确认 {old.unknownEntries.length} → {next.unknownEntries.length}</p>)}{diff.previousEdits.map(i=><p key={i.key}>旧手改/已购/手动项：{i.name} · {i.userQuantity??'无手改'} · {i.purchased?'已购':'未购'}</p>)}<p>确认会另存新清单，不迁移手改用量、已购状态或手动项。旧版和全部编辑仍保留。</p></div>}<button disabled={disabled} onClick={()=>void save()}>{previous?'确认另存新版本':'确认保存新清单'}</button>{' '}<button disabled={mutation.saving} onClick={()=>setPreview(null)}>返回选择来源</button></>}
    {error&&<Notice error text={error}/>} {mutation.feedback}<button disabled={mutation.saving} onClick={onDone}>取消新清单</button>
  </div>;
}
function ShoppingEditor({actions,list,onDone}:{actions:LocalActions;list:ShoppingList;onDone:()=>void}){
  const mutation=useLocalMutation(actions);const [items,setItems]=useState(()=>structuredClone(list.items)),[name,setName]=useState(''),[quantity,setQuantity]=useState(''),[error,setError]=useState('');
  function change(key:string,patch:Partial<Pick<ShoppingItem,'userQuantity'|'purchased'>>){setItems(current=>current.map(i=>i.key===key?{...i,...patch}:i));}
  function manual(){if(!isText(name)||!isText(quantity,false)){setError('手动项名称必填，名称和用量文字不超过 20,000 字符');return;}setItems(current=>[...current,{key:`manual:${crypto.randomUUID()}`,name:name.trim(),ingredientId:null,form:'',part:null,quantity:null,unknownEntries:[],sources:[],userQuantity:quantity||null,purchased:false,manual:true}]);setName('');setQuantity('');setError('');}
  async function save(){if(await mutation.run({type:'saveShoppingList',list:{id:list.id,sources:list.sources,items},expectedObjectRevision:list.revision},'采购编辑已保存'))onDone();}
  return <Dialog title="编辑采购清单" busy={mutation.saving||actions.pending} onClose={onDone}><h3>编辑采购清单</h3><p>手改是你的采购文字，不改来源结构用量。没有填写并不代表零用量。</p><ul>{items.map(item=><li key={item.key}><ItemFacts item={item}/><label>手改用量 {item.name}<input value={item.userQuantity??''} disabled={mutation.disabled} onChange={e=>change(item.key,{userQuantity:e.target.value||null})}/></label><label>已购 {item.name}<input type="checkbox" checked={item.purchased} disabled={mutation.disabled} onChange={e=>change(item.key,{purchased:e.target.checked})}/></label>{item.manual&&<button disabled={mutation.disabled} aria-label={`移除手动项 ${item.name}`} onClick={()=>setItems(items.filter(i=>i.key!==item.key))}>移除手动项</button>}</li>)}</ul><label>手动项名称<input value={name} disabled={mutation.disabled} onChange={e=>setName(e.target.value)}/></label><label>手动项用量<input value={quantity} disabled={mutation.disabled} onChange={e=>setQuantity(e.target.value)}/></label><button disabled={mutation.disabled} onClick={manual}>添加手动项</button>{error&&<Notice error text={error}/>} {mutation.feedback}<button disabled={mutation.disabled} onClick={()=>void save()}>保存采购编辑</button>{' '}<button disabled={mutation.saving} onClick={onDone}>取消采购编辑</button></Dialog>;
}
export function Shopping({actions,initialSources=[],draftSource}:{actions:LocalActions;initialSources?:ShoppingSource[];draftSource:ShoppingSource|null}){
  const [builder,setBuilder]=useState<{initial:ShoppingSource[];previous?:ShoppingList}|null>(()=>initialSources.length?{initial:initialSources}:null),[editing,setEditing]=useState<ShoppingList|null>(null),[deleting,setDeleting]=useState<string|null>(null);
  function done(){setBuilder(null);setEditing(null);setDeleting(null);}
  function regenerate(list:ShoppingList){const current=list.sources.flatMap(s=>{if(s.kind==='draft')return draftSource?[draftSource]:[];const p=actions.data.plans.find(p=>p.id===s.id);return p?[sourceFromPlan(p)]:[];});done();setBuilder({initial:current,previous:list});}
  const disabled=actions.pending||!actions.writable;
  return <section aria-label="采购清单"><h3>采购清单</h3><p>来源变化只提示，不重算已保存清单。旧版本始终保留；重新生成需查看差异并确认另存。</p><button disabled={disabled} onClick={()=>{done();setBuilder({initial:[]});}}>新建采购清单</button>
    {builder&&<ShoppingBuilder key={builder.previous?.id??'new'} actions={actions} {...builder} draftSource={draftSource} onDone={done}/>}{editing&&<ShoppingEditor key={editing.id} actions={actions} list={editing} onDone={done}/>}{deleting&&<DeleteEditor actions={actions} store="shoppingLists" id={deleting} onDone={done}/>}
    {actions.data.shoppingLists.length?actions.data.shoppingLists.map(list=><article className="card" key={list.id}><h4>采购清单 {list.createdAt} · 编辑版本 {list.revision}</h4><p>清单身份 {list.id}</p>{list.sources.map(s=><SourceDetails key={`${s.kind}/${s.id}`} source={s} actions={actions} draftSource={draftSource}/>)}<ul>{list.items.map(item=><li key={item.key}><ItemFacts item={item}/></li>)}</ul><button disabled={disabled} aria-label={`编辑采购清单 ${list.id}`} onClick={()=>{done();setEditing(list);}}>编辑采购清单</button>{' '}<button disabled={disabled} aria-label={`重新生成采购清单 ${list.id}`} onClick={()=>regenerate(list)}>查看差异并重新生成</button>{' '}<button disabled={disabled} aria-label={`删除采购清单 ${list.id}`} onClick={()=>{done();setDeleting(list.id);}}>删除采购清单</button></article>):<p>还没有采购清单。</p>}
  </section>;
}
