@import "../../styles/theme.wxss";
page { min-height: 100%; background: {{background}}; color: {{text}}; } button::after { border: none; }
.page { min-height: 100vh; padding:{{space.2.rpx}}; box-sizing: border-box; } .heading { min-height: 76rpx; display: flex; align-items: baseline; gap:{{space.1.rpx*0.875}}; } .title { font-size:{{font.section.em}}; font-weight: 700; } .count { color: {{muted}}; font-size:{{font.caption.em}}; } .notice { padding:{{space.1.rpx*0.875}} {{space.1.rpx}}; margin-bottom:{{space.1.rpx*0.875}}; color: {{brand}}; background: {{brandSoft}}; border-radius:{{radius.0.rpx*0.66666667}}; font-size:{{font.caption.em}}; }
.tabs { display: grid; grid-template-columns: 1fr 1fr; background: {{border}}; border-radius:{{radius.0.rpx*0.83333333}}; padding:{{space.0.rpx*0.75}}; margin-bottom:{{space.1.rpx*0.875}}; } .tabs button { min-height: 68rpx; margin:0; background: transparent; color:{{muted}}; border-radius:{{radius.0.rpx*0.66666667}}; font-size:{{font.secondary.em}}; } .tabs button.active { background: {{card}}; color:{{brand}}; font-weight: 650; }
.search { display: grid; grid-template-columns: minmax(0, 1fr) 110rpx; gap:{{space.0.rpx*1.25}}; } .search input { min-width: 0; height: 80rpx; padding:0 {{space.1.rpx*1.0625}}; box-sizing: border-box; background: {{card}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx*0.83333333}}; font-size:{{font.secondary.em}}; } .search button, .primary, .more { min-height: 80rpx; background: {{brand}}; color: {{card}}; border-radius:{{radius.0.rpx*0.83333333}}; font-size:{{font.caption.em}}; }
.filters { display: grid; grid-template-columns: 1fr 1fr; gap:{{space.0.rpx*1.25}}; margin:{{space.0.rpx*1.5}} 0 {{space.1.rpx}}; } .filters picker { min-width: 0; } .filters picker view { min-height: 70rpx; padding:0 {{space.1.rpx}}; display: flex; align-items: center; background: {{card}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx*0.75}}; color: {{muted}}; font-size:{{font.caption.em}}; }
.state { min-height: 280rpx; display: flex; flex-direction: column; align-items: center; justify-content: center; color: {{muted}}; gap:{{space.1.rpx*1.125}}; } .list { display: flex; flex-direction: column; gap:{{space.0.rpx*1.5}}; } .dish { display: grid; grid-template-columns: minmax(0, 1fr) auto; align-items: center; gap:{{space.1.rpx*0.875}}; padding:{{space.1.rpx*1.25}}; background: {{card}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx}}; } .main { min-width: 0; } .row { display: flex; align-items: center; gap:{{space.0.rpx*1.25}}; } .dish-name { font-size:{{font.body.em}}; font-weight: 650; word-break: break-word; } .badge { padding:{{space.0.rpx*0.625}} {{space.0.rpx*1.125}}; border-radius:{{radius.0.rpx*0.58333333}}; font-size:{{font.caption.em}}; } .badge.on { color: {{brand}}; background: {{brandSoft}}; } .badge.off { color: {{warning}}; background: {{warningSoft}}; } .meta, .ingredients { display: block; margin-top:{{space.0.rpx*0.875}}; color: {{muted}}; font-size:{{font.caption.em}}; line-height: 1.45; word-break: break-word; } .ingredients { color: {{text}}; } .status { min-width: 88rpx; min-height: 60rpx; margin:0; padding:0 {{space.0.rpx*1.25}}; color: {{brand}}; background: {{brandSoft}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx*0.66666667}}; font-size:{{font.caption.em}}; } .arrow { font-size:{{font.page.em}}; color: {{muted}}; } .more { margin-top:{{space.0.rpx*0.75}}; } .end { padding:{{space.2.rpx*0.91666667}}; text-align: center; color: {{muted}}; font-size:{{font.caption.em}}; }
.form-title { display: block; margin-bottom:{{space.2.rpx*0.91666667}}; font-size:{{font.card.em}}; font-weight: 700; } .label { display: block; margin:{{space.1.rpx*1.1875}} 0 {{space.0.rpx}}; color: {{text}}; font-size:{{font.caption.em}}; font-weight: 600; } .form input, .form textarea { width: 100%; min-height: 80rpx; padding:{{space.1.rpx}}; box-sizing: border-box; background: {{card}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx*0.83333333}}; font-size:{{font.secondary.em}}; } .form textarea { min-height: 160rpx; line-height: 1.5; } .type-row { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap:{{space.0.rpx*0.875}}; } .type-row button { min-width: 0; min-height: 68rpx; margin:0; padding:0; background: {{card}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx*0.66666667}}; font-size:{{font.caption.em}}; } .type-row .selected { color: {{card}}; background: {{brand}}; border-color: {{brand}}; } .form-actions { display: grid; grid-template-columns: 1fr 1fr; gap:{{space.0.rpx*1.5}}; margin-top:{{space.2.rpx*1.1666667}}; } .form-actions button { min-height: 82rpx; margin:0; border-radius:{{radius.0.rpx*0.83333333}}; font-size:{{font.secondary.em}}; background: {{card}}; } .form-actions .primary { background: {{brand}}; color: {{card}}; }

/* 页面共享主题，适用于本页详情、表单和弹层。 */

/* Shared finish for legacy pages; layout and permission-specific states remain local. */
.ew-page { background:{{background}}; color:{{text}}; }
.ew-page .btn-primary, .ew-page .primary-btn, .ew-page .save-btn, .ew-page .primary-action, .ew-page .generate-btn { background:{{brand}}; border-radius:{{radius.1.rpx*1.2}}; }
.ew-page .choice-chip, .ew-page .ingredient-chip, .ew-page .count-btn, .ew-page .clear-btn, .ew-page .period-nav, .ew-page .filter-chip { min-height:{{controls.touchSize.px}}; min-width:{{controls.touchSize.px}}; box-sizing:border-box; }

/* Input and touch minima remain fixed under small screens/font changes. */
.ew-page button,.ew-page input,.ew-page .count-btn,.ew-page .choice-chip,.ew-page .filter-chip,.ew-page .date-picker{min-height:{{controls.touchSize.px}};box-sizing:border-box}
.ew-page .primary-btn,.ew-page .save-btn,.ew-page .primary-action,.ew-page .wx-login-btn{min-height:{{controls.primaryHeight.px}}}

/* Fixed CSS pixels protect the actual event node at the 320px baseline. */
.ew-hit-target, .ew-page .ew-hit-target { min-width:{{controls.touchSize.px}}; min-height:{{controls.touchSize.px}}; box-sizing:border-box; }
text.ew-hit-target { display:inline-flex; align-items:center; justify-content:center; }
picker.ew-hit-target { display:block; }
button { min-width:{{controls.touchSize.px}}; min-height:{{controls.primaryHeight.px}}; }

.tabs button { color:{{text}}; }

button.ew-hit-target, .ew-page button.ew-hit-target { min-height:{{controls.primaryHeight.px}}; }
