@import "../../styles/theme.wxss";
page { min-height: 100%; background: {{background}}; color: {{text}}; } button::after { border: none; }
.page { min-height: 100vh; padding: 24rpx; box-sizing: border-box; } .heading { min-height: 76rpx; display: flex; align-items: baseline; gap: 14rpx; } .title { font-size:1.3571em; font-weight: 700; } .count { color: {{muted}}; font-size:0.8571em; } .notice { padding: 14rpx 16rpx; margin-bottom: 14rpx; color: {{brand}}; background: {{brandSoft}}; border-radius: 8rpx; font-size:0.8571em; }
.tabs { display: grid; grid-template-columns: 1fr 1fr; background: {{border}}; border-radius: 10rpx; padding: 6rpx; margin-bottom: 14rpx; } .tabs button { min-height: 68rpx; margin: 0; background: transparent; color: #657069; border-radius: 8rpx; font-size:0.8929em; } .tabs button.active { background: {{card}}; color: #1d6f4e; font-weight: 650; }
.search { display: grid; grid-template-columns: minmax(0, 1fr) 110rpx; gap: 10rpx; } .search input { min-width: 0; height: 80rpx; padding: 0 17rpx; box-sizing: border-box; background: {{card}}; border: 2rpx solid {{border}}; border-radius: 10rpx; font-size:0.9286em; } .search button, .primary, .more { min-height: 80rpx; background: {{brand}}; color: {{card}}; border-radius: 10rpx; font-size:0.8571em; }
.filters { display: grid; grid-template-columns: 1fr 1fr; gap: 10rpx; margin: 12rpx 0 16rpx; } .filters picker { min-width: 0; } .filters picker view { min-height: 70rpx; padding: 0 16rpx; display: flex; align-items: center; background: {{card}}; border: 2rpx solid {{border}}; border-radius: 9rpx; color: {{muted}}; font-size:0.8571em; }
.state { min-height: 280rpx; display: flex; flex-direction: column; align-items: center; justify-content: center; color: {{muted}}; gap: 18rpx; } .list { display: flex; flex-direction: column; gap: 12rpx; } .dish { display: grid; grid-template-columns: minmax(0, 1fr) auto; align-items: center; gap: 14rpx; padding: 20rpx; background: {{card}}; border: 2rpx solid {{border}}; border-radius: 12rpx; } .main { min-width: 0; } .row { display: flex; align-items: center; gap: 10rpx; } .dish-name { font-size:1.0357em; font-weight: 650; word-break: break-word; } .badge { padding: 5rpx 9rpx; border-radius: 7rpx; font-size:0.8571em; } .badge.on { color: {{brand}}; background: {{brandSoft}}; } .badge.off { color: {{warning}}; background: {{warningSoft}}; } .meta, .ingredients { display: block; margin-top: 7rpx; color: {{muted}}; font-size:0.8571em; line-height: 1.45; word-break: break-word; } .ingredients { color: {{text}}; } .status { min-width: 88rpx; min-height: 60rpx; margin: 0; padding: 0 10rpx; color: {{brand}}; background: {{brandSoft}}; border: 2rpx solid {{border}}; border-radius: 8rpx; font-size:0.8571em; } .arrow { font-size:1.5em; color: {{muted}}; } .more { margin-top: 6rpx; } .end { padding: 22rpx; text-align: center; color: {{muted}}; font-size:0.8571em; }
.form-title { display: block; margin-bottom: 22rpx; font-size:1.1071em; font-weight: 700; } .label { display: block; margin: 19rpx 0 8rpx; color: {{text}}; font-size:0.8571em; font-weight: 600; } .form input, .form textarea { width: 100%; min-height: 80rpx; padding: 16rpx; box-sizing: border-box; background: {{card}}; border: 2rpx solid {{border}}; border-radius: 10rpx; font-size:0.9286em; } .form textarea { min-height: 160rpx; line-height: 1.5; } .type-row { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 7rpx; } .type-row button { min-width: 0; min-height: 68rpx; margin: 0; padding: 0; background: {{card}}; border: 2rpx solid {{border}}; border-radius: 8rpx; font-size:0.8571em; } .type-row .selected { color: {{card}}; background: {{brand}}; border-color: {{brand}}; } .form-actions { display: grid; grid-template-columns: 1fr 1fr; gap: 12rpx; margin-top: 28rpx; } .form-actions button { min-height: 82rpx; margin: 0; border-radius: 10rpx; font-size:0.8929em; background: {{card}}; } .form-actions .primary { background: {{brand}}; color: {{card}}; }

/* 页面共享主题，适用于本页详情、表单和弹层。 */

/* Shared finish for legacy pages; layout and permission-specific states remain local. */
.ew-page { background:{{background}}; color:{{text}}; }
.ew-page .btn-primary, .ew-page .primary-btn, .ew-page .save-btn, .ew-page .primary-action, .ew-page .generate-btn { background:{{brand}}; border-radius:24rpx; }
.ew-page .choice-chip, .ew-page .ingredient-chip, .ew-page .count-btn, .ew-page .clear-btn, .ew-page .period-nav, .ew-page .filter-chip { min-height:44px; min-width:44px; box-sizing:border-box; }

/* Input and touch minima remain fixed under small screens/font changes. */
.ew-page button,.ew-page input,.ew-page .count-btn,.ew-page .choice-chip,.ew-page .filter-chip,.ew-page .date-picker{min-height:44px;box-sizing:border-box}
.ew-page .primary-btn,.ew-page .save-btn,.ew-page .primary-action,.ew-page .wx-login-btn{min-height:48px}
