import { expect, test, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
// Browser acceptance source only. Browser launch is blocked in the current execution environment.
async function start(page:Page){await page.clock.setFixedTime(new Date('2026-10-09T12:00:00Z'));await page.route('**/api/public/catalog/dishes?*',route=>route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.goto('/');await expect(page.getByText('正在读取本地记录…')).toHaveCount(0);await page.getByRole('button',{name:'我的',exact:true}).click();}
async function read(page:Page){return page.evaluate(async()=>{const path='/src/data/repository.ts';const {openRepository}=await import(path);const opened=await openRepository({factory:indexedDB,now:()=>new Date(),uuid:()=>crypto.randomUUID()});if(!opened.ok)throw new Error(opened.error.message);const result=await opened.value.read();opened.value.close();if(!result.ok)throw new Error(result.error.message);return result.value;});}
async function seed(page:Page,name:string){await page.getByRole('button',{name:'新建自定义菜谱'}).click();await page.getByLabel('自定义菜名').fill(name);await page.getByRole('button',{name:'保存自定义菜谱'}).click();await expect(page.getByText('自定义菜谱已保存',{exact:true})).toBeVisible();}
async function select(page:Page,buffer:Buffer){await page.getByLabel('选择 JSON 备份').setInputFiles({name:'eatwhat-backup.json',mimeType:'application/json',buffer});await expect(page.getByText('备份已验证，尚未替换任何数据。')).toBeVisible();}
async function confirm(page:Page){await page.getByLabel('我已保存旧库备份，或接受覆盖且无法撤回').check();await page.getByRole('button',{name:'确认替换全部个人数据'}).click();}
test('A exports and B restores all personal snapshots; cancellation/bad files preserve B; loaded app works offline',async({page,browser})=>{
  await start(page);await seed(page,'A 的个人菜');const a=await read(page);const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'导出已保存个人备份'}).click();const download=await downloadPromise;const path=await download.path();if(!path)throw new Error('Download artifact unavailable');const buffer=await readFile(path);
  const bContext=await browser.newContext({baseURL:test.info().project.use.baseURL as string});const b=await bContext.newPage();await start(b);await seed(b,'B 的旧菜');const before=await read(b);await select(b,buffer);await b.getByRole('button',{name:'取消备份恢复'}).click();expect(await read(b)).toEqual(before);
  await b.getByLabel('选择 JSON 备份').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"__proto__":{}}')});await expect(b.getByText('Dangerous object key')).toBeVisible();expect(await read(b)).toEqual(before);
  await select(b,buffer);await bContext.setOffline(true);await confirm(b);await expect(b.getByText('个人备份已恢复。',{exact:true})).toBeVisible();const restored=await read(b);expect(restored.customRecipes.map((r:{snapshot:unknown})=>r.snapshot)).toEqual(a.customRecipes.map((r:{snapshot:unknown})=>r.snapshot));expect(restored.customRecipes.some((r:{snapshot:{name:string}})=>r.snapshot.name==='B 的旧菜')).toBe(false);await bContext.close();
});
test('C writes during preview, restore conflicts; after deliberate re-preview C stale editor cannot overwrite restored generation',async({page})=>{
  await start(page);await seed(page,'原菜');const d=await read(page);const buffer=Buffer.from(JSON.stringify({format:'eatwhat-web-backup',schemaVersion:1,appVersion:'0.1.0',catalogVersion:null,exportedAt:'2026-10-09T12:00:00.000Z',timeZone:'UTC',data:d}));
  const c=await page.context().newPage();await start(c);await c.getByRole('button',{name:'编辑自定义 原菜'}).click();await c.getByLabel('自定义菜名').fill('C 的旧表单');await select(page,buffer);
  await c.evaluate(async()=>{const path='/src/data/repository.ts';const {openRepository}=await import(path);const opened=await openRepository({factory:indexedDB,now:()=>new Date(),uuid:()=>crypto.randomUUID()});if(!opened.ok)throw new Error();const result=await opened.value.read();if(!result.ok)throw new Error();await opened.value.commit({type:'savePreferences',preferences:{...result.value.preferences,softPreferences:['foreign-write']}},result.value.meta.revision,'foreign');opened.value.close();});
  const before=await read(page);await confirm(page);await expect(page.getByText('预览后数据有更新，未覆盖。请重新预览这份已验证备份并重新确认。')).toBeVisible();expect(await read(page)).toEqual(before);await page.getByRole('button',{name:'重新预览已验证备份'}).click();await expect(page.getByText('本地预览版本：2')).toBeVisible();await confirm(page);await expect(page.getByText('个人备份已恢复。',{exact:true})).toBeVisible();await c.getByRole('button',{name:'保存自定义菜谱'}).click();await expect(c.getByText('另一个页面有更新，输入已保留。')).toBeVisible();expect((await read(page)).customRecipes[0].snapshot.name).toBe('原菜');
});
test('an injected all-store write abort preserves B and its restore request can retry',async({page})=>{
  await start(page);await seed(page,'B 保留菜');const d=await read(page),buffer=Buffer.from(JSON.stringify({format:'eatwhat-web-backup',schemaVersion:1,appVersion:'0.1.0',catalogVersion:null,exportedAt:'2026-10-09T12:00:00.000Z',timeZone:'UTC',data:d}));await select(page,buffer);
  await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(...args:Parameters<IDBObjectStore['put']>){if(this.name==='meta')this.transaction.abort();return original.apply(this,args);};(globalThis as unknown as {restorePut:()=>void}).restorePut=()=>{IDBObjectStore.prototype.put=original;};});
  const before=await read(page);await confirm(page);await expect(page.getByText('本地保存未完成，输入已保留。请重试。')).toBeVisible();expect(await read(page)).toEqual(before);await page.evaluate(()=>{(globalThis as unknown as {restorePut:()=>void}).restorePut();});await page.getByRole('button',{name:'确认替换全部个人数据'}).click();await expect(page.getByText('个人备份已恢复。',{exact:true})).toBeVisible();
});
