import { expect, test, type Page } from '@playwright/test';
// Public endpoint fixture only. This source has not been executed in the environment-blocked browser.
const directoryURL='**/api/public/catalog/dishes?*';
const directory={page:1,pageSize:100,total:1,list:[{id:940001,name:'采购端到端菜',type:'veg',steps:'测试做法',contentVersion:'shopping-e2e-only',quality:{reviewStatus:'VERIFIED',basePeople:2,servingsStatus:'VERIFIED',stepStatus:'VERIFIED',timeStatus:'UNKNOWN',issueCodes:[],ingredients:[{name:'大米',unit:'g',rawText:'大米 100g',rawQuantity:'100',rawUnit:'g',displayQuantity:'100g',quantityValue:100,preparation:'raw',role:null,identityStatus:'VERIFIED',quantityStatus:'VERIFIED'},{name:'盐',unit:null,rawText:'盐 适量',rawQuantity:null,rawUnit:null,displayQuantity:null,quantityValue:null,preparation:null,role:null,identityStatus:'VERIFIED',quantityStatus:'UNKNOWN'}]}}]};
async function start(page:Page,online=true){await page.clock.setFixedTime(new Date('2026-10-09T12:00:00Z'));await page.route(directoryURL,route=>online?route.fulfill({contentType:'application/json',body:JSON.stringify(directory)}):route.fulfill({status:503,contentType:'application/json',body:'{}'}));await page.goto('/');await expect(page.getByText('正在读取本地记录…')).toHaveCount(0);}
async function readData(page:Page){return page.evaluate(async()=>{const path='/src/data/repository.ts';const {openRepository}=await import(path);const opened=await openRepository({factory:indexedDB,now:()=>new Date(),uuid:()=>crypto.randomUUID()});if(!opened.ok)throw new Error(opened.error.message);const result=await opened.value.read();opened.value.close();if(!result.ok)throw new Error(result.error.message);return result.value;});}
test('selected plan → known total plus pending → manual edit → source change → diff/cancel/new independent version',async({page})=>{
  const requests:string[]=[];page.on('request',request=>requests.push(request.url()));await start(page);await page.getByLabel('用餐人数').fill('4');await expect(page.getByText('设置和草稿已保存',{exact:true})).toBeVisible();await page.getByRole('button',{name:'菜谱',exact:true}).click();await page.getByRole('button',{name:'手选 采购端到端菜',exact:true}).click();await expect(page.getByText('草稿已保存',{exact:true})).toBeVisible();await page.getByRole('button',{name:'今天吃什么',exact:true}).click();await page.getByRole('button',{name:'保存到日历'}).click();await page.getByRole('button',{name:'保存计划',exact:true}).click();await expect(page.getByText('计划已保存',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'日历',exact:true}).click();await page.getByRole('button',{name:'按计划建采购清单 采购端到端菜'}).click();await page.getByRole('button',{name:'预览采购合计'}).click();await expect(page.getByText('200 g',{exact:true})).toBeVisible();await expect(page.getByText('待确认 1 项',{exact:true})).toBeVisible();await page.getByRole('button',{name:'确认保存新清单'}).click();await expect(page.getByText('采购清单已保存',{exact:true})).toBeVisible();
  let data=await readData(page);const id=data.shoppingLists[0].id;await page.getByRole('button',{name:'编辑采购清单 '+id,exact:true}).click();await page.getByLabel('手改用量 大米 100g',{exact:true}).fill('买一袋');await page.getByLabel('已购 大米 100g',{exact:true}).check();await page.getByLabel('手动项名称').fill('垃圾袋');await page.getByLabel('手动项用量').fill('一包');await page.getByRole('button',{name:'添加手动项'}).click();await page.getByRole('button',{name:'保存采购编辑'}).click();await expect(page.getByText('采购编辑已保存',{exact:true})).toBeVisible();const old=(await readData(page)).shoppingLists[0];
  await page.getByRole('button',{name:'日历',exact:true}).click();await page.getByRole('button',{name:'编辑计划 采购端到端菜'}).click();await page.getByLabel('计划人数').fill('2');await page.getByRole('button',{name:'保存计划编辑'}).click();await expect(page.getByText('计划编辑已保存',{exact:true})).toBeVisible();await page.getByRole('button',{name:'我的',exact:true}).click();await expect(page.getByText('来源已变更',{exact:true})).toBeVisible();expect((await readData(page)).shoppingLists[0]).toEqual(old);
  await page.getByRole('button',{name:'重新生成采购清单 '+id,exact:true}).click();await page.getByRole('button',{name:'预览采购合计'}).click();await expect(page.getByText('变化 2 项',{exact:true})).toBeVisible();await expect(page.getByText('旧手改/已购/手动项：大米 100g · 买一袋 · 已购',{exact:true})).toBeVisible();const before=await readData(page);await page.getByRole('button',{name:'取消新清单'}).click();expect(await readData(page)).toEqual(before);
  await page.getByRole('button',{name:'重新生成采购清单 '+id,exact:true}).click();await page.getByRole('button',{name:'预览采购合计'}).click();await page.getByRole('button',{name:'确认另存新版本'}).click();await expect(page.getByText('采购清单已保存',{exact:true})).toBeVisible();data=await readData(page);expect(data.shoppingLists).toHaveLength(2);expect(data.shoppingLists[0]).toEqual(old);expect(data.shoppingLists[1].items.every((i:{userQuantity:string|null;purchased:boolean;manual:boolean})=>i.userQuantity===null&&!i.purchased&&!i.manual)).toBe(true);await page.reload();await page.getByRole('button',{name:'我的',exact:true}).click();expect((await readData(page)).shoppingLists).toEqual(data.shoppingLists);
  expect(requests.filter(url=>new URL(url).pathname.startsWith('/api/')).every(url=>new URL(url).pathname==='/api/public/catalog/dishes')).toBe(true);
});
test('API unavailable → manual custom draft → unknown shopping quantities → source deletion tracing and shopping trash restore',async({page})=>{
  await start(page,false);await page.getByRole('button',{name:'我的',exact:true}).click();await page.getByRole('button',{name:'新建自定义菜谱'}).click();await page.getByLabel('自定义菜名').fill('手写采购菜');await page.getByLabel('原料及用量原文，每行一项，可留空').fill('盐 适量');await page.getByRole('button',{name:'保存自定义菜谱'}).click();await expect(page.getByText('自定义菜谱已保存',{exact:true})).toBeVisible();await page.getByRole('button',{name:'手选 手写采购菜',exact:true}).click();await expect(page.getByText('草稿已保存',{exact:true})).toBeVisible();await page.getByRole('button',{name:'今天吃什么',exact:true}).click();await page.getByRole('button',{name:'从当前草稿建采购清单'}).click();await page.getByRole('button',{name:'预览采购合计'}).click();await expect(page.getByText('待确认 1 项',{exact:true})).toBeVisible();await page.getByRole('button',{name:'确认保存新清单'}).click();await expect(page.getByText('采购清单已保存',{exact:true})).toBeVisible();const original=(await readData(page)).shoppingLists[0];expect(original.items[0].quantity).toBeNull();
  await page.getByRole('button',{name:'删除自定义 手写采购菜'}).click();await page.getByRole('button',{name:'确认移入回收站'}).click();expect((await readData(page)).shoppingLists[0]).toEqual(original);await page.getByRole('button',{name:'删除采购清单 '+original.id,exact:true}).click();await page.getByRole('button',{name:'取消删除'}).click();expect((await readData(page)).shoppingLists[0]).toEqual(original);await page.getByRole('button',{name:'删除采购清单 '+original.id,exact:true}).click();await page.getByRole('button',{name:'确认移入回收站'}).click();expect((await readData(page)).shoppingLists).toHaveLength(0);await page.getByRole('button',{name:'恢复 采购清单 '+original.createdAt,exact:true}).click();await page.getByRole('button',{name:'确认恢复'}).click();await expect(page.getByText('已恢复',{exact:true})).toBeVisible();expect((await readData(page)).shoppingLists[0].items).toEqual(original.items);
});
