@import "../../styles/theme.wxss";
page { min-height: 100%; background: {{background}}; color: {{text}}; } button::after { border: none; }
.page { min-height: 100vh; padding:{{space.2.rpx}}; box-sizing: border-box; } .notice { padding:{{space.1.rpx*0.875}} {{space.1.rpx}}; margin-bottom:{{space.1.rpx*0.875}}; color: {{brand}}; background: {{brandSoft}}; border-radius:{{radius.0.rpx*0.66666667}}; font-size:{{font.caption.em}}; } .state { min-height: 300rpx; display: flex; flex-direction: column; align-items: center; justify-content: center; color: {{muted}}; gap:{{space.1.rpx*1.25}}; } .state.compact { min-height: 180rpx; }
.summary { padding:{{space.2.rpx*0.91666667}}; background: {{card}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx}}; } .summary-top { display: flex; justify-content: space-between; align-items: flex-start; gap:{{space.1.rpx}}; } .name { display: block; font-size:{{font.section.em}}; font-weight: 700; word-break: break-word; } .meta { display: block; margin-top:{{space.0.rpx}}; color: {{muted}}; font-size:{{font.caption.em}}; word-break: break-word; } .badge { padding:{{space.0.rpx*0.75}} {{space.0.rpx*1.375}}; border-radius:{{radius.0.rpx*0.58333333}}; font-size:{{font.caption.em}}; } .badge.on { color: {{brand}}; background: {{brandSoft}}; } .badge.off { color: {{warning}}; background: {{warningSoft}}; } .status { width: 100%; margin-top:{{space.1.rpx*1.25}}; min-height: 70rpx; border: 2rpx solid #d7e2dc; background: #f4faf6; color: {{brand}}; border-radius:{{radius.0.rpx*0.75}}; font-size:{{font.caption.em}}; }
.section-head { display: flex; justify-content: space-between; align-items: center; margin:{{space.2.rpx*1.1666667}} 0 {{space.1.rpx*0.875}}; } .section-title, .form-title { font-size:{{font.body.em}}; font-weight: 700; } .add { min-width: 104rpx; min-height: 66rpx; margin:0; background: {{brand}}; color: {{card}}; border-radius:{{radius.0.rpx*0.75}}; font-size:{{font.caption.em}}; } .list { display: flex; flex-direction: column; gap:{{space.0.rpx*1.5}}; } .dish { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap:{{space.1.rpx*0.875}}; padding:{{space.1.rpx*1.25}}; background: {{card}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx}}; } .dish-main { min-width: 0; } .dish-name { font-size:{{font.body.em}}; font-weight: 650; } .ingredients { display: block; margin-top:{{space.0.rpx*1.125}}; color: {{text}}; font-size:{{font.caption.em}}; line-height: 1.5; word-break: break-word; } .actions { display: flex; flex-direction: column; gap:{{space.0.rpx}}; } .actions button { min-width: 88rpx; min-height: 58rpx; margin:0; padding:0 {{space.0.rpx*1.25}}; border-radius:{{radius.0.rpx*0.66666667}}; background: #eef4f0; color: {{brand}}; font-size:{{font.caption.em}}; } .actions .danger { color:{{danger}}; background: {{dangerSoft}}; }
.form { padding-bottom:{{space.3.rpx*0.9375}}; } .form-title { display: block; margin-bottom:{{space.2.rpx*0.91666667}}; } .label { display: block; margin:{{space.1.rpx*1.25}} 0 {{space.0.rpx*1.125}}; color: {{text}}; font-size:{{font.caption.em}}; font-weight: 600; } .form input, .form textarea { width: 100%; min-height: 80rpx; padding:{{space.1.rpx*1.0625}}; box-sizing: border-box; background: {{card}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx*0.83333333}}; font-size:{{font.secondary.em}}; } .form textarea { min-height: 160rpx; line-height: 1.5; } .types { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap:{{space.0.rpx}}; } .types button { min-width: 0; min-height: 68rpx; margin:0; padding:0; background: {{card}}; border: 2rpx solid {{border}}; border-radius:{{radius.0.rpx*0.66666667}}; font-size:{{font.caption.em}}; } .types button.selected { color: {{card}}; background: {{brand}}; border-color: {{brand}}; } .form-actions { display: grid; grid-template-columns: 1fr 1fr; gap:{{space.0.rpx*1.5}}; margin-top:{{space.2.rpx*1.1666667}}; } .form-actions button, .primary { min-height: 82rpx; margin:0; border-radius:{{radius.0.rpx*0.83333333}}; font-size:{{font.secondary.em}}; } .form-actions button { background: {{card}}; color: {{text}}; } .form-actions .primary, .primary { background: {{brand}}; color: {{card}}; }

/* 页面共享主题，适用于本页详情、表单和弹层。 */

/* Shared finish for legacy pages; layout and permission-specific states remain local. */
.ew-page { background:{{background}}; color:{{text}}; }
.ew-page .btn-primary, .ew-page .primary-btn, .ew-page .save-btn, .ew-page .primary-action, .ew-page .generate-btn { background:{{brand}}; border-radius:{{radius.1.rpx*1.2}}; }
.ew-page .choice-chip, .ew-page .ingredient-chip, .ew-page .count-btn, .ew-page .clear-btn, .ew-page .period-nav, .ew-page .filter-chip { min-height:{{controls.touchSize.px}}; min-width:{{controls.touchSize.px}}; box-sizing:border-box; }

/* Input and touch minima remain fixed under small screens/font changes. */
.ew-page button,.ew-page input,.ew-page .count-btn,.ew-page .choice-chip,.ew-page .filter-chip,.ew-page .date-picker{min-height:{{controls.touchSize.px}};box-sizing:border-box}
.ew-page .primary-btn,.ew-page .save-btn,.ew-page .primary-action,.ew-page .wx-login-btn{min-height:{{controls.primaryHeight.px}}}

/* Fixed CSS pixels protect the actual event node at the 320px baseline. */
.ew-hit-target, .ew-page .ew-hit-target { min-width:{{controls.touchSize.px}}; min-height:{{controls.touchSize.px}}; box-sizing:border-box; }
text.ew-hit-target { display:inline-flex; align-items:center; justify-content:center; }
picker.ew-hit-target { display:block; }
button { min-width:{{controls.touchSize.px}}; min-height:{{controls.primaryHeight.px}}; }

button.ew-hit-target, .ew-page button.ew-hit-target { min-height:{{controls.primaryHeight.px}}; }
