@import "../../styles/theme.wxss";
page { min-height: 100%; background: {{background}}; color: {{text}}; } button::after { border: none; }
.page { min-height: 100vh; padding: 24rpx; box-sizing: border-box; } .notice { padding: 14rpx 16rpx; margin-bottom: 14rpx; color: {{brand}}; background: {{brandSoft}}; border-radius: 8rpx; font-size:0.8571em; } .state { min-height: 300rpx; display: flex; flex-direction: column; align-items: center; justify-content: center; color: {{muted}}; gap: 20rpx; } .state.compact { min-height: 180rpx; }
.summary { padding: 22rpx; background: {{card}}; border: 2rpx solid {{border}}; border-radius: 12rpx; } .summary-top { display: flex; justify-content: space-between; align-items: flex-start; gap: 16rpx; } .name { display: block; font-size:1.2143em; font-weight: 700; word-break: break-word; } .meta { display: block; margin-top: 8rpx; color: {{muted}}; font-size:0.8571em; word-break: break-word; } .badge { padding: 6rpx 11rpx; border-radius: 7rpx; font-size:0.8571em; } .badge.on { color: {{brand}}; background: {{brandSoft}}; } .badge.off { color: {{warning}}; background: {{warningSoft}}; } .status { width: 100%; margin-top: 20rpx; min-height: 70rpx; border: 2rpx solid #d7e2dc; background: #f4faf6; color: {{brand}}; border-radius: 9rpx; font-size:0.8571em; }
.section-head { display: flex; justify-content: space-between; align-items: center; margin: 28rpx 0 14rpx; } .section-title, .form-title { font-size:1.0714em; font-weight: 700; } .add { min-width: 104rpx; min-height: 66rpx; margin: 0; background: {{brand}}; color: {{card}}; border-radius: 9rpx; font-size:0.8571em; } .list { display: flex; flex-direction: column; gap: 12rpx; } .dish { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 14rpx; padding: 20rpx; background: {{card}}; border: 2rpx solid {{border}}; border-radius: 12rpx; } .dish-main { min-width: 0; } .dish-name { font-size:1.0357em; font-weight: 650; } .ingredients { display: block; margin-top: 9rpx; color: {{text}}; font-size:0.8571em; line-height: 1.5; word-break: break-word; } .actions { display: flex; flex-direction: column; gap: 8rpx; } .actions button { min-width: 88rpx; min-height: 58rpx; margin: 0; padding: 0 10rpx; border-radius: 8rpx; background: #eef4f0; color: {{brand}}; font-size:0.8571em; } .actions .danger { color: #a13b36; background: {{dangerSoft}}; }
.form { padding-bottom: 30rpx; } .form-title { display: block; margin-bottom: 22rpx; } .label { display: block; margin: 20rpx 0 9rpx; color: {{text}}; font-size:0.8571em; font-weight: 600; } .form input, .form textarea { width: 100%; min-height: 80rpx; padding: 17rpx; box-sizing: border-box; background: {{card}}; border: 2rpx solid {{border}}; border-radius: 10rpx; font-size:0.9286em; } .form textarea { min-height: 160rpx; line-height: 1.5; } .types { display: grid; grid-template-columns: repeat(5, minmax(0, 1fr)); gap: 8rpx; } .types button { min-width: 0; min-height: 68rpx; margin: 0; padding: 0; background: {{card}}; border: 2rpx solid {{border}}; border-radius: 8rpx; font-size:0.8571em; } .types button.selected { color: {{card}}; background: {{brand}}; border-color: {{brand}}; } .form-actions { display: grid; grid-template-columns: 1fr 1fr; gap: 12rpx; margin-top: 28rpx; } .form-actions button, .primary { min-height: 82rpx; margin: 0; border-radius: 10rpx; font-size:0.9286em; } .form-actions button { background: {{card}}; color: {{text}}; } .form-actions .primary, .primary { background: {{brand}}; color: {{card}}; }

/* 页面共享主题，适用于本页详情、表单和弹层。 */

/* Shared finish for legacy pages; layout and permission-specific states remain local. */
.ew-page { background:{{background}}; color:{{text}}; }
.ew-page .btn-primary, .ew-page .primary-btn, .ew-page .save-btn, .ew-page .primary-action, .ew-page .generate-btn { background:{{brand}}; border-radius:24rpx; }
.ew-page .choice-chip, .ew-page .ingredient-chip, .ew-page .count-btn, .ew-page .clear-btn, .ew-page .period-nav, .ew-page .filter-chip { min-height:44px; min-width:44px; box-sizing:border-box; }

/* Input and touch minima remain fixed under small screens/font changes. */
.ew-page button,.ew-page input,.ew-page .count-btn,.ew-page .choice-chip,.ew-page .filter-chip,.ew-page .date-picker{min-height:44px;box-sizing:border-box}
.ew-page .primary-btn,.ew-page .save-btn,.ew-page .primary-action,.ew-page .wx-login-btn{min-height:48px}
