// Generated by scripts/build_ui_assets.py; edit design/tokens.json.
module.exports = {
  "brand": "#28634E",
  "brandSoft": "#EDF3ED",
  "background": "#F8F7F2",
  "card": "#FFFFFF",
  "text": "#25332B",
  "muted": "#617066",
  "border": "#D9E1D5",
  "danger": "#A93B30",
  "dangerSoft": "#FFF0ED",
  "warning": "#75501A",
  "warningSoft": "#FFF1DB",
  "disabled": "#E8EBE5",
  "primaryHeight": 48,
  "touchSize": 44
}
