"""Rebuild deterministic SVG masters, mini-program PNG exports and token bindings."""
from pathlib import Path
import json
import re
import cairosvg

ROOT = Path(__file__).resolve().parents[1]
TOKENS = json.loads((ROOT / "design/tokens.json").read_text(encoding="utf-8"))
COLOR = TOKENS["colors"]
PATHS = {
    "today": 'M4 9h16v11H4z M7 9V5h10v4 M9 5V3m6 2V3 M8 13h8m-8 3h5',
    "recipes": 'M4 4h7l1 2 1-2h7v16h-7l-1 1-1-1H4z M12 6v15 M7 8h2m6 0h2 M7 12h2m6 0h2',
    "plan": 'M5 5h14v16H5z M8 3v4m8-4v4 M5 10h14 M8 14h2m4 0h2 M8 17h2',
    "profile": 'M8 7a4 4 0 1 0 8 0a4 4 0 1 0-8 0 M4 21v-3a8 5 0 0 1 16 0v3',
    "arrow-left": 'M20 12H4 M10 6l-6 6 6 6',
    "chevron-right": 'M9 5l7 7-7 7',
    "close": 'M6 6l12 12 M18 6 6 18',
    "more": 'M4 12h.1 M12 12h.1 M20 12h.1',
    "search": 'M3 10a7 7 0 1 0 14 0a7 7 0 1 0-14 0 M15 15l6 6',
    "filter": 'M3 5h18l-7 8v6l-4 2v-8z',
    "add": 'M12 4v16 M4 12h16',
    "edit": 'M14 4l6 6 M3 21l2-7L17 2l5 5-12 12z',
    "delete": 'M3 6h18 M8 6V3h8v3 M5 6l1 15h12l1-15 M10 10v7m4-7v7',
    "share": 'M9 8l7-4 M9 16l7 4 M3 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0 M16 4a2 2 0 1 0 4 0a2 2 0 1 0-4 0 M16 20a2 2 0 1 0 4 0a2 2 0 1 0-4 0',
    "refresh": 'M20 8a9 9 0 0 0-16 0 M20 3v5h-5 M4 16a9 9 0 0 0 16 0 M4 21v-5h5',
    "check": 'M4 12l5 5L20 6',
    "favorite": 'M12 21S2 15 2 8a5 5 0 0 1 10-1a5 5 0 0 1 10 1c0 7-10 13-10 13z',
    "favorite-filled": 'M12 21S2 15 2 8a5 5 0 0 1 10-1a5 5 0 0 1 10 1c0 7-10 13-10 13z',
    "settings": 'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1z M9 12a3 3 0 1 0 6 0a3 3 0 1 0-6 0',
    "info": 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0-20 0 M12 11v6m0-10h.1',
    "history": 'M4 7a9 9 0 1 1-1 8 M3 3v5h5 M12 7v5l4 2',
    "calendar": 'M4 5h16v16H4z M8 3v4m8-4v4 M4 10h16 M8 14h.1m4 0h.1m4 0h.1 M8 18h.1m4 0h.1',
    "statistics": 'M3 3v18h18 M7 17v-5m5 5V8m5 9V4',
    "clock": 'M2 12a10 10 0 1 0 20 0a10 10 0 1 0-20 0 M12 6v6l4 3',
    "users": 'M4 7a3 3 0 1 0 6 0a3 3 0 1 0-6 0 M14 7a3 3 0 1 0 6 0a3 3 0 1 0-6 0 M2 20v-3a5 4 0 0 1 10 0v3 M14 20v-3a4 4 0 0 1 8 0v3',
    "recipe": 'M6 3h12v18H6z M3 7h4m-4 5h4m-4 5h4 M10 7h5m-5 5h5m-5 5h3',
    "ingredient": 'M4 19C3 7 11 3 21 3c0 12-6 18-17 16z M4 19 17 7 M10 13v-4m0 4h4',
    "shopping-basket": 'M3 10h18l-3 11H6z M7 10l4-7m6 7-4-7 M9 14v3m6-3v3',
    "nutrition": 'M12 21C3 20 1 8 6 6c3-2 4 0 6 0s3-2 6 0c5 2 3 14-6 15z M12 6c0-3 3-4 6-4 M12 7V4',
    "servings": 'M3 13h18c0 6-3 8-9 8s-9-2-9-8z M5 9h14 M8 6V3m4 3V2m4 4V3',
    "cooking-pot": 'M5 8h14v10c0 3-14 3-14 0z M3 8h18 M9 5h6m-3 0V3 M2 12h3m14 0h3',
    "agent-spark": 'M12 2l3 7 7 3-7 3-3 7-3-7-7-3 7-3z',
    "agent-arrange": 'M3 5h11m-11 7h11m-11 7h11 M18 8l2 4 3 1-3 1-2 4-2-4-3-1 3-1z',
    "agent-regenerate": 'M20 9a8 8 0 0 0-15-3 M20 4v5h-5 M4 15a8 8 0 0 0 15 3 M4 20v-5h5 M12 9l1 2 2 1-2 1-1 2-1-2-2-1 2-1z',
    "agent-replace-dish": 'M3 8h17l-4-4 M21 16H4l4 4 M9 12h6',
    "agent-adjust": 'M4 6h16 M4 12h16 M4 18h16 M8 3v6m8 0v6m-6 0v6',
}
ILLUSTRATIONS = {
    "empty-favorites": '<path d="M58 48h44l8 8 8-8h44v104h-44l-8 8-8-8H58z" fill="#fff"/><path d="M110 56v101 M74 74h22m-22 20h22m32 35c-30-17-34-36-21-39 7-3 14 3 16 8 4-8 11-11 17-8 16 7 5 23-12 39z"/>',
    "empty-shopping": '<path d="M44 85h132l-18 68H62z" fill="#fff"/><path d="M70 85l30-38m50 38-30-38 M82 109v20m28-20v20m28-20v20"/><path d="M159 62c3-20 15-22 28-19-2 21-12 27-28 19z" fill="#EDF3ED"/>',
    "empty-plan": '<rect x="55" y="46" width="112" height="110" rx="14" fill="#fff"/><path d="M78 35v25m65-25v25 M56 77h110 M80 99h22m20 0h22 M80 125h22"/><circle cx="156" cy="148" r="26" fill="#EDF3ED"/><path d="M156 133v16l10 6"/>',
    "agent-thinking": '<path d="M45 111h130c-4 44-28 54-65 54s-61-10-65-54z" fill="#fff"/><path d="M71 86c-14-17 14-21 0-38m39 38c-14-17 14-21 0-38m39 38c-14-17 14-21 0-38"/><path d="M182 30l5 12 12 5-12 5-5 12-5-12-12-5 12-5z" fill="#EDF3ED"/>',
    "meal-success": '<circle cx="110" cy="105" r="63" fill="#fff"/><circle cx="110" cy="105" r="45"/><path d="M82 104l19 20 39-39"/><path d="M34 154c-5-24 5-31 23-28-1 24-10 30-23 28z M161 54c2-22 15-25 28-22-2 21-13 27-28 22z" fill="#EDF3ED"/>',
}


def build():
    tokens = {**COLOR, **TOKENS["controls"]}
    (ROOT / "utils/ui-tokens.js").write_text("// Generated by scripts/build_ui_assets.py; edit design/tokens.json.\nmodule.exports = " + json.dumps(tokens, indent=2) + "\n", encoding="utf-8")
    template = (ROOT / "design/theme.wxss.tpl").read_text(encoding="utf-8")
    for key, value in COLOR.items():
        template = template.replace("{{" + key + "}}", value)
    (ROOT / "styles/theme.wxss").write_text("/* Generated from design/tokens.json and theme.wxss.tpl. */\n" + template, encoding="utf-8")
    for item in json.loads((ROOT / "design/wxss-manifest.json").read_text(encoding="utf-8")):
        contents = (ROOT / item["source"]).read_text(encoding="utf-8")
        for key, value in COLOR.items():
            contents = contents.replace("{{" + key + "}}", value)
        (ROOT / item["output"]).write_text("/* Generated token bindings; edit corresponding design/wxss template. */\n" + contents, encoding="utf-8")
    icons = ROOT / "assets/icons"
    illustrations = ROOT / "assets/illustrations"
    icons.mkdir(parents=True, exist_ok=True)
    illustrations.mkdir(parents=True, exist_ok=True)
    tabs = ["today", "recipes", "plan", "profile"]
    for name, path in PATHS.items():
        for selected in ([False, True] if name in tabs else [False]):
            variant = name + ("-selected" if selected else "")
            color = COLOR["brand"] if selected or name not in tabs else COLOR["muted"]
            fill = color if name == "favorite-filled" else "none"
            svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="{path}" fill="{fill}" stroke="{color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>'
            (icons / (variant + ".svg")).write_text(svg, encoding="utf-8")
            cairosvg.svg2png(bytestring=svg.encode(), output_width=72, output_height=72, write_to=str(icons / (variant + ".png")))
    for name, contents in ILLUSTRATIONS.items():
        svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 220 200"><ellipse cx="110" cy="178" rx="69" ry="7" fill="{COLOR["brandSoft"]}"/><g stroke="{COLOR["brand"]}" fill="none" stroke-width="3" stroke-linecap="round" stroke-linejoin="round">{contents}</g></svg>'
        (illustrations / (name + ".svg")).write_text(svg, encoding="utf-8")
        cairosvg.svg2png(bytestring=svg.encode(), output_width=440, output_height=400, write_to=str(illustrations / (name + ".png")))
    manifest = {"style": "warm-rounded-line", "icons": list(PATHS), "tabs": tabs, "illustrations": list(ILLUSTRATIONS)}
    (ROOT / "design/asset-manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    app_file = ROOT / "app.json"
    app = json.loads(app_file.read_text(encoding="utf-8"))
    for item, name in zip(app["tabBar"]["list"], tabs):
        item.update(iconPath=f"assets/icons/{name}.png", selectedIconPath=f"assets/icons/{name}-selected.png")
    app_file.write_text(json.dumps(app, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    build()
    print("Built token bindings, 40 icon variants and 5 illustrations")
