@import "../../styles/theme.wxss";
.page{height:100vh;display:flex;flex-direction:column;background:#f7fbf9;box-sizing:border-box;padding-bottom:env(safe-area-inset-bottom)}
.assistant-head{display:flex;align-items:center;justify-content:space-between;padding:{{space.2.rpx}} {{space.3.rpx}} {{space.1.rpx*1.125}};background:linear-gradient(180deg,#e7f8f1 0%,{{card}} 100%);flex-shrink:0}
.head-title{font-size:{{font.section.em}};font-weight:700;color:{{brand}};line-height:1.25}.head-subtitle{margin-top:{{space.0.rpx}};font-size:{{font.caption.em}};color:{{muted}}}
.clear-btn{display:flex;align-items:center;gap:{{space.0.rpx}};color:{{muted}};font-size:{{font.caption.em}};padding:{{space.0.rpx*1.25}}}.clear-btn .line-icon{width:28rpx;height:28rpx}
.task-summary{display:flex;align-items:center;gap:{{space.0.rpx*1.25}};margin:0 {{space.2.rpx}} {{space.0.rpx}};padding:{{space.0.rpx*1.5}} {{space.1.rpx}};background:{{card}};border:1rpx solid #dcece5;border-radius:{{radius.0.rpx}};color:{{brand}};font-size:{{font.caption.em}};flex-shrink:0}.task-summary text:last-child{margin-left:auto;color:{{muted}}}.task-dot{width:12rpx;height:12rpx;border-radius:50%;background:{{brand}}}.task-dot-loading{animation:blink 1.2s infinite}.stop-task{color:{{brand}}!important;padding-left:{{space.1.rpx*1.125}}}.mode-badge{margin-left:{{space.0.rpx*1.25}}!important;padding:{{space.0.rpx*0.25}} {{space.0.rpx*1.25}};border-radius:{{radius.0.rpx*1.1666667}};background:#e8f8f1;color:{{brand}}!important;font-size:{{font.caption.em}}}
.msg-list{flex:1;min-height:0;padding:{{space.1.rpx*1.125}} {{space.2.rpx}} {{space.2.rpx}};box-sizing:border-box;overflow-y:auto}.welcome-block{text-align:center;padding:{{space.6.rpx*1.125}} {{space.4.rpx}} {{space.4.rpx*1.05}}}.welcome-icon{width:92rpx;height:92rpx;border-radius:50%;margin:0 auto {{space.2.rpx}};display:flex;align-items:center;justify-content:center;background:#dff4ec;color:{{brand}}}.welcome-icon .line-icon{width:48rpx;height:48rpx}.welcome-title{font-size:{{font.card.em}};font-weight:600;color:{{brand}}}.welcome-text{font-size:{{font.secondary.em}};line-height:1.7;color:{{muted}};margin-top:{{space.1.rpx*0.875}}}
.msg-row{display:flex;align-items:flex-start;margin-bottom:{{space.1.rpx*1.25}}}.row-right{flex-direction:row-reverse}.avatar-bot-fb,.avatar-user,.avatar-user-fb{width:64rpx;height:64rpx;border-radius:50%;flex-shrink:0;margin:0 {{space.0.rpx*1.25}}}.avatar-bot-fb,.avatar-user-fb{display:flex;align-items:center;justify-content:center}.avatar-bot-fb{background:#e1f4ed;color:{{brand}}}.avatar-user-fb{background:#e7ecea;color:{{muted}}}.avatar-bot-fb .line-icon,.avatar-user-fb .line-icon{width:36rpx;height:36rpx}.msg-bubble{max-width:78%;padding:{{space.1.rpx}} {{space.1.rpx*1.25}};border-radius:{{radius.1.rpx*0.9}};font-size:{{font.body.em}};line-height:1.65;white-space:pre-wrap;word-break:break-word}.bubble-left{background:{{card}};color:{{text}};border:1rpx solid #deebe5;border-top-left-radius:6rpx}.bubble-right{background:{{brand}};color:{{card}};border-top-right-radius:6rpx}
.dish-cards{display:flex;flex-direction:column;gap:{{space.0.rpx*1.25}};padding:0 {{space.0.rpx}} {{space.0.rpx*1.5}} {{space.6.rpx*1.3125}}}.dish-card{display:flex;align-items:center;min-height:92rpx;padding:{{space.0.rpx*1.5}} {{space.1.rpx*0.875}};background:{{card}};border:1rpx solid {{brandSoft}};border-radius:{{radius.0.rpx}};box-sizing:border-box}.dc-img,.dc-img-fb{width:100rpx;height:76rpx;border-radius:{{radius.0.rpx*0.66666667}};flex-shrink:0;margin-right:{{space.1.rpx*0.875}};background:#eff6f3}.dc-img-fb{display:flex;align-items:center;justify-content:center;color:{{brand}}}.dc-img-fb .line-icon{width:36rpx;height:36rpx}.dc-info,.plan-dish-main{flex:1;min-width:0}.dc-name,.plan-dish-name{display:block;font-size:{{font.body.em}};font-weight:600;color:{{text}};overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dc-reason,.plan-reason{display:block;margin-top:{{space.0.rpx*0.75}};font-size:{{font.caption.em}};color:{{muted}};white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dc-arrow,.plan-arrow{font-size:{{font.section.em}};color:{{muted}};margin-left:{{space.0.rpx*1.25}}}
.plan-block{margin:{{space.0.rpx*0.75}} {{space.0.rpx}} {{space.1.rpx*1.25}};padding:{{space.1.rpx*1.25}};background:{{card}};border:1rpx solid {{brandSoft}};border-radius:{{radius.0.rpx*1.1666667}}}.plan-heading{display:flex;justify-content:space-between;align-items:center;font-size:{{font.body.em}};color:{{brand}};font-weight:600}.plan-version{font-size:{{font.caption.em}};color:{{muted}};font-weight:400}.meal-group{margin-top:{{space.1.rpx*1.125}}}.meal-heading{display:flex;justify-content:space-between;color:{{muted}};font-size:{{font.caption.em}};padding-bottom:{{space.0.rpx}};border-bottom:1rpx solid #edf3f0}.plan-dish{display:flex;align-items:center;padding:{{space.1.rpx}} 0;border-bottom:1rpx solid #f0f4f2}.plan-dish:last-child{border-bottom:0}.plan-actions{display:flex;gap:{{space.0.rpx*1.5}};margin-top:{{space.1.rpx}}}.secondary-action,.primary-action{border-radius:{{radius.0.rpx*0.83333333}};font-size:{{font.secondary.em}};line-height:70rpx;height:70rpx;padding:0 {{space.1.rpx*1.25}};box-sizing:border-box}.secondary-action{flex:1;color:{{brand}};background:#f0faf6;border:1rpx solid #cce9dc}.plan-warning{display:flex;align-items:flex-start;gap:{{space.0.rpx}};margin-top:{{space.0.rpx*1.5}};padding:{{space.0.rpx*1.5}};background:#fff9e9;color:{{warning}};font-size:{{font.caption.em}};line-height:1.5;border-radius:{{radius.0.rpx*0.66666667}}}.plan-warning .line-icon{width:28rpx;height:28rpx;flex-shrink:0}
.howto-block{margin:{{space.0.rpx*0.75}} {{space.0.rpx}} {{space.1.rpx*1.25}};padding:{{space.1.rpx*1.25}};background:{{card}};border:1rpx solid {{brandSoft}};border-radius:{{radius.0.rpx*1.1666667}}}.howto-heading{display:flex;align-items:center;justify-content:space-between;color:{{brand}};font-size:{{font.body.em}};font-weight:600}.howto-source{font-size:{{font.caption.em}};font-weight:400;color:{{muted}}}.howto-step{display:flex;align-items:flex-start;gap:{{space.0.rpx*1.5}};margin-top:{{space.1.rpx}};color:{{muted}};font-size:{{font.secondary.em}};line-height:1.55}.step-index{width:34rpx;height:34rpx;line-height:34rpx;border-radius:50%;background:#e1f4ed;color:{{brand}};text-align:center;font-size:{{font.caption.em}};flex-shrink:0}.step-text{flex:1;word-break:break-word}.howto-empty{margin-top:{{space.1.rpx}};color:{{muted}};font-size:{{font.caption.em}};line-height:1.5}
.alternatives-block{margin:0 {{space.0.rpx}} {{space.1.rpx*1.25}};padding:{{space.1.rpx*1.125}} {{space.1.rpx*1.25}};background:#fbfefd;border:1rpx solid #e3eee9;border-radius:{{radius.0.rpx*1.1666667}}}.alternatives-heading{display:flex;justify-content:space-between;align-items:center;color:{{brand}};font-size:{{font.secondary.em}}}.alternatives-heading text:last-child{font-size:{{font.caption.em}};color:{{muted}}}.alternative-row{display:flex;align-items:center;padding:{{space.1.rpx*0.875}} 0;border-bottom:1rpx solid #edf3f0}.alternative-row:last-child{border-bottom:0}.alternative-main{flex:1;min-width:0}.alternative-name{display:block;color:{{brand}};font-size:{{font.secondary.em}}}.alternative-reason{display:block;margin-top:{{space.0.rpx*0.5}};color:{{muted}};font-size:{{font.caption.em}};white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.action-bar{display:flex;gap:{{space.0.rpx*1.5}};flex-wrap:wrap;padding:{{space.1.rpx*0.875}} {{space.2.rpx}} {{space.0.rpx*0.75}};background:{{card}};border-top:1rpx solid #e8efec;flex-shrink:0}.primary-action{flex:1;min-width:260rpx;color:{{card}};background:{{brand}}}.ew-page .primary-action[disabled]{opacity:1;background:{{disabled}};color:{{text}}}
.quick-bar{display:flex;white-space:nowrap;background:{{card}};border-top:1rpx solid #eef3f1;padding:{{space.0.rpx*1.5}} {{space.2.rpx}};box-sizing:border-box;flex-shrink:0}.quick-btn{display:inline-block;margin-right:{{space.0.rpx*1.5}};padding:{{space.0.rpx*1.25}} {{space.1.rpx*1.125}};border-radius:{{radius.1.rpx*1.1}};background:#eef9f5;color:{{brand}};font-size:{{font.caption.em}};white-space:nowrap}.input-bar{display:flex;align-items:center;gap:{{space.0.rpx*1.5}};padding:{{space.0.rpx*1.5}} {{space.2.rpx}} calc({{space.0.rpx*1.5}} + env(safe-area-inset-bottom));background:{{card}};border-top:1rpx solid #e8efec;flex-shrink:0}.chat-input{flex:1;min-width:0;height:76rpx;padding:0 {{space.2.rpx*0.91666667}};border-radius:{{radius.3.rpx*1.0555556}};background:#f3f6f5;color:{{text}};font-size:{{font.body.em}};box-sizing:border-box}.send-btn{width:76rpx;height:76rpx;line-height:76rpx;padding:0;border-radius:50%;background:{{brand}};display:flex;align-items:center;justify-content:center;flex-shrink:0}.send-btn .line-icon{width:34rpx;height:34rpx;color:{{card}}}.send-btn[disabled]{opacity:1;background:{{disabled}};color:{{text}}}.typing-dots{display:flex;gap:{{space.0.rpx}};padding:{{space.1.rpx*0.875}} {{space.2.rpx*0.91666667}}}.dot{font-size:{{font.caption.em}};color:{{brand}};animation:blink 1.2s infinite}.dot:nth-child(2){animation-delay:.2s}.dot:nth-child(3){animation-delay:.4s}@keyframes blink{0%,100%{opacity:.85}50%{opacity:1}}.error-state{display:flex;align-items:center;gap:{{space.0.rpx*1.5}};padding:{{space.0.rpx*1.5}} {{space.1.rpx}};margin:0 {{space.0.rpx}} {{space.1.rpx}};background:#fff2f0;border-radius:{{radius.0.rpx*0.83333333}};color:{{danger}};font-size:{{font.caption.em}}}.error-state text{flex:1}.error-state button{margin:0;padding:0 {{space.1.rpx*1.125}};height:54rpx;line-height:54rpx;border-radius:{{radius.0.rpx*0.66666667}};color:{{danger}};background:{{card}};border:1rpx solid #edc6c0;font-size:{{font.caption.em}}}

/* 页面共享主题，适用于本页详情、表单和弹层。 */

.plan-dish { flex-wrap:wrap; }
.dish-commands { display:flex;gap:{{space.0.rpx*1.5}};width:100%; }
.clear-btn,.quick-btn,.stop-task { min-height:{{controls.touchSize.px}};min-width:{{controls.touchSize.px}};display:inline-flex;align-items:center;justify-content:center; }

/* Shared finish for legacy pages; layout and permission-specific states remain local. */
.ew-page { background:{{background}}; color:{{text}}; }
.ew-page .btn-primary, .ew-page .primary-btn, .ew-page .save-btn, .ew-page .primary-action, .ew-page .generate-btn { background:{{brand}}; border-radius:{{radius.1.rpx*1.2}}; }
.ew-page .choice-chip, .ew-page .ingredient-chip, .ew-page .count-btn, .ew-page .clear-btn, .ew-page .period-nav, .ew-page .filter-chip { min-height:{{controls.touchSize.px}}; min-width:{{controls.touchSize.px}}; box-sizing:border-box; }

@import "../../styles/workspace.wxss";

/* Input and touch minima remain fixed under small screens/font changes. */
.ew-page button,.ew-page input,.ew-page .count-btn,.ew-page .choice-chip,.ew-page .filter-chip,.ew-page .date-picker{min-height:{{controls.touchSize.px}};box-sizing:border-box}
.ew-page .primary-btn,.ew-page .save-btn,.ew-page .primary-action,.ew-page .wx-login-btn{min-height:{{controls.primaryHeight.px}}}

.send-btn { width:auto; min-width:64px; border-radius:{{radius.2.px}}; padding:0 {{space.2.px}}; color:{{card}}; }

/* Fixed CSS pixels protect the actual event node at the 320px baseline. */
.ew-hit-target, .ew-page .ew-hit-target { min-width:{{controls.touchSize.px}}; min-height:{{controls.touchSize.px}}; box-sizing:border-box; }
text.ew-hit-target { display:inline-flex; align-items:center; justify-content:center; }
picker.ew-hit-target { display:block; }
button { min-width:{{controls.touchSize.px}}; min-height:{{controls.primaryHeight.px}}; }


button.ew-hit-target, .ew-page button.ew-hit-target { min-height:{{controls.primaryHeight.px}}; }
