import { IDBFactory, IDBObjectStore } from 'fake-indexeddb';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { exportBackup, exportRawSnapshot, parseBackup, restoreBackup, scanJsonTextBoundary, type BackupContext, type RestoreCandidate } from '../src/backup/backup.ts';
import { openRepository, type Repository } from '../src/data/repository.ts';
import { BACKUP_ENVELOPE_RESERVED_BYTES, LIMITS, validatePersonalData } from '../src/domain/validation.ts';
import { buildShopping, sourceFromPlan } from '../src/shopping/shopping.ts';
import { snapshotRecipe } from '../src/domain/snapshots.ts';
import { draft, FIXED_NOW, personalData, recipe } from './fixtures.ts';
import type { PersonalData, Plan, TimeZone, UtcIso } from '../src/domain/types.ts';
const context:BackupContext={appVersion:'0.1.0',catalogVersion:null,exportedAt:FIXED_NOW.toISOString() as UtcIso,timeZone:'UTC' as TimeZone};
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const stamp=FIXED_NOW.toISOString() as UtcIso;
const identity=(n:number)=>({id:id(n),createdAt:stamp,updatedAt:stamp,revision:3,requestId:`record-${n}`});
const envelope=(data=personalData())=>({format:'eatwhat-web-backup',schemaVersion:1,...context,data});
const file=(value:unknown)=>new Blob([JSON.stringify(value)]);
const repos:Repository[]=[];
afterEach(()=>{repos.splice(0).forEach(r=>r.close());vi.restoreAllMocks();vi.unstubAllGlobals();});
async function setup(factory=new IDBFactory(),zone='UTC',now=FIXED_NOW){let sequence=1000;const r=await openRepository({factory,now:()=>now,uuid:()=>id(++sequence),currentTimeZone:()=>zone as TimeZone});if(!r.ok)throw new Error(r.error.message);repos.push(r.value);return {repo:r.value,factory};}
async function candidate(data=personalData()):Promise<RestoreCandidate>{const r=await parseBackup(file(envelope(data)));expect(r.ok).toBe(true);if(!r.ok)throw new Error(r.error.message);return r.value;}
async function read(repo:Repository){const r=await repo.read();if(!r.ok)throw new Error(r.error.message);return r.value;}
function fullData():PersonalData{
  const d=personalData(),snapshot=snapshotRecipe(recipe());d.draft=draft({dishes:[{slotId:'vegetable-1',recipe:snapshot,locked:true}]});
  const plan:Plan={...identity(1),date:'2026-10-09' as Plan['date'],meal:'dinner',servings:2,snapshots:[snapshot],timeZone:'Asia/Tokyo' as TimeZone};d.plans=[plan];
  d.actualMeals=[{...identity(2),date:plan.date,meal:plan.meal,snapshots:[snapshot],planId:plan.id,note:'<img src="file:///secret"> plain text',timeZone:plan.timeZone}];
  const custom={...identity(3),snapshot:{...snapshot,recipeId:id(3),familyId:id(3),ingredients:[],steps:[],source:{url:null,commit:null,license:null},catalogVersion:null,contentVersion:null}};d.customRecipes=[custom];
  d.favorites=[{...identity(4),recipeId:custom.id,snapshot:custom.snapshot}];d.menuTemplates=[{...identity(5),name:'历史组合',servings:2,snapshots:[custom.snapshot,snapshot]}];
  const list=buildShopping([sourceFromPlan(plan)]);d.shoppingLists=[{...identity(6),...list}];
  d.trash=[{id:id(7),store:'favorites',originalId:id(8),data:{...identity(8),recipeId:'deleted-source',snapshot:{...snapshot,recipeId:'deleted-source'}},deletedAt:stamp,expiresAt:'2026-11-08T00:00:00.000Z' as UtcIso,revision:2,requestId:'trash-7'}];return d;
}
describe('strict personal JSON backup',()=>{
  it.each([['empty',personalData()],['all stores and trash',fullData()]])('roundtrips %s exactly without catalog or operational journal',async(_name,data)=>{const exported=exportBackup(data,context);expect(exported.ok).toBe(true);if(!exported.ok)return;expect(exported.value.type).toBe('application/json;charset=utf-8');const parsed=await parseBackup(exported.value);expect(parsed).toMatchObject({ok:true,value:{data,context}});const json=JSON.parse(await exported.value.text());expect(Object.keys(json).sort()).toEqual(Object.keys(envelope()).sort());expect(json.data.meta).toEqual(data.meta);expect(json.data.catalog).toBeUndefined();});
  it('clones and freezes approved data and context instead of retaining mutable caller/file state',async()=>{const original=fullData(),blob=file(envelope(original));const parsed=await parseBackup(blob);expect(parsed.ok).toBe(true);if(!parsed.ok)return;original.actualMeals[0]!.note='changed';expect(parsed.value.data.actualMeals[0]!.note).toContain('plain text');expect(Object.isFrozen(parsed.value)).toBe(true);expect(Object.isFrozen(parsed.value.data.actualMeals[0])).toBe(true);expect(()=>{parsed.value.data.actualMeals[0]!.note='mutation';}).toThrow();});
  it('rejects a raw or newer version and unknown envelope/context fields',async()=>{for(const value of [{...envelope(),schemaVersion:2},{...envelope(),format:'eatwhat-web-raw-snapshot'},{...envelope(),media:[]},{...envelope(),catalogVersion:42},{...envelope(),timeZone:'bad-zone'},{...envelope(),exportedAt:'2026-02-30T00:00:00.000Z'}])expect(await parseBackup(file(value))).toMatchObject({ok:false});});
  it('rejects dangerous keys, duplicate keys, malformed JSON and nonfinite numeric notation',async()=>{for(const text of ['{"__proto__":{"polluted":true}}','{"constructor":{}}','{"prototype":{}}','{"format":1,"format":2}','{','{"x":1e999}'])expect(await parseBackup(new Blob([text]))).toMatchObject({ok:false});expect(({} as Record<string,unknown>).polluted).toBeUndefined();});
  it('keeps HTML-looking named text inert and makes zero URL requests while rejecting all media and non-https sources',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);const data=fullData();expect((await parseBackup(file(envelope(data)))).ok).toBe(true);for(const url of ['file:///etc/passwd','javascript:alert(1)','data:text/html,x','http://example.test','blob:https://example.test/a']){const invalid=fullData();invalid.plans[0]!.snapshots[0]!.source.url=url;expect(await parseBackup(file(envelope(invalid)))).toMatchObject({ok:false});}for(const key of ['html','image','video','audio','iframe','media','generationEligible','reviewStatus']){const invalid=fullData();Object.assign(invalid.plans[0]!.snapshots[0]!,{[key]:'https://example.test/a'});expect(await parseBackup(file(envelope(invalid)))).toMatchObject({ok:false});}data.plans[0]!.snapshots[0]!.source.url='https://example.test/recipe';expect((await parseBackup(file(envelope(data)))).ok).toBe(true);expect(fetch).not.toHaveBeenCalled();});
  it('rejects bad dates/meals, duplicate identities, broken required snapshot and slot references, and custom authority',async()=>{const mutations=[(d:PersonalData)=>{d.plans[0]!.date='2026-02-30' as Plan['date'];},(d:PersonalData)=>{d.plans[0]!.meal='midnight' as Plan['meal'];},(d:PersonalData)=>{d.plans.push(structuredClone(d.plans[0]!));},(d:PersonalData)=>{d.favorites[0]!.recipeId='wrong';},(d:PersonalData)=>{d.draft!.dishes[0]!.slotId='missing';},(d:PersonalData)=>{d.trash[0]!.originalId=id(99);},(d:PersonalData)=>{d.customRecipes[0]!.snapshot.ingredients=[{ingredientId:'trusted',form:'',part:null,raw:'x',quantity:null,trust:'reviewed',compoundResolved:true}];}];for(const mutate of mutations){const d=fullData();mutate(d);expect(await parseBackup(file(envelope(d)))).toMatchObject({ok:false});}});
  it('allows missing plan/custom/shopping tracing sources with warnings and preserves historical snapshots',async()=>{const d=fullData();d.plans=[];d.customRecipes=[];const parsed=await parseBackup(file(envelope(d)));expect(parsed).toMatchObject({ok:true,value:{data:d}});if(parsed.ok){expect(parsed.value.warnings.some(w=>w.includes('计划'))).toBe(true);expect(parsed.value.warnings.some(w=>w.includes('采购'))).toBe(true);expect(parsed.value.counts.trash).toBe(1);}});
  it.each([0,1_000_001,Infinity,NaN])('rejects ingredient quantity %s on export and parse',async amount=>{const d=fullData();d.plans[0]!.snapshots[0]!.ingredients[0]!.quantity={kind:'exact',value:amount,unit:'g'};expect(exportBackup(d,context)).toMatchObject({ok:false});expect(await parseBackup(file(envelope(d)))).toMatchObject({ok:false});});
  it('accepts 20,000 decoded characters and rejects 20,001 including escaped input',async()=>{const d=personalData();d.preferences.softPreferences=['x'.repeat(20_000)];expect((await parseBackup(file(envelope(d)))).ok).toBe(true);d.preferences.softPreferences=['x'.repeat(20_001)];expect(await parseBackup(file(envelope(d)))).toMatchObject({ok:false,error:{code:'LIMIT'}});expect(scanJsonTextBoundary('"'+ '\\u0061'.repeat(20_000)+'"').ok).toBe(true);expect(scanJsonTextBoundary('"'+ '\\u0061'.repeat(20_001)+'"')).toMatchObject({ok:false,error:{code:'LIMIT'}});});
  it('counts only JSON containers for the 20-layer boundary, ignoring brackets/escapes inside strings',()=>{expect(scanJsonTextBoundary('['.repeat(20)+'"[\\\"]"'+']'.repeat(20)).ok).toBe(true);expect(scanJsonTextBoundary('['.repeat(21)+'0'+']'.repeat(21))).toMatchObject({ok:false,error:{code:'LIMIT'}});});
  it('accepts exactly 20 MiB UTF-8 including whitespace and refuses +1 before reading',async()=>{const text=JSON.stringify(envelope()),padded=text+' '.repeat(LIMITS.bytes-new TextEncoder().encode(text).byteLength);expect((await parseBackup(new Blob([padded]))).ok).toBe(true);const oversized=new Blob([padded+' ']);const textSpy=vi.spyOn(oversized,'text');expect(await parseBackup(oversized)).toMatchObject({ok:false,error:{code:'LIMIT'}});expect(textSpy).not.toHaveBeenCalled();},30_000);
  it('accepts 20,000 domain records (preferences once, each trash wrapper once) and refuses +1 without truncation',async()=>{const d=personalData(),s=snapshotRecipe(recipe({ingredients:[],steps:[]}));d.favorites=Array.from({length:19_999},(_,n)=>({...identity(n+1),recipeId:`r-${n}`,snapshot:{...s,recipeId:`r-${n}`}}));const exported=exportBackup(d,context);expect(exported.ok).toBe(true);if(exported.ok)expect((await parseBackup(exported.value)).ok).toBe(true);d.favorites.push({...identity(20_000),recipeId:'extra',snapshot:{...s,recipeId:'extra'}});expect(exportBackup(d,context)).toMatchObject({ok:false,error:{code:'LIMIT'}});expect(await parseBackup(file(envelope(d)))).toMatchObject({ok:false,error:{code:'LIMIT'}});},30_000);
  it('uses an envelope-aware normal byte boundary so every accepted personal state exports and reparses',async()=>{const d=personalData();d.preferences.softPreferences=Array.from({length:1048},()=> 'x'.repeat(20_000));const before=JSON.stringify(d).length;d.preferences.softPreferences.push('x'.repeat(LIMITS.bytes-BACKUP_ENVELOPE_RESERVED_BYTES-before-3));expect(exportBackup(d,context).ok).toBe(true);d.preferences.softPreferences[d.preferences.softPreferences.length-1]+='x';expect(validatePersonalData(d)).toMatchObject({ok:false,error:{code:'LIMIT'}});expect(exportBackup(d,context)).toMatchObject({ok:false,error:{code:'LIMIT'}});});
});
describe('atomic restore generation',()=>{
  it('replaces all stores, unifies every object revision and advances only the existing global generation',async()=>{const {repo}=await setup();await repo.commit({type:'saveDraft',draft:draft()},0,'old');const incoming=fullData();incoming.meta.revision=900;const c=await candidate(incoming);const r=await restoreBackup(repo,c,1,'restore');expect(r).toMatchObject({ok:true,value:{globalRevision:2,objectId:null,objectRevision:null}});const d=await read(repo);expect(d.plans[0]!.revision).toBe(2);expect(d.draft!.revision).toBe(2);expect(d.preferences.revision).toBe(2);expect(d.trash[0]!.revision).toBe(2);expect(d.trash[0]!.data.revision).toBe(2);expect(d.shoppingLists[0]!.sources).toEqual(incoming.shoppingLists[0]!.sources);expect(d.meta.revision).toBe(2);const raw=await repo.readRawSnapshot();if(raw.ok){const meta=raw.value.stores.find(s=>s.name==='meta')!.entries;expect(meta.find(e=>e.key==='epoch')!.value).toBe(1);expect(meta.filter(e=>String(e.key).startsWith('request:'))).toHaveLength(1);expect(meta.find(e=>e.key==='request:old')).toBeUndefined();}expect(await repo.commit({type:'saveDraft',draft:draft()},0,'old')).toMatchObject({ok:false,error:{code:'CONFLICT'}});});
  it('preview revision and post-restore old forms conflict across repository instances',async()=>{const {repo,factory}=await setup();const {repo:second}=await setup(factory),c=await candidate(fullData());await second.commit({type:'saveDraft',draft:draft()},0,'foreign');const before=await repo.readRawSnapshot();expect(await restoreBackup(repo,c,0,'restore')).toMatchObject({ok:false,error:{code:'CONFLICT'}});expect(await repo.readRawSnapshot()).toEqual(before);expect((await restoreBackup(repo,c,1,'restore')).ok).toBe(true);expect(await second.commit({type:'saveDraft',draft:draft({servings:4})},1,'stale')).toMatchObject({ok:false,error:{code:'CONFLICT'}});});
  it('retains exact restore retries and replay cannot overwrite data written later',async()=>{const {repo}=await setup(),c=await candidate(fullData());expect((await restoreBackup(repo,c,0,'restore')).ok).toBe(true);await repo.commit({type:'saveDraft',draft:draft({servings:5})},1,'later');const before=await repo.readRawSnapshot();expect(await restoreBackup(repo,c,0,'restore')).toMatchObject({ok:true,value:{globalRevision:1,replayed:true}});expect(await repo.readRawSnapshot()).toEqual(before);expect((await read(repo)).draft!.servings).toBe(5);expect(await restoreBackup(repo,await candidate(),2,'restore')).toMatchObject({ok:false,error:{code:'CONFLICT'}});});
  it.each(['abort','quota'])('keeps every old store/epoch/journal after %s and the exact request can retry',async(mode)=>{const {repo}=await setup();await repo.commit({type:'saveDraft',draft:draft()},0,'old');const before=await repo.readRawSnapshot(),c=await candidate(fullData()),original=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,...args){if(this.name==='meta'){if(mode==='quota')throw new DOMException('full','QuotaExceededError');this.transaction.abort();}return original.apply(this,args);});expect(await restoreBackup(repo,c,1,'restore')).toMatchObject({ok:false,error:{code:mode==='quota'?'QUOTA':'ABORTED'}});expect(await repo.readRawSnapshot()).toEqual(before);vi.restoreAllMocks();expect((await restoreBackup(repo,c,1,'restore')).ok).toBe(true);});
  it('rejects future actuals in the current zone without changing historical creation timezones',async()=>{const {repo}=await setup(new IDBFactory(),'America/Los_Angeles',new Date('2026-10-09T00:30:00Z'));const c=await candidate(fullData()),before=await repo.readRawSnapshot();expect(await restoreBackup(repo,c,0,'restore')).toMatchObject({ok:false,error:{code:'FUTURE_DATE'}});expect(await repo.readRawSnapshot()).toEqual(before);});
  it('preserves all raw store names/keys/values including future stores and multiple meta entries in preservation-only format',async()=>{const {repo,factory}=await setup();repo.close();const request=factory.open('eatwhat-web',2);request.onupgradeneeded=()=>{request.result.createObjectStore('future').put({unknown:[null,'<b>text</b>']},'future-key');request.transaction!.objectStore('meta').put({future:true},'other-meta');};const db=await new Promise<IDBDatabase>(resolve=>{request.onsuccess=()=>resolve(request.result);});db.close();const {repo:newer}=await setup(factory);const raw=await newer.readRawSnapshot();expect(raw.ok).toBe(true);if(!raw.ok)return;const exported=await exportRawSnapshot(raw.value,{schemaVersion:2,appVersion:'0.1.0',exportedAt:stamp});expect(exported.ok).toBe(true);if(!exported.ok)return;const parsed=JSON.parse(await exported.value.text());expect(parsed.format).toBe('eatwhat-web-raw-snapshot');expect(parsed.snapshot.stores.map((s:{name:string})=>s.name)).toEqual(raw.value.stores.map(s=>s.name));expect(parsed.snapshot.stores.find((s:{name:string})=>s.name==='meta').entries.map((e:{key:unknown})=>e.key)).toContain('other-meta');expect(parsed.nodes.some((n:{kind:string;entries?:unknown[]})=>n.kind==='object'&&JSON.stringify(n.entries).includes('future'))).toBe(true);expect(await parseBackup(exported.value)).toMatchObject({ok:false});expect(newer.status().writable).toBe(false);});
});

describe('raw preservation graph and defensive boundary regressions',()=>{
  it('preserves compound keys, cycles/shared references, Date, binary views, Blob and non-JSON primitives',async()=>{
    const shared:{name:string;self?:unknown}={name:'保留'};shared.self=shared;
    const buffer=new Uint8Array([0,1,2,255]).buffer,view=new Uint8Array(buffer,1,2),key=['compound',new Date('2026-01-01T00:00:00.000Z'),buffer] as IDBValidKey;
    const value={left:shared,right:shared,date:new Date('2026-10-09T00:00:00.000Z'),buffer,view,blob:new Blob(['中文'],{type:'text/plain'}),undefined:undefined,big:42n,nan:NaN,minusZero:-0,map:new Map([[shared,shared]]),set:new Set([shared])};
    const raw={databaseName:'eatwhat-web',version:9,stores:[{name:'future',entries:[{key,value},{key:'second',value:shared}]}]};
    const result=await exportRawSnapshot(raw,{schemaVersion:9,appVersion:'0.1.0',exportedAt:stamp});expect(result.ok).toBe(true);if(!result.ok)return;
    const json=JSON.parse(await result.value.text());expect(json.restorable).toBe(false);expect(json.encoding).toBe('eatwhat-structured-clone-v1');
    const root=json.nodes[json.snapshot.stores[0].entries[0].value.ref],entries=Object.fromEntries(root.entries),left=entries.left.ref;
    expect(entries.right.ref).toBe(left);expect(json.snapshot.stores[0].entries[1].value.ref).toBe(left);expect(Object.fromEntries(json.nodes[left].entries).self).toEqual({ref:left});
    expect(json.nodes[entries.date.ref]).toEqual({kind:'date',value:'2026-10-09T00:00:00.000Z'});expect(json.nodes[entries.buffer.ref]).toEqual({kind:'buffer',bytes:[0,1,2,255]});
    expect(json.nodes[entries.view.ref]).toEqual({kind:'view',type:'Uint8Array',buffer:entries.buffer,byteOffset:1,byteLength:2});expect(json.nodes[entries.blob.ref]).toEqual({kind:'blob',type:'text/plain',bytes:Array.from(new TextEncoder().encode('中文'))});
    expect(entries.undefined).toEqual({tag:'undefined'});expect(entries.big).toEqual({tag:'bigint',value:'42'});expect(entries.nan).toEqual({tag:'number',value:'NaN'});expect(entries.minusZero).toEqual({tag:'number',value:'-0'});
    expect(json.nodes[entries.map.ref].entries).toEqual([[{ref:left},{ref:left}]]);expect(json.nodes[entries.set.ref].entries).toEqual([{ref:left}]);
    const compound=json.nodes[json.snapshot.stores[0].entries[0].key.ref];expect(compound.kind).toBe('array');expect(compound.entries[0]).toEqual(['0','compound']);expect(compound.entries[2]).toEqual(['2',entries.buffer]);
    expect((await parseBackup(result.value)).ok).toBe(false);
  });
  it('explicitly fails unsupported raw host objects and Blob read failures without delivering partial JSON',async()=>{
    const unsupported=await exportRawSnapshot({databaseName:'eatwhat-web',version:2,stores:[{name:'future',entries:[{key:'key',value:new URL('https://example.test')}]}]},{schemaVersion:2,appVersion:'0.1.0',exportedAt:stamp});expect(unsupported).toMatchObject({ok:false,error:{code:'UNAVAILABLE',message:expect.stringContaining('Unsupported stored host object')}});
    const blob=new Blob(['keep']);vi.spyOn(blob,'arrayBuffer').mockRejectedValue(new Error('read failed'));expect(await exportRawSnapshot({databaseName:'eatwhat-web',version:2,stores:[{name:'future',entries:[{key:'blob',value:blob}]}]},{schemaVersion:2,appVersion:'0.1.0',exportedAt:stamp})).toMatchObject({ok:false,error:{message:expect.stringContaining('read failed')}});
  });
  it('rejects malformed UTF-8 rather than silently replacing saved text',async()=>{const d=personalData();d.preferences.softPreferences=['BAD'];const bytes=new TextEncoder().encode(JSON.stringify(envelope(d)));const position=new TextDecoder().decode(bytes).indexOf('BAD');bytes[position]=0xff;expect(await parseBackup(new Blob([bytes]))).toMatchObject({ok:false});});
  it('bounds app/catalog/timezone context independently and accepts token maximums',async()=>{const d=personalData(),valid={...context,appVersion:'x'.repeat(128),catalogVersion:'x'.repeat(256)};const exported=exportBackup(d,valid);expect(exported.ok).toBe(true);if(exported.ok)expect((await parseBackup(exported.value)).ok).toBe(true);for(const ctx of [{...valid,appVersion:'x'.repeat(129)},{...valid,catalogVersion:'x'.repeat(257)},{...valid,appVersion:'<script>'}]){expect(exportBackup(d,ctx)).toMatchObject({ok:false});expect(await parseBackup(file({...envelope(d),...ctx}))).toMatchObject({ok:false});}});
  it('ordinary repository writes use the same envelope allowance and keep original data after +1 byte',async()=>{const {repo}=await setup();const d=personalData();d.preferences.softPreferences=Array.from({length:1048},()=> 'x'.repeat(20_000));const before=JSON.stringify(d).length;d.preferences.softPreferences.push('x'.repeat(LIMITS.bytes-BACKUP_ENVELOPE_RESERVED_BYTES-before-3));expect(validatePersonalData(d).ok).toBe(true);d.preferences.softPreferences[d.preferences.softPreferences.length-1]+='x';const original=await repo.readRawSnapshot();expect(await repo.commit({type:'savePreferences',preferences:d.preferences},0,'oversize')).toMatchObject({ok:false,error:{code:'LIMIT'}});expect(await repo.readRawSnapshot()).toEqual(original);});
});
it('roundtrips every typed trash payload and counts wrappers without double-counting their originals',async()=>{const d=fullData();d.trash=[];let n=20;for(const store of ['customRecipes','favorites','menuTemplates','plans','actualMeals','shoppingLists'] as const){const data=d[store][0]!;d.trash.push({id:id(n),store,originalId:data.id,data:structuredClone(data),deletedAt:stamp,expiresAt:'2026-11-08T00:00:00.000Z' as UtcIso,revision:1,requestId:`trash-${n++}`} as PersonalData['trash'][number]);}const result=exportBackup(d,context);expect(result.ok).toBe(true);if(!result.ok)return;const parsed=await parseBackup(result.value);expect(parsed).toMatchObject({ok:true,value:{data:d,counts:{trash:6,total:14}}});});

describe('persisted unsupported raw subtypes fail closed',()=>{
  type ResizableBuffer=ArrayBuffer&{readonly resizable:boolean;readonly maxByteLength:number;resize(length:number):void};
  const ResizableArrayBuffer=ArrayBuffer as unknown as {new(length:number,options:{maxByteLength:number}):ResizableBuffer};
  async function persisted(value:unknown){
    const {repo,factory}=await setup();repo.close();const request=factory.open('eatwhat-web',2);
    request.onupgradeneeded=()=>{const store=request.result.createObjectStore('future');store.put('ordinary value before unsupported row','a-safe');store.put(value,'subtype');};
    const db=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});db.close();
    const {repo:newer}=await setup(factory),raw=await newer.readRawSnapshot();expect(raw.ok).toBe(true);if(!raw.ok)throw new Error(raw.error.message);
    const stored=raw.value.stores.find(s=>s.name==='future')!.entries.find(e=>e.key==='subtype')!.value;
    return {repo:newer,raw:raw.value,stored};
  }
  it.each(['buffer','tracking-view','fixed-view','data-view'] as const)('rejects persisted resizable %s before delivering a partial raw export',async kind=>{
    const buffer=new ResizableArrayBuffer(4,{maxByteLength:8});new Uint8Array(buffer).set([1,2,3,4]);
    const input=kind==='buffer'?buffer:kind==='tracking-view'?new Uint8Array(buffer):kind==='fixed-view'?new Uint8Array(buffer,0,2):new DataView(buffer);
    const {repo,raw,stored}=await persisted(input);const savedBuffer=stored instanceof ArrayBuffer?stored:(stored as ArrayBufferView).buffer;
    expect((savedBuffer as ResizableBuffer).resizable).toBe(true);expect((savedBuffer as ResizableBuffer).maxByteLength).toBe(8);
    if(kind==='tracking-view'){(savedBuffer as ResizableBuffer).resize(6);expect((stored as Uint8Array).length).toBe(6);}
    const before=await repo.readRawSnapshot();expect(await exportRawSnapshot(raw,{schemaVersion:2,appVersion:'0.1.0',exportedAt:stamp})).toEqual({ok:false,error:{code:'UNAVAILABLE',message:expect.stringContaining('Unsupported resizable ArrayBuffer')}});expect(await repo.readRawSnapshot()).toEqual(before);
  });
  it('rejects persisted DOMException identity rather than presenting it as an ordinary Error',async()=>{
    const {repo,raw,stored}=await persisted(new DOMException('reason','AbortError'));expect(stored).toBeInstanceOf(DOMException);
    const before=await repo.readRawSnapshot();const result=await exportRawSnapshot(raw,{schemaVersion:2,appVersion:'0.1.0',exportedAt:stamp});expect(result).toEqual({ok:false,error:{code:'UNAVAILABLE',message:expect.stringContaining('Unsupported DOMException')}});expect(await repo.readRawSnapshot()).toEqual(before);
  });
  it('keeps persisted fixed buffers/views and ordinary Error details faithfully exportable',async()=>{
    const buffer=new Uint8Array([0,1,2,255]).buffer;const {raw,stored}=await persisted({buffer,view:new Uint8Array(buffer,1,2),error:new Error('ordinary',{cause:'cause text'})});
    expect((stored as {buffer:ResizableBuffer}).buffer.resizable).toBe(false);const result=await exportRawSnapshot(raw,{schemaVersion:2,appVersion:'0.1.0',exportedAt:stamp});expect(result.ok).toBe(true);if(!result.ok)return;
    const json=JSON.parse(await result.value.text()),future=json.snapshot.stores.find((s:{name:string})=>s.name==='future'),entries=Object.fromEntries(json.nodes[future.entries.find((e:{key:string})=>e.key==='subtype').value.ref].entries);
    expect(json.nodes[entries.buffer.ref]).toEqual({kind:'buffer',bytes:[0,1,2,255]});expect(json.nodes[entries.view.ref]).toEqual({kind:'view',type:'Uint8Array',buffer:entries.buffer,byteOffset:1,byteLength:2});expect(json.nodes[entries.error.ref]).toMatchObject({kind:'error',name:'Error',message:'ordinary',cause:'cause text'});
  });
});
