// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { Blob as NodeBlob, File as NodeFile } from 'node:buffer';
import { webcrypto } from 'node:crypto';
import { IDBFactory } from 'fake-indexeddb';
import { App } from '../src/ui/App.tsx';
import { openRepository, type Repository } from '../src/data/repository.ts';
import { personalData, draft } from './fixtures.ts';
import type { PersonalData } from '../src/domain/types.ts';
const unavailable=async()=>({ok:false as const,error:{code:'UNAVAILABLE' as const,message:'offline'}});
const status={readable:true,writable:true,origin:'https://backup.test',estimate:null,persisted:null,error:null};
const repos:Repository[]=[];
beforeEach(()=>{history.replaceState(null,'','/');vi.stubGlobal('crypto',webcrypto);vi.stubGlobal('Blob',NodeBlob);vi.stubGlobal('File',NodeFile);vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-10-09T12:00:00Z'));Object.defineProperty(URL,'createObjectURL',{configurable:true,value:vi.fn(()=> 'blob:https://backup.test/request')});Object.defineProperty(URL,'revokeObjectURL',{configurable:true,value:vi.fn()});vi.spyOn(HTMLAnchorElement.prototype,'click').mockImplementation(()=>{});});
afterEach(()=>{cleanup();repos.splice(0).forEach(r=>r.close());vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks();});
async function setup(factory=new IDBFactory()){const r=await openRepository({factory,now:()=>new Date(),uuid:()=>crypto.randomUUID()});if(!r.ok)throw new Error(r.error.message);repos.push(r.value);return {repo:r.value,factory};}
async function read(repo:Repository){const result=await repo.read();if(!result.ok)throw new Error(result.error.message);return result.value;}
async function show(repo:Repository|null,storage=status){render(<App repository={repo} catalogLoader={unavailable} storageStatus={storage}/>);await screen.findByRole('button',{name:'我的'});await waitFor(()=>expect(screen.queryByText('正在读取本地记录…')).toBeNull());fireEvent.click(screen.getByRole('button',{name:'我的'}));}
async function click(name:string){const button=await screen.findByRole('button',{name});await waitFor(()=>expect(button).toHaveProperty('disabled',false));fireEvent.click(button);}
function json(data=personalData()){return JSON.stringify({format:'eatwhat-web-backup',schemaVersion:1,appVersion:'0.1.0',catalogVersion:null,exportedAt:'2026-10-09T00:00:00.000Z',timeZone:'UTC',data});}
async function select(data=personalData()){fireEvent.change(screen.getByLabelText('选择 JSON 备份'),{target:{files:[new NodeFile([json(data)],'backup.json',{type:'application/json'})]}});await screen.findByText('备份已验证，尚未替换任何数据。');}
function accept(){fireEvent.click(screen.getByLabelText('我已保存旧库备份，或接受覆盖且无法撤回'));}
describe('backup user decisions',()=>{
  it('shows privacy and truthful unknown storage data, only requests downloads and never persistence on startup',async()=>{const {repo}=await setup();const persist=vi.fn(async()=>false);Object.defineProperty(navigator,'storage',{configurable:true,value:{persist}});await show(repo);expect(screen.getByText(/备份包含饮食记录和忌口/)).not.toBeNull();expect(persist).not.toHaveBeenCalled();await click('导出已保存个人备份');await screen.findByText('已请求下载个人备份。请自行确认文件已保存。');expect((await read(repo)).meta.lastBackupRequestedAt).toBe('2026-10-09T12:00:00.000Z');expect(screen.getByText('估算占用：未知 · 配额：未知 字节')).not.toBeNull();await click('请求持久化存储');await screen.findByText(/持久化许可：未获得/);expect(persist).toHaveBeenCalledOnce();expect(screen.getByRole('button',{name:'导出已保存个人备份'})).toHaveProperty('disabled',false);});
  it('validates and previews replacement time/counts, cancel writes nothing, confirmation adopts imported draft',async()=>{const {repo}=await setup();await repo.commit({type:'saveDraft',draft:draft({servings:3})},0,'old');await show(repo);const incoming=personalData();incoming.draft=draft({servings:5});incoming.preferences.servings=5;const before=await repo.readRawSnapshot();await select(incoming);expect(screen.getByText(/2026-10-09T00:00:00.000Z/)).not.toBeNull();expect(screen.getByRole('button',{name:'确认替换全部个人数据'})).toHaveProperty('disabled',true);await click('取消备份恢复');expect(await repo.readRawSnapshot()).toEqual(before);await select(incoming);accept();await click('确认替换全部个人数据');await screen.findByText('个人备份已恢复。');expect((await read(repo)).draft!.servings).toBe(5);fireEvent.click(screen.getByRole('button',{name:'今天吃什么'}));expect(screen.getByLabelText('用餐人数')).toHaveProperty('value','5');});
  it('retains validated input/request after quota failure and disables competing controls while pending',async()=>{const {repo}=await setup();const original=repo.commit.bind(repo);let calls=0,firstId='',resolve!:(r:Awaited<ReturnType<Repository['commit']>>)=>void;vi.spyOn(repo,'commit').mockImplementation((command,revision,id)=>{if(command.type!=='replaceAll')return original(command,revision,id);if(++calls===1){firstId=id;return Promise.resolve({ok:false,error:{code:'QUOTA',message:'full'}});}expect(id).toBe(firstId);return new Promise(r=>{resolve=r;});});await show(repo);await select();accept();await click('确认替换全部个人数据');await screen.findByText(/存储空间不足/);expect(screen.getByRole('heading',{name:'恢复预览'})).not.toBeNull();await click('确认替换全部个人数据');expect(screen.getByLabelText('选择 JSON 备份')).toHaveProperty('disabled',true);expect(screen.getByRole('button',{name:'导出已保存个人备份'})).toHaveProperty('disabled',true);resolve(await original({type:'replaceAll',data:personalData()},0,firstId));await screen.findByText('个人备份已恢复。');});
  it('foreign preview write conflicts, viewing/repreviewing the frozen candidate is explicit and never rereads its file',async()=>{const {repo,factory}=await setup(),{repo:foreign}=await setup(factory);await show(repo);await select();await foreign.commit({type:'saveDraft',draft:draft()},0,'foreign');const before=await repo.readRawSnapshot();accept();await click('确认替换全部个人数据');await screen.findByText('预览后数据有更新，未覆盖。请重新预览这份已验证备份并重新确认。');expect(await repo.readRawSnapshot()).toEqual(before);await click('重新预览已验证备份');await screen.findByText('本地预览版本：1');await waitFor(()=>expect(screen.getByLabelText('我已保存旧库备份，或接受覆盖且无法撤回')).toHaveProperty('disabled',false));expect(screen.getByRole('button',{name:'确认替换全部个人数据'})).toHaveProperty('disabled',true);accept();await click('确认替换全部个人数据');await screen.findByText('个人备份已恢复。');expect((await read(repo)).draft).toBeNull();});
  it('invalid files leave every store untouched and do not retain a previous accepted preview',async()=>{const {repo}=await setup();await show(repo);await select();accept();const before=await repo.readRawSnapshot();fireEvent.change(screen.getByLabelText('选择 JSON 备份'),{target:{files:[new NodeFile(['{"__proto__":{}}'],'invalid.json')]}});await screen.findByText(/Dangerous object key/);expect(screen.queryByRole('button',{name:'确认替换全部个人数据'})).toBeNull();expect(await repo.readRawSnapshot()).toEqual(before);});
  it('exports available unsaved memory if storage is unavailable without pretending it was persisted',async()=>{await show(null,{...status,readable:false,writable:false});fireEvent.click(screen.getByRole('button',{name:'今天吃什么'}));fireEvent.change(screen.getByLabelText('用餐人数'),{target:{value:'4'}});fireEvent.click(screen.getByRole('button',{name:'我的'}));await click('导出当前内存备份');await screen.findByText('已请求下载当前内存备份，含未保存编辑。请自行确认文件已保存。');const blob=(URL.createObjectURL as ReturnType<typeof vi.fn>).mock.calls[0]![0] as Blob;const exported=JSON.parse(await blob.text());expect(exported.data.preferences.servings).toBe(4);expect(exported.data.draft.servings).toBe(4);expect(screen.getByLabelText('选择 JSON 备份')).toHaveProperty('disabled',true);});
  it('offers lossless raw preservation for a newer read-only database without normal restore authority',async()=>{const {repo,factory}=await setup();repo.close();const request=factory.open('eatwhat-web',2);request.onupgradeneeded=()=>request.result.createObjectStore('future').put('keep','key');const db=await new Promise<IDBDatabase>(resolve=>{request.onsuccess=()=>resolve(request.result);});db.close();const {repo:newer}=await setup(factory);await show(newer);await click('导出原始保留文件');await screen.findByText('已请求下载原始保留文件。此格式仅供留存，本版不能恢复。');expect(screen.getByLabelText('选择 JSON 备份')).toHaveProperty('disabled',true);});
  it('download metadata preserves dirty editor baselines and the exact failed draft retry',async()=>{const {repo}=await setup();const original=repo.commit.bind(repo);let draftId='',attempts=0;vi.spyOn(repo,'commit').mockImplementation((command,revision,id)=>{if(command.type==='saveSettings'){if(++attempts===1){draftId=id;return Promise.resolve({ok:false,error:{code:'QUOTA',message:'full'}});}expect(id).toBe(draftId);expect(revision).toBe(0);}return original(command,revision,id);});await show(repo);fireEvent.click(screen.getByRole('button',{name:'今天吃什么'}));fireEvent.change(screen.getByLabelText('用餐人数'),{target:{value:'4'}});await screen.findByText(/存储空间不足/);fireEvent.click(screen.getByRole('button',{name:'我的'}));await click('新建自定义菜谱');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'保留表单'}});await click('导出已保存个人备份');await screen.findByText('已请求下载个人备份。请自行确认文件已保存。');expect(screen.getByLabelText('自定义菜名')).toHaveProperty('value','保留表单');await click('重试保存当前编辑');await screen.findByText('另一个页面已修改，请查看最新内容后重试。你的输入已保留。');expect((await read(repo)).preferences.servings).toBe(2);expect(attempts).toBe(2);});
});

it('exporting old data blocks confirmation until explicit re-preview and resets the checkbox after a foreign write',async()=>{const {repo,factory}=await setup(),{repo:foreign}=await setup(factory);await show(repo);await select();accept();await click('导出恢复前旧库备份');await screen.findByText('下载请求时间已记录；这不证明文件已保存。');expect(screen.getByRole('button',{name:'确认替换全部个人数据'})).toHaveProperty('disabled',true);expect(screen.getByLabelText('我已保存旧库备份，或接受覆盖且无法撤回')).toHaveProperty('checked',false);await foreign.commit({type:'saveDraft',draft:draft()},1,'after-export');await click('重新预览已验证备份');await screen.findByText('本地预览版本：2');expect(screen.getByText('当前草稿：当前 1 → 备份 0')).not.toBeNull();expect(screen.getByLabelText('我已保存旧库备份，或接受覆盖且无法撤回')).toHaveProperty('checked',false);accept();await click('确认替换全部个人数据');await screen.findByText('个人备份已恢复。');});
it('a failed metadata write preserves successful requested-download status and its exact metadata retry',async()=>{const {repo}=await setup();const original=repo.commit.bind(repo);let metadataCalls=0,firstId='',firstCommand:unknown;vi.spyOn(repo,'commit').mockImplementation((command,revision,id)=>{if(command.type==='markBackupRequested'){if(++metadataCalls===1){firstId=id;firstCommand=structuredClone(command);return Promise.resolve({ok:false,error:{code:'QUOTA',message:'full'}});}expect(id).toBe(firstId);expect(command).toEqual(firstCommand);}return original(command,revision,id);});await show(repo);await click('导出已保存个人备份');await screen.findByText('已请求下载个人备份。请自行确认文件已保存。');await screen.findByText(/已请求下载，但下载时间未写入本地记录/);expect((await read(repo)).meta.lastBackupRequestedAt).toBeNull();expect(URL.createObjectURL).toHaveBeenCalledOnce();await click('重试记录下载时间');await screen.findByText('下载请求时间已记录；这不证明文件已保存。');expect(URL.createObjectURL).toHaveBeenCalledOnce();expect((await read(repo)).meta.lastBackupRequestedAt).not.toBeNull();});
it('never records a download timestamp if requesting the browser download fails',async()=>{const {repo}=await setup();await show(repo);const before=await repo.readRawSnapshot();(URL.createObjectURL as ReturnType<typeof vi.fn>).mockImplementation(()=>{throw new Error('denied');});await click('导出已保存个人备份');await screen.findByText('无法请求下载。请保留数据并重试。');expect(await repo.readRawSnapshot()).toEqual(before);});
it('renders imported HTML-looking recipe names as text without creating media elements or network requests',async()=>{const {repo}=await setup();await show(repo);const d=personalData(),id='00000000-0000-4000-8000-000000000077',name='<img src="file:///private">';d.customRecipes=[{id,createdAt:'2026-10-09T00:00:00.000Z' as never,updatedAt:'2026-10-09T00:00:00.000Z' as never,revision:1,requestId:'custom',snapshot:{recipeId:id,familyId:id,variantId:null,name,types:[],ingredients:[],steps:[],source:{url:null,commit:null,license:null},baseServings:null,catalogVersion:null,contentVersion:null}}];const fetch=vi.fn();vi.stubGlobal('fetch',fetch);await select(d);accept();await click('确认替换全部个人数据');await screen.findByText('个人备份已恢复。');expect(screen.getByText(name)).not.toBeNull();expect(document.querySelectorAll('img,video,audio,iframe')).toHaveLength(0);expect(fetch).not.toHaveBeenCalled();});
it('exact replay of an uncertain completed restore keeps later data and an explicitly adopted newer draft',async()=>{const {repo}=await setup();const original=repo.commit.bind(repo);let attempts=0;vi.spyOn(repo,'commit').mockImplementation(async(command,revision,id)=>{const result=await original(command,revision,id);if(command.type==='replaceAll'&&++attempts===1)return {ok:false,error:{code:'UNAVAILABLE',message:'completion uncertain'}};return result;});await show(repo);await select();accept();await click('确认替换全部个人数据');await screen.findByText('本地保存未完成，输入已保留。请重试。');await original({type:'saveDraft',draft:draft({servings:6})},1,'later-draft');await click('查看最新内容');await click('采用最新草稿');await click('确认替换全部个人数据');await screen.findByText('这次恢复请求已执行，之后新增的内容仍保留。');expect((await read(repo)).draft!.servings).toBe(6);fireEvent.click(screen.getByRole('button',{name:'今天吃什么'}));expect(screen.getByLabelText('用餐人数')).toHaveProperty('value','6');});

it('shows unknown history for unreadable newer-schema metadata even when its raw meta contains real timestamps',async()=>{const {repo,factory}=await setup();expect((await repo.commit({type:'markBackupRequested',requestedAt:'2026-10-09T11:00:00.000Z' as never},0,'download-before-upgrade')).ok).toBe(true);repo.close();const request=factory.open('eatwhat-web',2);request.onupgradeneeded=()=>request.result.createObjectStore('future');const db=await new Promise<IDBDatabase>(resolve=>{request.onsuccess=()=>resolve(request.result);});db.close();const {repo:newer}=await setup(factory);const raw=await newer.readRawSnapshot();if(!raw.ok)throw new Error(raw.error.message);expect(raw.value.stores.find(s=>s.name==='meta')!.entries.find(e=>e.key==='current')!.value).toMatchObject({lastSuccessfulWriteAt:'2026-10-09T12:00:00.000Z',lastBackupRequestedAt:'2026-10-09T11:00:00.000Z'});await show(newer);expect(screen.getByText('最后成功写入：未知')).not.toBeNull();expect(screen.getByText('最近请求下载备份：未知')).not.toBeNull();expect(screen.queryByText('最后成功写入：尚未写入')).toBeNull();expect(screen.queryByText('最近请求下载备份：尚未请求')).toBeNull();});
it('keeps real empty-history labels after successfully reading an empty valid v1 database',async()=>{const {repo}=await setup();await show(repo);expect(screen.getByText('最后成功写入：尚未写入')).not.toBeNull();expect(screen.getByText('最近请求下载备份：尚未请求')).not.toBeNull();});
it('retains known prior memory timestamps when a later repository read becomes unavailable',async()=>{const {repo}=await setup();await repo.commit({type:'markBackupRequested',requestedAt:'2026-10-09T11:00:00.000Z' as never},0,'known');await show(repo);expect(screen.getByText('最后成功写入：2026-10-09T12:00:00.000Z')).not.toBeNull();expect(screen.getByText('最近请求下载备份：2026-10-09T11:00:00.000Z')).not.toBeNull();vi.spyOn(repo,'read').mockResolvedValue({ok:false,error:{code:'UNAVAILABLE',message:'read failed'}});await click('导出已保存个人备份');await screen.findByText(/个人结构无法读取/);expect(screen.getByText('最后成功写入：2026-10-09T12:00:00.000Z')).not.toBeNull();expect(screen.getByText('最近请求下载备份：2026-10-09T11:00:00.000Z')).not.toBeNull();});
it('never requests a partial raw file for a persisted DOMException in a future store',async()=>{let NativeException=DOMException;try{structuredClone(()=>{});}catch(error){NativeException=(error as Error).constructor as typeof DOMException;}const {repo,factory}=await setup();repo.close();const request=factory.open('eatwhat-web',2);request.onupgradeneeded=()=>{const store=request.result.createObjectStore('future');store.put('safe first','a-safe');store.put(new NativeException('reason','AbortError'),'unsupported');};const db=await new Promise<IDBDatabase>(resolve=>{request.onsuccess=()=>resolve(request.result);});db.close();const {repo:newer}=await setup(factory);await show(newer);await click('导出原始保留文件');await screen.findByText(/Unsupported DOMException/);expect(URL.createObjectURL).not.toHaveBeenCalled();expect(screen.queryByText('已请求下载原始保留文件。此格式仅供留存，本版不能恢复。')).toBeNull();});
