// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { IDBFactory } from 'fake-indexeddb';
import { webcrypto } from 'node:crypto';
import { App } from '../src/ui/App.tsx';
import { openRepository, type Repository } from '../src/data/repository.ts';
import { snapshotRecipe } from '../src/domain/snapshots.ts';
import type { Catalog, LocalDate, TimeZone } from '../src/domain/types.ts';
import { draft, personalData, recipe } from './fixtures.ts';
const status={readable:true,writable:true,origin:'https://test.invalid',estimate:null,persisted:null,error:null};
const unavailable=async()=>({ok:false as const,error:{code:'UNAVAILABLE' as const,message:'API disabled'}});
const catalog={origin:'online-provider',version:null,recipes:[recipe()],aliases:{},recipeAliases:{},availability:{}} as Catalog;
const repos:Repository[]=[];
beforeEach(()=>{history.replaceState(null,'','/');vi.stubGlobal('crypto',webcrypto);vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-10-09T12:00:00Z'));});
afterEach(()=>{cleanup();repos.splice(0).forEach(r=>r.close());vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks();});
async function setup(){let seq=0;const factory=new IDBFactory();const r=await openRepository({factory,now:()=>new Date(),uuid:()=>`00000000-0000-4000-8000-${String(++seq).padStart(12,'0')}`});if(!r.ok)throw new Error(r.error.message);repos.push(r.value);return {repo:r.value,factory};}
async function data(repo:Repository){const r=await repo.read();if(!r.ok)throw new Error(r.error.message);return r.value;}
async function seedPlan(repo:Repository){await repo.commit({type:'savePlan',plan:{date:'2026-10-09' as LocalDate,meal:'dinner',servings:2,snapshots:[snapshotRecipe(recipe())],timeZone:'UTC' as TimeZone},expectedObjectRevision:null},0,'plan');}
function app(repo:Repository,loader=unavailable){return render(<App repository={repo} catalogLoader={loader} storageStatus={status}/>);}
async function tab(name:string){fireEvent.click(await screen.findByRole('button',{name}));}
async function click(name:string){const button=await screen.findByRole('button',{name});await waitFor(()=>expect(button).toHaveProperty('disabled',false));fireEvent.click(button);}

describe('calendar and actual user paths',()=>{
  it('shows four meals, explicit plan/actual empty states, a week list and month day choice while API is unavailable',async()=>{const {repo}=await setup();app(repo);await tab('日历');expect(await screen.findByText('本周')).not.toBeNull();for(const meal of ['早餐','午餐','晚餐','加餐'])expect(screen.getByRole('heading',{name:meal})).not.toBeNull();expect(screen.getAllByText('暂无计划')).toHaveLength(4);expect(screen.getAllByText('未记录实际饮食')).toHaveLength(4);await click('月选日');fireEvent.change(screen.getByLabelText('选择月份'),{target:{value:'2026-11'}});await click('选择 2026-11-03');expect(screen.getByLabelText('查看日期')).toHaveProperty('value','2026-11-03');});
  it('records selected plan dishes separately, supports cancellation and opens duplicate actuals before explicit additional creation',async()=>{const {repo}=await setup();await seedPlan(repo);app(repo);await tab('日历');await click('按此记录饮食 测试青菜');expect(screen.getByLabelText('实际日期')).toHaveProperty('value','2026-10-09');await click('取消记录');expect((await data(repo)).actualMeals).toEqual([]);await click('按此记录饮食 测试青菜');fireEvent.change(screen.getByLabelText('实际备注'),{target:{value:'确实吃过'}});await click('确认记录实际');await screen.findByText('实际记录已保存');let d=await data(repo);expect(d.plans).toHaveLength(1);expect(d.actualMeals).toHaveLength(1);expect(d.actualMeals[0]!.note).toBe('确实吃过');await click('按此记录饮食 测试青菜');expect(screen.getByText('此计划已有实际记录')).not.toBeNull();await click('打开现有实际记录');expect(screen.getByLabelText('实际备注')).toHaveProperty('value','确实吃过');await click('取消记录');await click('按此记录饮食 测试青菜');await click('明确新增一条实际记录');await click('确认记录实际');await waitFor(async()=>expect((await data(repo)).actualMeals).toHaveLength(2));});
  it('lets users remove or manually add dishes before actual confirmation and refuses future actual dates',async()=>{const {repo}=await setup();await seedPlan(repo);app(repo,async()=>({ok:true,value:catalog}) as never);await tab('日历');await click('按此记录饮食 测试青菜');await click('移出实际 测试青菜');expect(screen.getByRole('button',{name:'确认记录实际'})).toHaveProperty('disabled',true);await click('加入实际 测试青菜');fireEvent.change(screen.getByLabelText('实际日期'),{target:{value:'2026-10-10'}});await click('确认记录实际');expect(await screen.findByText('未来日期只能保存计划')).not.toBeNull();expect((await data(repo)).actualMeals).toEqual([]);});
  it('edits plans without altering existing actual snapshots and confirms replacement of a date/meal plan',async()=>{const {repo}=await setup();await seedPlan(repo);app(repo,async()=>({ok:true,value:catalog}) as never);await tab('日历');await click('按此记录饮食 测试青菜');await click('确认记录实际');await screen.findByText('实际记录已保存');await click('编辑计划 测试青菜');fireEvent.change(screen.getByLabelText('计划人数'),{target:{value:'4'}});await click('保存计划编辑');await screen.findByText('计划编辑已保存');expect((await data(repo)).plans[0]!.servings).toBe(4);expect((await data(repo)).actualMeals[0]!.snapshots[0]!.name).toBe('测试青菜');});
  it('delete source plan preserves actual history with deleted-source label and restores from trash',async()=>{const {repo}=await setup();await seedPlan(repo);app(repo);await tab('日历');await click('按此记录饮食 测试青菜');await click('确认记录实际');await screen.findByText('实际记录已保存');await click('删除计划 测试青菜');await click('取消删除');expect((await data(repo)).plans).toHaveLength(1);await click('删除计划 测试青菜');await click('确认移入回收站');await screen.findByText('已移入回收站，保留 30 天');expect(await screen.findByText('来源计划已删除')).not.toBeNull();await tab('我的');await click('恢复 测试青菜');await click('确认恢复');await screen.findByText('已恢复');expect((await data(repo)).plans).toHaveLength(1);expect((await data(repo)).actualMeals).toHaveLength(1);});
});
describe('local personal objects when online recipes are unavailable',()=>{
  it('creates and edits a manual-only custom recipe, uses it in draft, favorites it and saves a template without creating actual history',async()=>{const {repo}=await setup();app(repo);await tab('我的');await click('新建自定义菜谱');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'我的空白菜'}});await click('保存自定义菜谱');await screen.findByText('自定义菜谱已保存');expect(screen.getByText('仅供手选，食材信息未经审核')).not.toBeNull();await click('收藏 我的空白菜');await click('确认收藏');await screen.findByText('已收藏');await click('手选 我的空白菜');await screen.findByText('草稿已保存');await tab('今天吃什么');await click('保存为菜单模板');fireEvent.change(screen.getByLabelText('模板名称'),{target:{value:'工作日晚餐'}});await click('确认保存模板');await screen.findByText('菜单模板已保存');await tab('我的');await click('编辑自定义 我的空白菜');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'改名以后'}});await click('保存自定义菜谱');await screen.findByText('自定义菜谱已保存');const d=await data(repo);expect(d.customRecipes[0]!.snapshot.name).toBe('改名以后');expect(d.menuTemplates[0]!.snapshots[0]!.name).toBe('我的空白菜');expect(d.favorites[0]!.snapshot.name).toBe('我的空白菜');expect(d.actualMeals).toEqual([]);await click('使用模板 工作日晚餐');await screen.findByText('模板已载入草稿');});
  it('retains favorite snapshot after catalog removal and cancels unfavorite without any writes',async()=>{const {repo}=await setup();await repo.commit({type:'saveFavorite',snapshot:snapshotRecipe(recipe())},0,'favorite');app(repo);await tab('我的');expect(await screen.findByText('当前菜库已不收录或尚未读取')).not.toBeNull();expect(screen.getByText('测试青菜')).not.toBeNull();await click('取消收藏 测试青菜');await click('取消删除');expect((await data(repo)).favorites).toHaveLength(1);await click('取消收藏 测试青菜');await click('确认移入回收站');await screen.findByText('已移入回收站，保留 30 天');expect((await data(repo)).favorites).toEqual([]);});
  it('shows actual-only 7/30 recap and labels unrecorded dates and overlapping classifications without health claims',async()=>{const {repo}=await setup();await seedPlan(repo);app(repo);await tab('我的');expect(await screen.findByText('2026-10-09 · 未记录')).not.toBeNull();expect(screen.getByText('分类标签可重叠，只描述记录中的菜品，不代表营养比例。')).not.toBeNull();await click('最近 30 天');expect(screen.getByText('2026-09-10 · 未记录')).not.toBeNull();expect(screen.getByText('没有实际记录，计划不计入回顾。')).not.toBeNull();});
  it('clearAll has two explicit confirmation stages, export reminder, and cancellation at either stage causes zero writes',async()=>{const {repo}=await setup();await seedPlan(repo);app(repo);await tab('我的');const before=await repo.read();await click('清空本应用全部数据');expect(screen.getByText(/请先在数据管理导出备份/)).not.toBeNull();await click('取消清空');expect(await repo.read()).toEqual(before);await click('清空本应用全部数据');await click('我已了解影响，继续');await click('取消清空');expect(await repo.read()).toEqual(before);await click('清空本应用全部数据');await click('我已了解影响，继续');await click('最终确认清空本应用');await screen.findByText('本应用个人数据已清空');expect((await data(repo)).plans).toEqual([]);expect((await data(repo)).meta.revision).toBe(2);});
  it('records draft directly as actual without implicitly adding a plan and offers first-write backup reminder',async()=>{const {repo}=await setup();app(repo,async()=>({ok:true,value:catalog}) as never);await tab('菜谱');await click('手选 测试青菜');await screen.findByText('草稿已保存');await tab('今天吃什么');await click('记录本餐实际饮食');await click('确认记录实际');await screen.findByText('实际记录已保存');expect((await data(repo)).plans).toEqual([]);expect((await data(repo)).actualMeals).toHaveLength(1);expect(screen.getByText(/建议在“我的 → 数据管理”导出备份/)).not.toBeNull();});
});

describe('preserved form baselines and request recovery',()=>{
  it('requires explicit plan replacement or cancellation instead of silently replacing an existing date/meal',async()=>{const {repo}=await setup();await seedPlan(repo);app(repo,async()=>({ok:true,value:catalog}) as never);await tab('菜谱');await click('手选 测试青菜');await screen.findByText('草稿已保存');await tab('今天吃什么');await click('保存到日历');await click('保存计划');expect(await screen.findByRole('button',{name:'确认替换已有计划'})).not.toBeNull();const before=await repo.read();await click('取消替换计划');expect(await repo.read()).toEqual(before);await click('保存到日历');await click('保存计划');await click('确认替换已有计划');await screen.findByText('计划已保存');expect((await data(repo)).plans).toHaveLength(1);expect((await data(repo)).plans[0]!.revision).toBe(2);});
  it('restore conflict offers another plan date/meal, or cancellation with no write',async()=>{const {repo}=await setup();await seedPlan(repo);let d=await data(repo);await repo.commit({type:'deleteObject',store:'plans',id:d.plans[0]!.id,expectedObjectRevision:1},1,'delete');await repo.commit({type:'savePlan',plan:{date:'2026-10-09' as LocalDate,meal:'dinner',servings:2,snapshots:[snapshotRecipe(recipe({name:'另一个计划'}))],timeZone:'UTC' as TimeZone},expectedObjectRevision:null},2,'other-plan');app(repo);await tab('我的');await click('恢复 测试青菜');expect(screen.getByText('恢复遇到唯一键冲突，不会覆盖已有对象。')).not.toBeNull();expect(screen.getByRole('button',{name:'确认恢复'})).toHaveProperty('disabled',true);const before=await repo.read();await click('取消恢复');expect(await repo.read()).toEqual(before);await click('恢复 测试青菜');fireEvent.click(screen.getByLabelText('另选计划日期和餐次'));fireEvent.change(screen.getByLabelText('恢复计划日期'),{target:{value:'2026-10-10'}});await click('确认恢复');await screen.findByText('已恢复');d=await data(repo);expect(d.plans).toHaveLength(2);expect(d.trash).toEqual([]);});
  it('keeps actual notes and the exact request UUID after quota failure, and disables controls during retry',async()=>{const {repo}=await setup();await seedPlan(repo);const original=repo.commit.bind(repo);let firstId='';let firstCommand:unknown;let resolve!:(r:Awaited<ReturnType<Repository['commit']>>)=>void;let calls=0;vi.spyOn(repo,'commit').mockImplementation((command,rev,id)=>{if(command.type!=='saveActual')return original(command,rev,id);calls++;if(calls===1){firstId=id;firstCommand=structuredClone(command);return Promise.resolve({ok:false,error:{code:'QUOTA',message:'full'}});}expect(id).toBe(firstId);expect(command).toEqual(firstCommand);return new Promise(r=>{resolve=r;});});app(repo);await tab('日历');await click('按此记录饮食 测试青菜');fireEvent.change(screen.getByLabelText('实际备注'),{target:{value:'保留这段输入'}});await click('确认记录实际');await screen.findByText(/存储空间不足/);expect(screen.getByLabelText('实际备注')).toHaveProperty('value','保留这段输入');await click('确认记录实际');expect(screen.getByLabelText('实际备注')).toHaveProperty('disabled',true);expect(screen.getByRole('button',{name:'确认记录实际'})).toHaveProperty('disabled',true);resolve(await original(firstCommand as Parameters<Repository['commit']>[0],1,firstId));await screen.findByText('实际记录已保存');expect((await data(repo)).actualMeals).toHaveLength(1);});
  it('foreign writes do not silently rebase a custom form, and viewing latest alone is read-only',async()=>{const {repo}=await setup();app(repo);await tab('我的');await click('新建自定义菜谱');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'保留的菜名'}});await repo.commit({type:'saveFavorite',snapshot:snapshotRecipe(recipe())},0,'foreign-write');await click('保存自定义菜谱');expect(await screen.findByText('另一个页面有更新，输入已保留。')).not.toBeNull();expect(screen.getByLabelText('自定义菜名')).toHaveProperty('value','保留的菜名');await click('查看此表单的最新记录');expect(await screen.findByText('已读取最新记录，当前表单输入未改变。')).not.toBeNull();const before=await repo.read();await click('保存自定义菜谱');expect(await repo.read()).toEqual(before);await click('保留此表单编辑并继续');await click('保存自定义菜谱');await screen.findByText('自定义菜谱已保存');expect((await data(repo)).customRecipes[0]!.snapshot.name).toBe('保留的菜名');});
  it('an independent successful custom save preserves the exact failed draft recovery command',async()=>{const {repo}=await setup();const original=repo.commit.bind(repo);let failedId='';let draftCalls=0;vi.spyOn(repo,'commit').mockImplementation((command,rev,id)=>{if(command.type==='saveDraft'){draftCalls++;if(draftCalls===1){failedId=id;return Promise.resolve({ok:false,error:{code:'QUOTA',message:'full'}});}expect(id).toBe(failedId);}return original(command,rev,id);});app(repo,async()=>({ok:true,value:catalog}) as never);await tab('菜谱');await click('手选 测试青菜');await screen.findByText(/存储空间不足/);await tab('我的');await click('新建自定义菜谱');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'独立菜'}});await click('保存自定义菜谱');await screen.findByText('自定义菜谱已保存');expect(screen.getByRole('button',{name:'重试保存当前编辑'})).not.toBeNull();await click('重试保存当前编辑');await screen.findByText('草稿已保存');const d=await data(repo);expect(d.draft?.dishes[0]!.recipe.name).toBe('测试青菜');expect(d.customRecipes).toHaveLength(1);});
  it('a completed actual commit with a refresh failure cannot be resubmitted as a new actual',async()=>{const {repo}=await setup();await seedPlan(repo);const originalRead=repo.read.bind(repo);let reads=0;vi.spyOn(repo,'read').mockImplementation(()=>{reads++;return reads===2?Promise.resolve({ok:false,error:{code:'UNAVAILABLE',message:'refresh failed'}}):originalRead();});app(repo);await tab('日历');await click('按此记录饮食 测试青菜');await click('确认记录实际');expect(await screen.findByText('保存事务已完成，但读取更新失败。不要重复新建记录，请重新读取已保存内容。')).not.toBeNull();expect(screen.getByRole('button',{name:'按此记录饮食 测试青菜'})).toHaveProperty('disabled',true);await click('重新读取已保存记录');await waitFor(()=>expect(screen.queryByText(/保存事务已完成，但读取更新失败/)).toBeNull());expect((await data(repo)).actualMeals).toHaveLength(1);await click('按此记录饮食 测试青菜');expect(screen.getByText('此计划已有实际记录')).not.toBeNull();});
  it('custom source rendering does not claim an online provenance',async()=>{const {repo}=await setup();await repo.commit({type:'saveCustomRecipe',recipe:{name:'手写来源',types:[],ingredients:[],steps:[],baseServings:null},expectedObjectRevision:null},0,'custom');app(repo);await tab('我的');await click('手选 手写来源');await screen.findByText('草稿已保存');await tab('今天吃什么');expect(screen.queryByText(/在线目录，来源链接未知/)).toBeNull();});
});

it('shows an accurate future-date rejection if the repository clock crosses the form validation boundary',async()=>{const {repo}=await setup();await seedPlan(repo);vi.spyOn(repo,'commit').mockResolvedValue({ok:false,error:{code:'FUTURE_DATE',message:'Future actual rejected'}});app(repo);await tab('日历');await click('按此记录饮食 测试青菜');await click('确认记录实际');expect(await screen.findByText('未来日期只能保存计划，实际记录输入已保留。')).not.toBeNull();});
it('offers a reread when an actual duplicate is detected in the transaction rather than claiming a plan date conflict',async()=>{const {repo}=await setup();await seedPlan(repo);vi.spyOn(repo,'commit').mockResolvedValue({ok:false,error:{code:'DUPLICATE',message:'Same plan already recorded'}});app(repo);await tab('日历');await click('按此记录饮食 测试青菜');await click('确认记录实际');expect(await screen.findByText('此计划已有实际记录，请重新读取后打开已有记录或明确新增。')).not.toBeNull();expect(screen.getByRole('button',{name:'重新读取重复对象'})).not.toBeNull();});
it('cancelling new custom and template forms never writes personal objects',async()=>{const {repo}=await setup();app(repo,async()=>({ok:true,value:catalog}) as never);await tab('我的');await click('新建自定义菜谱');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'放弃的菜'}});const before=await repo.read();await click('取消自定义编辑');expect(await repo.read()).toEqual(before);await tab('菜谱');await click('手选 测试青菜');await screen.findByText('草稿已保存');await tab('今天吃什么');await click('保存为菜单模板');fireEvent.change(screen.getByLabelText('模板名称'),{target:{value:'放弃的组合'}});const draftBefore=await repo.read();await click('取消模板编辑');expect(await repo.read()).toEqual(draftBefore);});

it('freezes date and meal while an existing plan replacement confirmation is pending',async()=>{const {repo}=await setup();await seedPlan(repo);app(repo,async()=>({ok:true,value:catalog}) as never);await tab('菜谱');await click('手选 测试青菜');await screen.findByText('草稿已保存');await tab('今天吃什么');await click('保存到日历');await click('保存计划');await screen.findByRole('button',{name:'确认替换已有计划'});expect(screen.getByLabelText('计划日期')).toHaveProperty('disabled',true);expect(screen.getByLabelText('计划餐次')).toHaveProperty('disabled',true);});

it('shows the actual conflicting object contents before an explicit overwrite decision and preserves local notes',async()=>{const {repo}=await setup();await seedPlan(repo);await repo.commit({type:'saveActual',actual:{date:'2026-10-09' as LocalDate,meal:'dinner',snapshots:[snapshotRecipe(recipe())],planId:null,note:'原备注',timeZone:'UTC' as TimeZone},expectedObjectRevision:null,allowAdditional:false},1,'actual');app(repo);await tab('日历');await click('编辑实际 测试青菜');fireEvent.change(screen.getByLabelText('实际备注'),{target:{value:'我的修改'}});const original=(await data(repo)).actualMeals[0]!;await repo.commit({type:'saveActual',actual:{id:original.id,date:'2026-10-08' as LocalDate,meal:'lunch',snapshots:original.snapshots,planId:null,note:'另一个页面修改的备注',timeZone:'UTC' as TimeZone},expectedObjectRevision:1,allowAdditional:false},2,'foreign');await click('确认记录实际');await screen.findByText('另一个页面有更新，输入已保留。');await click('查看此表单的最新记录');expect(await screen.findByText('最新备注：另一个页面修改的备注')).not.toBeNull();expect(screen.getByText('最新日期/餐次：2026-10-08 · 午餐')).not.toBeNull();expect(screen.getByLabelText('实际备注')).toHaveProperty('value','我的修改');await click('保留此表单编辑并继续');await click('确认记录实际');await screen.findByText('实际记录已保存');expect((await data(repo)).actualMeals[0]!.note).toBe('我的修改');});

it('replaying an uncertain clearAll does not clear later data or reset an explicitly adopted newer draft',async()=>{const {repo}=await setup();await seedPlan(repo);const original=repo.commit.bind(repo);let attempts=0;vi.spyOn(repo,'commit').mockImplementation(async(command,revision,id)=>{const result=await original(command,revision,id);if(command.type==='clearAll'&&++attempts===1)return {ok:false,error:{code:'UNAVAILABLE',message:'completion presentation uncertain'}};return result;});app(repo);await tab('我的');await click('清空本应用全部数据');await click('我已了解影响，继续');await click('最终确认清空本应用');await screen.findByText('本地保存未完成，输入已保留。请重试。');const {draft:makeDraft}=await import('./fixtures.ts');const snap=snapshotRecipe(recipe({name:'清空之后的新菜'}));await original({type:'saveDraft',draft:makeDraft({dishes:[{slotId:'vegetable-1',recipe:snap,locked:false}]})},2,'later-draft');await click('查看最新内容');await click('采用最新草稿');await click('最终确认清空本应用');await screen.findByText('清空请求已执行，之后新增的记录仍保留。');expect((await data(repo)).draft?.dishes[0]!.recipe.name).toBe('清空之后的新菜');await tab('今天吃什么');expect(screen.getByText('清空之后的新菜')).not.toBeNull();});

it('reloading local records keeps actual history available after the recipe API becomes unavailable',async()=>{const {repo,factory}=await setup();app(repo,async()=>({ok:true,value:catalog}) as never);await tab('菜谱');await click('手选 测试青菜');await screen.findByText('草稿已保存');await tab('今天吃什么');await click('记录本餐实际饮食');await click('确认记录实际');await screen.findByText('实际记录已保存');cleanup();repo.close();const opened=await openRepository({factory,now:()=>new Date(),uuid:()=>crypto.randomUUID()});if(!opened.ok)throw new Error(opened.error.message);repos.push(opened.value);app(opened.value);await tab('日历');expect(await screen.findByText('实际 · 测试青菜')).not.toBeNull();expect((await data(opened.value)).plans).toEqual([]);await tab('我的');expect(await screen.findByText('2026-10-09 · 已记录 1 条')).not.toBeNull();});

describe('Task4 review regressions',()=>{
  it('deliberate template remove/re-add uses current custom source while the old favorite remains unchanged',async()=>{const {repo}=await setup();app(repo);await tab('我的');await click('新建自定义菜谱');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'原自定义菜'}});await click('保存自定义菜谱');await screen.findByText('自定义菜谱已保存');await click('收藏 原自定义菜');await click('确认收藏');await screen.findByText('已收藏');await click('手选 原自定义菜');await screen.findByText('草稿已保存');await tab('今天吃什么');await click('保存为菜单模板');fireEvent.change(screen.getByLabelText('模板名称'),{target:{value:'更新测试组合'}});await click('确认保存模板');await screen.findByText('菜单模板已保存');await tab('我的');await click('编辑自定义 原自定义菜');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'最新自定义菜'}});await click('保存自定义菜谱');await screen.findByText('自定义菜谱已保存');await click('更新模板 更新测试组合');await click('移出模板 原自定义菜');await click('加入模板 最新自定义菜');await click('确认保存模板');await screen.findByText('菜单模板已保存');const d=await data(repo);expect(d.menuTemplates[0]!.snapshots[0]!.name).toBe('最新自定义菜');expect(d.favorites[0]!.snapshot.name).toBe('原自定义菜');expect(d.draft?.dishes[0]!.recipe.name).toBe('原自定义菜');});
  it('renaming a custom recipe preserves all untouched structured ingredient facts and multiline step grouping',async()=>{const {repo}=await setup();const ingredients=[{ingredientId:null,form:'diced',part:'leaf',raw:'Cabbage',quantity:{kind:'exact' as const,value:100,unit:'g'},trust:'unknown' as const,compoundResolved:false}];const steps=['One\nmultiline step'];await repo.commit({type:'saveCustomRecipe',recipe:{name:'有结构的菜',types:[],ingredients,steps,baseServings:null},expectedObjectRevision:null},0,'structured');app(repo);await tab('我的');await click('编辑自定义 有结构的菜');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'只修改菜名'}});await click('保存自定义菜谱');await screen.findByText('自定义菜谱已保存');const custom=(await data(repo)).customRecipes[0]!;expect(custom.snapshot.ingredients).toEqual(ingredients);expect(custom.snapshot.steps).toEqual(steps);expect(custom.snapshot.name).toBe('只修改菜名');});
  it('edited ingredient text requires consequence-aware replacement confirmation and keeps unedited steps exact',async()=>{const {repo}=await setup();const steps=['One\nmultiline step'];await repo.commit({type:'saveCustomRecipe',recipe:{name:'确认编辑菜',types:[],ingredients:[{ingredientId:null,form:'diced',part:'leaf',raw:'Cabbage',quantity:{kind:'exact',value:100,unit:'g'},trust:'unknown',compoundResolved:false}],steps,baseServings:null},expectedObjectRevision:null},0,'structured');app(repo);await tab('我的');await click('编辑自定义 确认编辑菜');fireEvent.change(screen.getByLabelText('原料及用量原文，每行一项，可留空'),{target:{value:'Cabbage changed'}});const before=await repo.read();await click('保存自定义菜谱');expect(await screen.findByText('修改原料文本将替换原料结构化数量、处理形态和部位；未修改的字段会完整保留。')).not.toBeNull();expect(await repo.read()).toEqual(before);await click('继续编辑原料和步骤');expect(await repo.read()).toEqual(before);await click('保存自定义菜谱');await click('确认替换已编辑的原料和步骤');await screen.findByText('自定义菜谱已保存');const custom=(await data(repo)).customRecipes[0]!;expect(custom.snapshot.ingredients[0]).toMatchObject({raw:'Cabbage changed',form:'',part:null,quantity:null,trust:'unknown'});expect(custom.snapshot.steps).toEqual(steps);});
  it('Today replacement across current device timezone preserves original creation zone in the command and stored plan',async()=>{const {repo}=await setup();const originalZone=(Intl.DateTimeFormat().resolvedOptions().timeZone==='Asia/Tokyo'?'America/Los_Angeles':'Asia/Tokyo') as TimeZone;await repo.commit({type:'savePlan',plan:{date:'2026-10-09' as LocalDate,meal:'dinner',servings:2,snapshots:[snapshotRecipe(recipe())],timeZone:originalZone},expectedObjectRevision:null},0,'plan');const originalPlan=(await data(repo)).plans[0]!;const commit=vi.spyOn(repo,'commit');app(repo,async()=>({ok:true,value:catalog}) as never);await tab('菜谱');await click('手选 测试青菜');await screen.findByText('草稿已保存');await tab('今天吃什么');await click('保存到日历');await click('保存计划');await click('确认替换已有计划');await screen.findByText('计划已保存');const replacement=commit.mock.calls.find(([command])=>command.type==='savePlan')![0];expect(replacement).toMatchObject({type:'savePlan',plan:{id:originalPlan.id,timeZone:originalZone}});const p=(await data(repo)).plans[0]!;expect(p.id).toBe(originalPlan.id);expect(p.createdAt).toBe(originalPlan.createdAt);expect(p.timeZone).toBe(originalZone);});
});
it('actual editing checks today in the current zone rather than using an old creation timezone to admit tomorrow',async()=>{const originalResolved=Intl.DateTimeFormat.prototype.resolvedOptions;vi.spyOn(Intl.DateTimeFormat.prototype,'resolvedOptions').mockImplementation(function(this:Intl.DateTimeFormat){return {...originalResolved.call(this),timeZone:'America/Los_Angeles'};});vi.setSystemTime(new Date('2026-10-09T00:30:00Z'));const {repo}=await setup();await repo.commit({type:'saveActual',actual:{date:'2026-10-08' as LocalDate,meal:'dinner',snapshots:[snapshotRecipe(recipe())],planId:null,note:'old-zone',timeZone:'Asia/Tokyo' as TimeZone},expectedObjectRevision:null,allowAdditional:false},0,'actual');const commit=vi.spyOn(repo,'commit');app(repo);await tab('日历');await click('编辑实际 测试青菜');fireEvent.change(screen.getByLabelText('实际日期'),{target:{value:'2026-10-09'}});await click('确认记录实际');expect(await screen.findByText('未来日期只能保存计划')).not.toBeNull();expect(commit).not.toHaveBeenCalled();const a=(await data(repo)).actualMeals[0]!;expect(a.date).toBe('2026-10-08');expect(a.timeZone).toBe('Asia/Tokyo');});
it('editing step text confirms regrouping while retaining untouched ingredient structure',async()=>{const {repo}=await setup();const ingredients=[{ingredientId:null,form:'diced',part:'leaf',raw:'Cabbage',quantity:{kind:'range' as const,min:100,max:200,unit:'g'},trust:'unknown' as const,compoundResolved:false},{ingredientId:null,form:'whole',part:null,raw:'第二项',quantity:null,trust:'unknown' as const,compoundResolved:false}];await repo.commit({type:'saveCustomRecipe',recipe:{name:'步骤编辑菜',types:[],ingredients,steps:['One\nmultiline step','第二步'],baseServings:null},expectedObjectRevision:null},0,'structured');app(repo);await tab('我的');await click('编辑自定义 步骤编辑菜');fireEvent.change(screen.getByLabelText('步骤，每行一步，可留空'),{target:{value:'新步骤一\n新步骤二'}});const before=await repo.read();await click('保存自定义菜谱');expect(await screen.findByText('修改步骤文本将按每行一步重建，原多行步骤分组不再保留；未修改的字段会完整保留。')).not.toBeNull();expect(await repo.read()).toEqual(before);await click('确认替换已编辑的原料和步骤');await screen.findByText('自定义菜谱已保存');const custom=(await data(repo)).customRecipes[0]!;expect(custom.snapshot.ingredients).toEqual(ingredients);expect(custom.snapshot.steps).toEqual(['新步骤一','新步骤二']);});
it('current online rows beat stale favorite facts and missing online sources still use the retained favorite',async()=>{const {repo}=await setup();const old=snapshotRecipe(recipe({name:'旧收藏菜',steps:['旧步骤']}));await repo.commit({type:'saveFavorite',snapshot:old},0,'favorite');const d=await data(repo);const {availableSnapshots}=await import('../src/ui/PersonalActions.tsx');const actions={data:d,catalog:{ok:true as const,value:{...catalog,recipes:[recipe({name:'新在线菜',steps:['新步骤'],contentVersion:'fresh-source'})]}},writable:true,pending:false,commit:repo.commit,readLatest:repo.read,onSelect:()=>{},onUseTemplate:()=>{}};expect(availableSnapshots(actions)).toEqual([snapshotRecipe(actions.catalog.value.recipes[0]!)]);expect(availableSnapshots({...actions,catalog:{ok:true,value:{...catalog,recipes:[]}}})).toEqual([old]);expect(d.favorites[0]!.snapshot).toEqual(old);});

describe('explicit retained-edit conflict recovery', () => {
  type Attempt = { command: Parameters<Repository['commit']>[0]; revision: number; requestId: string };
  async function conflictedEditor(options: { repeatConflict?: boolean; uncertainRetainedSave?: boolean; foreignDraft?: boolean } = {}) {
    const { repo } = await setup(); const original = repo.commit.bind(repo); const attempts: Attempt[] = [];
    let injected = false; let repeated = false; let uncertain = false;
    const foreignPreferences = { ...personalData().preferences, servings: 6 };
    vi.spyOn(repo, 'commit').mockImplementation(async (command, revision, requestId) => {
      attempts.push({ command: structuredClone(command), revision, requestId });
      if (command.type === 'saveDraft' && !injected) {
        injected = true;
        const foreign = options.foreignDraft
          ? { type: 'saveSettings' as const, preferences: foreignPreferences, draft: draft({ servings: 6, dishes: [{ slotId: 'vegetable-1', recipe: snapshotRecipe(recipe({ name: '最新页面的菜' })), locked: false }] }) }
          : { type: 'savePreferences' as const, preferences: foreignPreferences };
        expect((await original(foreign, 0, 'foreign-before-save')).ok).toBe(true);
      } else if (options.repeatConflict && command.type === 'saveDraft' && !repeated) {
        repeated = true;
        expect((await original({ type: 'savePreferences', preferences: { ...foreignPreferences, servings: 7 } }, revision, 'foreign-after-review')).ok).toBe(true);
      }
      const result = await original(command, revision, requestId);
      if (options.uncertainRetainedSave && command.type === 'saveDraft' && result.ok && !uncertain) {
        uncertain = true;
        return { ok: false, error: { code: 'UNAVAILABLE', message: 'completion not confirmed' } };
      }
      return result;
    });
    app(repo, async () => ({ ok: true, value: catalog }) as never);
    await waitFor(() => expect(screen.queryByText('正在读取本地记录…')).toBeNull());
    await tab('菜谱'); await click('手选 测试青菜'); await screen.findByRole('button', { name: '查看最新内容' });
    return { repo, attempts };
  }
  async function keepLocal() { await click('查看最新内容'); await click('保留当前编辑并继续'); }
  async function saveRetained() { await click('保存当前编辑'); await screen.findByText('当前编辑已保存'); }
  async function saveCalendar() {
    await tab('今天吃什么'); await click('保存到日历'); await click('保存计划'); await screen.findByText('计划已保存');
  }
  it('saves the retained draft inside calendar confirmation without an unrelated edit', async () => {
    const { repo, attempts } = await conflictedEditor(); await keepLocal();
    expect((await data(repo)).draft).toBeNull();
    await tab('今天吃什么'); await click('保存到日历');
    const dialog = screen.getByRole('dialog', { name: '保存到日历' });
    expect(within(dialog).getByRole('button', { name: '保存当前编辑' })).not.toBeNull();
    await saveRetained(); expect((await data(repo)).plans).toEqual([]);
    await click('保存计划'); await screen.findByText('计划已保存');
    const saved = await data(repo);
    expect(saved.draft?.dishes.map(dish => dish.recipe.name)).toEqual(['测试青菜']);
    expect(saved.preferences.servings).toBe(6); // Unedited latest preferences are not overwritten by a draft-only save.
    expect(saved.plans[0]?.snapshots.map(snapshot => snapshot.name)).toEqual(['测试青菜']);
    expect(attempts[1]?.revision).toBe(1); expect(attempts[1]?.requestId).not.toBe(attempts[0]?.requestId);
    expect(screen.queryByRole('button', { name: '保存当前编辑' })).toBeNull();
  });
  it('builds the rebased save from current combined settings and draft, not the obsolete failed command', async () => {
    const { repo, attempts } = await conflictedEditor();
    await tab('今天吃什么'); fireEvent.change(screen.getByLabelText('用餐人数'), { target: { value: '4' } });
    fireEvent.change(screen.getByLabelText('硬忌口，每行一项'), { target: { value: '芝麻' } }); await click('保存忌口');
    expect(attempts).toHaveLength(1); await keepLocal(); await saveRetained();
    expect(attempts[1]).toMatchObject({ revision: 1, command: { type: 'saveSettings', preferences: { servings: 4, hardExclusions: [{ raw: '芝麻', ingredientId: null }] }, draft: { servings: 4 } } });
    expect(attempts[1]?.requestId).not.toBe(attempts[0]?.requestId);
    const saved = await data(repo); expect(saved.preferences.servings).toBe(4); expect(saved.draft?.servings).toBe(4);
    expect(saved.draft?.dishes.map(dish => dish.recipe.name)).toEqual(['测试青菜']);
    await saveCalendar(); expect((await data(repo)).plans[0]?.servings).toBe(4);
  });
  it('requires another review after a foreign write following keep-local, then saves with a fresh intent', async () => {
    const { repo, attempts } = await conflictedEditor({ repeatConflict: true }); await keepLocal();
    await click('保存当前编辑'); await screen.findByRole('button', { name: '查看最新内容' });
    expect((await data(repo)).draft).toBeNull(); expect((await data(repo)).preferences.servings).toBe(7);
    expect(attempts[1]?.revision).toBe(1); expect(screen.queryByRole('button', { name: '保存当前编辑' })).toBeNull();
    await keepLocal(); await saveRetained();
    expect(attempts[2]?.revision).toBe(2); expect(new Set(attempts.map(attempt => attempt.requestId)).size).toBe(3);
    await saveCalendar(); expect((await data(repo)).plans[0]?.snapshots[0]?.name).toBe('测试青菜');
  });
  it('retries the retained save with exactly the same UUID and payload until its completed receipt is known', async () => {
    const { repo, attempts } = await conflictedEditor({ uncertainRetainedSave: true }); await keepLocal();
    await click('保存当前编辑'); await screen.findByText('本地保存未完成，输入已保留。请重试。');
    const retainedAttempt = attempts[1]!; expect(retainedAttempt.requestId).not.toBe(attempts[0]?.requestId);
    expect((await data(repo)).meta.revision).toBe(2);
    await click('重试保存当前编辑'); await screen.findByText('当前编辑已保存');
    expect(attempts[2]).toEqual(retainedAttempt); expect((await data(repo)).meta.revision).toBe(2);
    await saveCalendar(); expect((await data(repo)).plans).toHaveLength(1);
  });
  it('does not erase a later foreign conflict when an exact retry acknowledges the older completed save', async () => {
    const { repo, attempts } = await conflictedEditor({ uncertainRetainedSave: true }); await keepLocal();
    await click('保存当前编辑'); await screen.findByText('本地保存未完成，输入已保留。请重试。');
    const retainedAttempt = attempts[1]!;
    await repo.commit({ type: 'savePreferences', preferences: { ...personalData().preferences, servings: 7 } }, 2, 'foreign-after-uncertain');
    await click('重试保存当前编辑'); await screen.findByText('当前编辑已保存');
    expect(attempts.at(-1)).toEqual(retainedAttempt); expect((await data(repo)).meta.revision).toBe(3);
    expect(screen.getByRole('button', { name: '查看最新内容' })).not.toBeNull();
    await tab('今天吃什么'); expect(screen.getByRole('button', { name: '保存到日历' })).toHaveProperty('disabled', true);
    expect((await data(repo)).preferences.servings).toBe(7); expect((await data(repo)).plans).toEqual([]);
  });
  it('starts a fresh save intent after reviewing an uncertain completed save and a later foreign draft', async () => {
    const { repo, attempts } = await conflictedEditor({ uncertainRetainedSave: true }); await keepLocal();
    await click('保存当前编辑'); await screen.findByText('本地保存未完成，输入已保留。请重试。');
    const firstRetained = attempts[1]!;
    await repo.commit({ type: 'saveDraft', draft: draft({ dishes: [{ slotId: 'vegetable-1', recipe: snapshotRecipe(recipe({ name: '之后写入的菜' })), locked: false }] }) }, 2, 'foreign-later-draft');
    await keepLocal(); await saveRetained();
    const rebased = attempts.at(-1)!;
    expect(rebased.command).toEqual(firstRetained.command); expect(rebased.revision).toBe(3); expect(rebased.requestId).not.toBe(firstRetained.requestId);
    const saved = await data(repo); expect(saved.meta.revision).toBe(4); expect(saved.draft?.dishes[0]?.recipe.name).toBe('测试青菜');
    await saveCalendar(); expect((await data(repo)).plans[0]?.snapshots[0]?.name).toBe('测试青菜');
  });
  it('persists preference-only retained edits without manufacturing a draft', async () => {
    const { repo } = await setup(); app(repo, async () => ({ ok: true, value: catalog }) as never);
    await waitFor(() => expect(screen.queryByText('正在读取本地记录…')).toBeNull());
    await repo.commit({ type: 'saveFavorite', snapshot: snapshotRecipe(recipe()) }, 0, 'foreign-preferences');
    await screen.findByRole('button', { name: '查看最新内容' });
    fireEvent.change(screen.getByLabelText('硬忌口，每行一项'), { target: { value: '芝麻' } }); await click('保存忌口');
    await keepLocal(); await saveRetained(); const saved = await data(repo);
    expect(saved.preferences.hardExclusions).toEqual([{ raw: '芝麻', ingredientId: null }]); expect(saved.draft).toBeNull(); expect(saved.favorites).toHaveLength(1);
  });
  it('adopting latest deliberately discards retained draft and settings without a recovery write', async () => {
    const { repo, attempts } = await conflictedEditor({ foreignDraft: true });
    await tab('今天吃什么'); fireEvent.change(screen.getByLabelText('用餐人数'), { target: { value: '4' } });
    await click('查看最新内容'); const before = await repo.read(); await click('采用最新草稿');
    expect(await repo.read()).toEqual(before); expect(attempts).toHaveLength(1);
    expect(screen.getByLabelText('用餐人数')).toHaveProperty('value', '6'); expect(screen.getByText('最新页面的菜')).not.toBeNull();
    expect(screen.queryByRole('button', { name: '保存当前编辑' })).toBeNull(); expect(screen.queryByRole('button', { name: '重试保存当前编辑' })).toBeNull();
    await saveCalendar(); expect((await data(repo)).plans[0]?.snapshots[0]?.name).toBe('最新页面的菜');
  });
});
