import { afterEach, describe, expect, it, vi } from 'vitest';
import { IDBFactory, IDBObjectStore } from 'fake-indexeddb';
import { webcrypto } from 'node:crypto';
import { openRepository, type Command, type Repository } from '../src/data/repository.ts';
import { recordFromPlan, restoreTrash } from '../src/history/records.ts';
import { isActualMeal, isCustomRecipe, isFavorite, isMenuTemplate, isTrashEntry, validatePersonalData } from '../src/domain/validation.ts';
import { snapshotRecipe } from '../src/domain/snapshots.ts';
import type { ActualMealInput, LocalDate, Plan, TimeZone, TrashEntry } from '../src/domain/types.ts';
import { FIXED_NOW, personalData, recipe } from './fixtures.ts';
vi.stubGlobal('crypto', webcrypto);
const snapshot = () => snapshotRecipe(recipe());
const date = '2026-10-09' as LocalDate;
const zone = 'UTC' as TimeZone;
const plan: Plan = { id:'00000000-0000-4000-8000-000000000099', date, meal:'dinner', servings:2, snapshots:[snapshot()], createdAt:FIXED_NOW.toISOString() as Plan['createdAt'],updatedAt:FIXED_NOW.toISOString() as Plan['updatedAt'],timeZone:zone,revision:1,requestId:'plan-original' };
const actualInput = (overrides:Partial<ActualMealInput> = {}):ActualMealInput => ({date,meal:'dinner',snapshots:[snapshot()],planId:null,note:'',timeZone:zone,...overrides});
const actualCommand = (overrides:Partial<ActualMealInput> = {}, allowAdditional=false):Extract<Command,{type:'saveActual'}> => ({type:'saveActual',actual:actualInput(overrides),expectedObjectRevision:null,allowAdditional});
const repos:Repository[]=[];
afterEach(()=>{repos.splice(0).forEach(r=>r.close());vi.restoreAllMocks();});
async function setup(factory = new IDBFactory(), now:()=>Date = ()=>FIXED_NOW, currentTimeZone:()=>TimeZone = ()=>zone) { let seq=0;const opened=await openRepository({factory,now,currentTimeZone,uuid:()=>`00000000-0000-4000-8000-${String(++seq).padStart(12,'0')}`});if(!opened.ok)throw new Error(opened.error.message);repos.push(opened.value);return {repo:opened.value,factory}; }
async function data(repo:Repository){const r=await repo.read();if(!r.ok)throw new Error(r.error.message);return r.value;}
async function savePlan(repo:Repository,revision=0){return repo.commit({type:'savePlan',plan:{date,meal:'dinner',servings:2,snapshots:[snapshot()],timeZone:zone},expectedObjectRevision:null},revision,`plan-${revision}`);}

describe('actual meal preparation and strict local objects',()=>{
  it('rejects future actuals while retaining immutable selected plan facts and dates',()=>{const selected=[snapshot()];expect(recordFromPlan(plan,selected,'2026-10-10' as LocalDate,'dinner',date)).toMatchObject({ok:false,error:{code:'FUTURE_DATE'}});const r=recordFromPlan(plan,selected,date,'lunch',date);expect(r.ok).toBe(true);selected[0]!.name='renamed';plan.snapshots[0]!.name='changed';if(r.ok)expect(r.value).toMatchObject({date,meal:'lunch',planId:plan.id,snapshots:[{name:'测试青菜'}]});});
  it('rejects malformed, empty or authority-bearing selected snapshots',()=>{expect(recordFromPlan(plan,[],date,'dinner',date).ok).toBe(false);expect(recordFromPlan(plan,[recipe()],date,'dinner',date).ok).toBe(false);expect(recordFromPlan(null as unknown as Plan,[snapshot()],date,'dinner',date).ok).toBe(false);});
  it('keeps future plans permitted and enforces actual dates using the injected current timezone',async()=>{const {repo}=await setup(undefined,()=>new Date('2026-10-09T00:30:00Z'),()=>'America/Los_Angeles' as TimeZone);expect(await repo.commit(actualCommand({date:'2026-10-09' as LocalDate,timeZone:'America/Los_Angeles' as TimeZone}),0,'future-zone')).toMatchObject({ok:false,error:{code:'FUTURE_DATE'}});expect(await repo.commit({type:'savePlan',plan:{date:'2027-01-01' as LocalDate,meal:'dinner',servings:2,snapshots:[snapshot()],timeZone:zone},expectedObjectRevision:null},0,'future-plan')).toMatchObject({ok:true});});
  it('validates exact shapes and internal snapshot identities without granting catalog authority',async()=>{const {repo}=await setup();await repo.commit({type:'saveCustomRecipe',recipe:{name:'我的菜',types:[],ingredients:[],steps:[],baseServings:null},expectedObjectRevision:null},0,'custom');const d=await data(repo);expect(isCustomRecipe(d.customRecipes[0])).toBe(true);expect(d.customRecipes[0]!.snapshot).toMatchObject({recipeId:d.customRecipes[0]!.id,familyId:d.customRecipes[0]!.id,source:{url:null,commit:null,license:null},ingredients:[]});expect(isCustomRecipe({...d.customRecipes[0],generationEligible:true})).toBe(false);expect(isCustomRecipe({...d.customRecipes[0],snapshot:{...d.customRecipes[0]!.snapshot,recipeId:'other'}})).toBe(false);expect(validatePersonalData({...d,shoppingLists:[{id:'unsupported'}]})).toMatchObject({ok:false});});
});
describe('atomic actual history',()=>{
  it('persists actuals separately, replays stable requests, and requires explicit same-plan additional entries',async()=>{const {repo}=await setup();await savePlan(repo);const p=(await data(repo)).plans[0]!;const command=actualCommand({planId:p.id});expect(await repo.commit(command,1,'actual')).toMatchObject({ok:true,value:{globalRevision:2}});expect(await repo.commit(command,1,'actual')).toMatchObject({ok:true,value:{replayed:true,globalRevision:2}});expect(await repo.commit(command,2,'actual-again')).toMatchObject({ok:false,error:{code:'DUPLICATE'}});expect(await repo.commit({...command,allowAdditional:true},2,'additional')).toMatchObject({ok:true});const d=await data(repo);expect(d.plans).toHaveLength(1);expect(d.actualMeals).toHaveLength(2);expect(d.actualMeals.every(isActualMeal)).toBe(true);});
  it('allows several independent actuals in one date and meal and edits without mutating plans',async()=>{const {repo}=await setup();await savePlan(repo);await repo.commit(actualCommand(),1,'first');await repo.commit(actualCommand(),2,'second');const d=await data(repo);const a=d.actualMeals[0]!;await repo.commit({type:'saveActual',actual:{...actualInput(),id:a.id,note:'真实备注',snapshots:[{...snapshot(),name:'吃过的菜'}]},expectedObjectRevision:a.revision,allowAdditional:false},3,'edit');const next=await data(repo);expect(next.actualMeals).toHaveLength(2);expect(next.actualMeals.find(x=>x.id===a.id)!.note).toBe('真实备注');expect(next.plans[0]!.snapshots[0]!.name).toBe('测试青菜');expect(await repo.commit({type:'saveActual',actual:{...actualInput(),id:a.id},expectedObjectRevision:a.revision,allowAdditional:false},4,'stale')).toMatchObject({ok:false,error:{code:'CONFLICT'}});});
  it('clones source facts before asynchronous persistence and rejects reused changed requests',async()=>{const {repo}=await setup();const command=actualCommand();const saving=repo.commit(command,0,'stable');if(command.type==='saveActual')command.actual.snapshots[0]!.name='source changed';expect(await saving).toMatchObject({ok:true});expect((await data(repo)).actualMeals[0]!.snapshots[0]!.name).toBe('测试青菜');expect(await repo.commit(command,1,'stable')).toMatchObject({ok:false,error:{code:'CONFLICT'}});});
  it('rolls back history and deletion when a later store write aborts or quota is full',async()=>{const {repo}=await setup();await repo.commit(actualCommand(),0,'first');const before=await repo.read();const original=IDBObjectStore.prototype.put;vi.spyOn(IDBObjectStore.prototype,'put').mockImplementation(function(this:IDBObjectStore,...args){if(this.name==='trash')throw new DOMException('full','QuotaExceededError');return original.apply(this,args);});const a=(await data(repo)).actualMeals[0]!;expect(await repo.commit({type:'deleteObject',store:'actualMeals',id:a.id,expectedObjectRevision:a.revision},1,'delete')).toMatchObject({ok:false,error:{code:'QUOTA'}});expect(await repo.read()).toEqual(before);});
});
describe('personal recipes, favorites and reusable templates',()=>{
  it('requires custom names but permits unknown ingredients, steps, categories and servings',async()=>{const {repo}=await setup();const command={type:'saveCustomRecipe',recipe:{name:'',types:[],ingredients:[],steps:[],baseServings:null},expectedObjectRevision:null} as Command;expect(await repo.commit(command,0,'empty')).toMatchObject({ok:false,error:{code:'INVALID'}});if(command.type==='saveCustomRecipe')command.recipe.name='手写菜';expect(await repo.commit(command,0,'valid')).toMatchObject({ok:true});expect((await data(repo)).actualMeals).toEqual([]);});
  it('deduplicates favorite identity, retains snapshots after catalog disappearance and never deletes history on unfavorite',async()=>{const {repo}=await setup();await repo.commit(actualCommand(),0,'actual');const favorite={type:'saveFavorite',snapshot:snapshot()} as Command;expect(await repo.commit(favorite,1,'favorite')).toMatchObject({ok:true});expect(await repo.commit(favorite,2,'other')).toMatchObject({ok:false,error:{code:'DUPLICATE'}});const d=await data(repo);expect(d.favorites).toHaveLength(1);expect(isFavorite(d.favorites[0])).toBe(true);await repo.commit({type:'deleteObject',store:'favorites',id:d.favorites[0]!.id,expectedObjectRevision:1},2,'unfavorite');const next=await data(repo);expect(next.favorites).toEqual([]);expect(next.actualMeals).toHaveLength(1);expect(next.trash[0]!.data).toMatchObject({snapshot:{name:'测试青菜'}});});
  it('updates custom recipe and template only by deliberate new snapshots; prior plan and history remain unchanged',async()=>{const {repo}=await setup();await repo.commit({type:'saveTemplate',template:{name:'常用组合',servings:2,snapshots:[snapshot()]},expectedObjectRevision:null},0,'template');const d=await data(repo);const t=d.menuTemplates[0]!;expect(isMenuTemplate(t)).toBe(true);await repo.commit({type:'saveTemplate',template:{id:t.id,name:'常用组合',servings:2,snapshots:[{...snapshot(),name:'新快照'}]},expectedObjectRevision:1},1,'template-update');const next=await data(repo);expect(next.actualMeals).toEqual([]);expect(next.menuTemplates[0]!.snapshots[0]!.name).toBe('新快照');expect(t.snapshots[0]!.name).toBe('测试青菜');});
});
describe('trash lifecycle and isolated clearing',()=>{
  it('atomically deletes a source plan without cascading actuals, stores full data, and checks restore date/meal conflicts',async()=>{const {repo}=await setup();await savePlan(repo);const p=(await data(repo)).plans[0]!;await repo.commit(actualCommand({planId:p.id}),1,'actual');await repo.commit({type:'deleteObject',store:'plans',id:p.id,expectedObjectRevision:1},2,'delete-plan');let d=await data(repo);expect(d.plans).toEqual([]);expect(d.actualMeals[0]!.planId).toBe(p.id);expect(d.trash.every(isTrashEntry)).toBe(true);expect(d.trash[0]!.expiresAt).toBe('2026-11-08T00:00:00.000Z');await savePlan(repo,3);d=await data(repo);expect(restoreTrash(d.trash[0]!,d)).toMatchObject({ok:false,error:{code:'DUPLICATE'}});const restored=restoreTrash(d.trash[0]!,d,{date:'2026-10-10' as LocalDate,meal:'lunch'});expect(restored.ok).toBe(true);if(restored.ok)expect(await repo.commit(restored.value,4,'restore')).toMatchObject({ok:true});d=await data(repo);expect(d.plans).toHaveLength(2);expect(d.plans.find(x=>x.id===p.id)!.date).toBe('2026-10-10');expect(d.trash).toEqual([]);});
  it('rejects object and favorite recipe identity collisions rather than replacing on restore',async()=>{const {repo}=await setup();await repo.commit({type:'saveFavorite',snapshot:snapshot()},0,'first');let d=await data(repo);await repo.commit({type:'deleteObject',store:'favorites',id:d.favorites[0]!.id,expectedObjectRevision:1},1,'delete');await repo.commit({type:'saveFavorite',snapshot:snapshot()},2,'new');d=await data(repo);expect(restoreTrash(d.trash[0]!,d)).toMatchObject({ok:false,error:{code:'DUPLICATE'}});expect(await repo.commit({type:'restoreTrash',id:d.trash[0]!.id,expectedObjectRevision:1},3,'restore')).toMatchObject({ok:false,error:{code:'DUPLICATE'}});});
  it('cleans expired trash once on open by elapsed 30 days, preserves unexpired entries and global guards',async()=>{const factory=new IDBFactory();let now=FIXED_NOW;const {repo}=await setup(factory,()=>now);await repo.commit(actualCommand(),0,'actual');const a=(await data(repo)).actualMeals[0]!;await repo.commit({type:'deleteObject',store:'actualMeals',id:a.id,expectedObjectRevision:1},1,'delete');repo.close();now=new Date('2026-11-07T23:59:59.999Z');const before=await setup(factory,()=>now);expect((await data(before.repo)).trash).toHaveLength(1);before.repo.close();now=new Date('2026-11-08T00:00:00Z');const after=await setup(factory,()=>now);expect((await data(after.repo)).trash).toEqual([]);expect((await data(after.repo)).meta.revision).toBe(3);expect(await after.repo.commit(actualCommand(),2,'old-form')).toMatchObject({ok:false,error:{code:'CONFLICT'}});});
  it('rejects malformed nested trash records and inconsistent identity/expiry envelopes',async()=>{const {repo}=await setup();await repo.commit(actualCommand(),0,'actual');const a=(await data(repo)).actualMeals[0]!;await repo.commit({type:'deleteObject',store:'actualMeals',id:a.id,expectedObjectRevision:1},1,'delete');const t=(await data(repo)).trash[0]!;expect(isTrashEntry({...t,originalId:'different'})).toBe(false);expect(isTrashEntry({...t,expiresAt:t.deletedAt})).toBe(false);expect(isTrashEntry({...t,data:{...t.data,html:'<script>'}})).toBe(false);});
  it('clearAll only clears application stores, increments epoch/revision, and invalidates queued old exact retries',async()=>{const factory=new IDBFactory();const foreignOpen=factory.open('unrelated-app',1);foreignOpen.onupgradeneeded=()=>foreignOpen.result.createObjectStore('keep').put('preserved','key');const foreign=await new Promise<IDBDatabase>(resolve=>{foreignOpen.onsuccess=()=>resolve(foreignOpen.result);});const {repo}=await setup(factory);const command=actualCommand();await repo.commit(command,0,'old-actual');expect(await repo.commit({type:'clearAll'},1,'clear')).toMatchObject({ok:true,value:{globalRevision:2,objectId:null}});const d=await data(repo);expect(d).toEqual({...personalData(),meta:{...personalData().meta,revision:2,lastSuccessfulWriteAt:FIXED_NOW.toISOString()}});expect(await repo.commit(command,0,'old-actual')).toMatchObject({ok:false,error:{code:'CONFLICT'}});expect(await repo.commit({type:'clearAll'},1,'clear')).toMatchObject({ok:true,value:{replayed:true,globalRevision:2}});const raw=await repo.readRawSnapshot();if(raw.ok){const m=raw.value.stores.find(x=>x.name==='meta')!;expect(m.entries.find(x=>x.key==='epoch')!.value).toBe(1);expect(m.entries.find(x=>x.key==='current')!.value).not.toHaveProperty('requestId');}expect(await new Promise(resolve=>{const q=foreign.transaction('keep').objectStore('keep').get('key');q.onsuccess=()=>resolve(q.result);})).toBe('preserved');foreign.close();});
});

describe('history boundary regressions',()=>{
  it('rejects actual/trash/new-object extra fields and mismatched favorite identities',async()=>{const {repo}=await setup();const before=await repo.read();expect(await repo.commit({...actualCommand(),html:'<script>'} as unknown as Command,0,'unknown')).toMatchObject({ok:false,error:{code:'INVALID'}});expect(await repo.commit({type:'saveCustomRecipe',recipe:{name:'unknown',types:[],ingredients:[{ingredientId:'claimed',form:'',part:null,raw:'食材',quantity:null,trust:'reviewed',compoundResolved:true}],steps:[],baseServings:null},expectedObjectRevision:null},0,'claimed-review')).toMatchObject({ok:false,error:{code:'INVALID'}});await repo.commit({type:'saveFavorite',snapshot:snapshot()},0,'favorite');const d=await data(repo);expect(isFavorite({...d.favorites[0],recipeId:'other'})).toBe(false);expect(validatePersonalData({...d,favorites:[d.favorites[0],{...d.favorites[0],id:'00000000-0000-4000-8000-000000000098',requestId:'other'}]})).toMatchObject({ok:false,error:{code:'INVALID'}});expect(before.ok).toBe(true);});
  it('updates a custom source without changing older actual, favorite, plan or template snapshots',async()=>{const {repo}=await setup();await repo.commit({type:'saveCustomRecipe',recipe:{name:'原菜名',types:[],ingredients:[],steps:[],baseServings:null},expectedObjectRevision:null},0,'custom');let d=await data(repo);const c=d.customRecipes[0]!;await repo.commit({type:'saveFavorite',snapshot:c.snapshot},1,'favorite');await repo.commit({type:'savePlan',plan:{date,meal:'dinner',servings:2,snapshots:[c.snapshot],timeZone:zone},expectedObjectRevision:null},2,'plan');await repo.commit({type:'saveTemplate',template:{name:'组合',servings:2,snapshots:[c.snapshot]},expectedObjectRevision:null},3,'template');await repo.commit(actualCommand({snapshots:[c.snapshot]}),4,'actual');await repo.commit({type:'saveCustomRecipe',recipe:{id:c.id,name:'新菜名',types:[],ingredients:[],steps:[],baseServings:null},expectedObjectRevision:1},5,'rename');d=await data(repo);expect(d.customRecipes[0]!.snapshot.name).toBe('新菜名');expect(d.actualMeals[0]!.snapshots[0]!.name).toBe('原菜名');expect(d.plans[0]!.snapshots[0]!.name).toBe('原菜名');expect(d.favorites[0]!.snapshot.name).toBe('原菜名');expect(d.menuTemplates[0]!.snapshots[0]!.name).toBe('原菜名');});
  it('a stale delete or restore cannot remove or replace newer content',async()=>{const {repo}=await setup();await repo.commit(actualCommand(),0,'actual');const a=(await data(repo)).actualMeals[0]!;await repo.commit({type:'saveActual',actual:{...actualInput(),id:a.id,note:'new'},expectedObjectRevision:1,allowAdditional:false},1,'edit');const before=await repo.read();expect(await repo.commit({type:'deleteObject',store:'actualMeals',id:a.id,expectedObjectRevision:1},2,'old-delete')).toMatchObject({ok:false,error:{code:'CONFLICT'}});expect(await repo.read()).toEqual(before);});
  it('checks same-plan duplicates atomically across repository instances',async()=>{const {repo,factory}=await setup();await savePlan(repo);const p=(await data(repo)).plans[0]!;const second=await setup(factory);const results=await Promise.all([repo.commit(actualCommand({planId:p.id}),1,'one'),second.repo.commit(actualCommand({planId:p.id}),1,'two')]);expect(results.filter(r=>r.ok)).toHaveLength(1);const retry=await second.repo.commit(actualCommand({planId:p.id}),2,'two-fresh');expect(retry).toMatchObject({ok:false,error:{code:'DUPLICATE'}});expect((await data(repo)).actualMeals).toHaveLength(1);});
});

it.each(['QUOTA','ABORTED'] as const)('keeps valid data and raw export readable after %s during opening expiry, with writes blocked until reopening',async(code)=>{const factory=new IDBFactory();let now=FIXED_NOW;const {repo}=await setup(factory,()=>now);await repo.commit(actualCommand(),0,'actual');const a=(await data(repo)).actualMeals[0]!;await repo.commit({type:'deleteObject',store:'actualMeals',id:a.id,expectedObjectRevision:1},1,'delete');const before=await repo.readRawSnapshot();repo.close();now=new Date('2026-11-08T00:00:00Z');const original=IDBObjectStore.prototype.delete;const spy=vi.spyOn(IDBObjectStore.prototype,'delete').mockImplementation(function(this:IDBObjectStore,...args){if(this.name==='trash'&&code==='QUOTA')throw new DOMException('cleanup unavailable','QuotaExceededError');const request=original.apply(this,args);if(this.name==='trash'&&code==='ABORTED')this.transaction.abort();return request;});const next=await setup(factory,()=>now);expect(next.repo.status()).toMatchObject({readable:true,writable:false,reason:code});expect((await data(next.repo)).trash).toHaveLength(1);expect(await next.repo.readRawSnapshot()).toEqual(before);expect(await next.repo.commit({type:'clearAll'},2,'unsafe')).toMatchObject({ok:false,error:{code}});spy.mockRestore();next.repo.close();const recovered=await setup(factory,()=>now);expect(recovered.repo.status().writable).toBe(true);expect((await data(recovered.repo)).trash).toEqual([]);});

it('reopens actual history unchanged and retains its stored civil date and original timezone',async()=>{const {repo,factory}=await setup();await repo.commit(actualCommand({date:'2026-10-08' as LocalDate,timeZone:'America/Los_Angeles' as TimeZone,note:'保存后的记录'}),0,'actual');const before=await repo.read();repo.close();const next=await setup(factory,()=>new Date('2026-10-10T00:30:00Z'));expect(await next.repo.read()).toEqual(before);expect((await data(next.repo)).actualMeals[0]!.date).toBe('2026-10-08');});

describe('creation metadata immutability',()=>{
  it('revision-valid plan and actual edits retain original creation timezone despite attempted changes',async()=>{const {repo}=await setup();await repo.commit({type:'savePlan',plan:{date,meal:'dinner',servings:2,snapshots:[snapshot()],timeZone:'Asia/Tokyo' as TimeZone},expectedObjectRevision:null},0,'plan');let d=await data(repo);const p=d.plans[0]!;await repo.commit({type:'savePlan',plan:{id:p.id,date,meal:'dinner',servings:3,snapshots:p.snapshots,timeZone:'America/Los_Angeles' as TimeZone},expectedObjectRevision:1},1,'edit-plan');await repo.commit(actualCommand({timeZone:'Asia/Tokyo' as TimeZone}),2,'actual');d=await data(repo);const a=d.actualMeals[0]!;await repo.commit({type:'saveActual',actual:{...actualInput(),id:a.id,note:'changed',timeZone:'America/Los_Angeles' as TimeZone},expectedObjectRevision:1,allowAdditional:false},3,'edit-actual');d=await data(repo);expect(d.plans[0]!.timeZone).toBe('Asia/Tokyo');expect(d.plans[0]!.createdAt).toBe(p.createdAt);expect(d.actualMeals[0]!.timeZone).toBe('Asia/Tokyo');expect(d.actualMeals[0]!.createdAt).toBe(a.createdAt);expect(d.actualMeals[0]!.note).toBe('changed');});
  it('uses the injected current civil date independently of creation timezone on edits',async()=>{const {repo}=await setup(undefined,()=>new Date('2026-10-09T00:30:00Z'),()=>'America/Los_Angeles' as TimeZone);await repo.commit(actualCommand({date:'2026-10-08' as LocalDate,timeZone:'Asia/Tokyo' as TimeZone}),0,'actual');const a=(await data(repo)).actualMeals[0]!;const before=await repo.read();expect(await repo.commit({type:'saveActual',actual:{...actualInput(),id:a.id,date:'2026-10-09' as LocalDate,timeZone:'Asia/Tokyo' as TimeZone},expectedObjectRevision:1,allowAdditional:false},1,'future-edit')).toMatchObject({ok:false,error:{code:'FUTURE_DATE'}});expect(await repo.read()).toEqual(before);});
});
it('rejects restore at the exact expiry in an already-open repository without changing domain or raw data',async()=>{let now=FIXED_NOW;const {repo}=await setup(undefined,()=>now);await repo.commit(actualCommand(),0,'actual');const a=(await data(repo)).actualMeals[0]!;await repo.commit({type:'deleteObject',store:'actualMeals',id:a.id,expectedObjectRevision:1},1,'delete');const d=await data(repo);const entry=d.trash[0]!;now=new Date(entry.expiresAt);const before=await repo.read();const raw=await repo.readRawSnapshot();expect(await repo.commit({type:'restoreTrash',id:entry.id,expectedObjectRevision:entry.revision},2,'expired-restore')).toMatchObject({ok:false,error:{code:'INVALID'}});expect(await repo.read()).toEqual(before);expect(await repo.readRawSnapshot()).toEqual(raw);});
it('accepts today in the current zone after travel while preserving an earlier creation zone and civil date',async()=>{const {repo}=await setup(undefined,()=>new Date('2026-10-09T00:30:00Z'),()=>'UTC' as TimeZone);await repo.commit(actualCommand({date:'2026-10-08' as LocalDate,timeZone:'America/Los_Angeles' as TimeZone}),0,'actual');const a=(await data(repo)).actualMeals[0]!;expect(await repo.commit({type:'saveActual',actual:{...actualInput(),id:a.id,date:'2026-10-09' as LocalDate,timeZone:'Asia/Tokyo' as TimeZone},expectedObjectRevision:1,allowAdditional:false},1,'travel-edit')).toMatchObject({ok:true});const edited=(await data(repo)).actualMeals[0]!;expect(edited.date).toBe('2026-10-09');expect(edited.timeZone).toBe('America/Los_Angeles');});
it.each(['invalid','unavailable'] as const)('returns a Result for %s current-zone context without mutating data',async(kind)=>{const {repo}=await setup(undefined,()=>FIXED_NOW,()=>{if(kind==='unavailable')throw new Error('zone unavailable');return 'Not/AZone' as TimeZone;});const before=await repo.read();const raw=await repo.readRawSnapshot();expect(await repo.commit(actualCommand(),0,'bad-zone')).toMatchObject({ok:false,error:{code:kind==='invalid'?'INVALID':'UNAVAILABLE'}});expect(await repo.read()).toEqual(before);expect(await repo.readRawSnapshot()).toEqual(raw);});
