// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { IDBFactory } from 'fake-indexeddb';
import { webcrypto } from 'node:crypto';
import { App } from '../src/ui/App.tsx';
import { openRepository, type Repository } from '../src/data/repository.ts';
import { snapshotRecipe } from '../src/domain/snapshots.ts';
import { buildShopping, sourceFromPlan } from '../src/shopping/shopping.ts';
import type { Catalog, Ingredient, LocalDate, TimeZone } from '../src/domain/types.ts';
import { recipe } from './fixtures.ts';
const status={readable:true,writable:true,origin:'https://test.invalid',estimate:null,persisted:null,error:null};
const unavailable=async()=>({ok:false as const,error:{code:'UNAVAILABLE' as const,message:'API disabled'}});
const rice:Ingredient={ingredientId:'rice',form:'raw',part:null,raw:'大米 100g',quantity:{kind:'exact',value:100,unit:'g'},trust:'reviewed',compoundResolved:true};
const r=recipe({name:'采购测试菜',baseServings:2,ingredients:[rice,{...rice,raw:'大米 适量',quantity:null}]});
const catalog={origin:'online-provider',version:null,recipes:[r],aliases:{},recipeAliases:{},availability:{}} as Catalog;
const repos:Repository[]=[];
beforeEach(()=>{history.replaceState(null,'','/');vi.stubGlobal('crypto',webcrypto);vi.useFakeTimers({toFake:['Date']});vi.setSystemTime(new Date('2026-10-09T12:00:00Z'));});
afterEach(()=>{cleanup();repos.splice(0).forEach(r=>r.close());vi.useRealTimers();vi.unstubAllGlobals();vi.restoreAllMocks();});
async function setup(){let seq=0;const opened=await openRepository({factory:new IDBFactory(),now:()=>new Date(),uuid:()=>`00000000-0000-4000-8000-${String(++seq).padStart(12,'0')}`});if(!opened.ok)throw new Error(opened.error.message);repos.push(opened.value);return opened.value;}
async function data(repo:Repository){const r=await repo.read();if(!r.ok)throw new Error(r.error.message);return r.value;}
async function seed(repo:Repository){await repo.commit({type:'savePlan',plan:{date:'2026-10-09' as LocalDate,meal:'dinner',servings:4,snapshots:[snapshotRecipe(r)],timeZone:'UTC' as TimeZone},expectedObjectRevision:null},0,'plan');}
function app(repo:Repository,loader=unavailable){render(<App repository={repo} catalogLoader={loader} storageStatus={status}/>);}
async function click(name:string){const button=await screen.findByRole('button',{name});await waitFor(()=>expect(button).toHaveProperty('disabled',false));fireEvent.click(button);}
async function create(repo:Repository){await click('我的');await click('新建采购清单');fireEvent.click(await screen.findByLabelText('选择计划 2026-10-09 晚餐 采购测试菜'));await click('预览采购合计');expect(screen.getByText('200 g')).not.toBeNull();expect(screen.getByText('待确认 1 项')).not.toBeNull();await click('确认保存新清单');await screen.findByText('采购清单已保存');return (await data(repo)).shoppingLists[0]!;}
describe('traceable shopping interaction',()=>{
  it('selects plans, previews known totals plus unknown fragments, persists overrides/manual/purchased, cancels without writing',async()=>{const repo=await setup();await seed(repo);app(repo);const list=await create(repo);await click('编辑采购清单 '+list.id);fireEvent.change(screen.getByLabelText('手改用量 rice'),{target:{value:'买一袋'}});fireEvent.click(screen.getByLabelText('已购 rice'));fireEvent.change(screen.getByLabelText('手动项名称'),{target:{value:'垃圾袋'}});fireEvent.change(screen.getByLabelText('手动项用量'),{target:{value:'一包'}});await click('添加手动项');await click('保存采购编辑');await screen.findByText('采购编辑已保存');const saved=(await data(repo)).shoppingLists[0]!;expect(saved.items[0]).toMatchObject({userQuantity:'买一袋',purchased:true});expect(saved.items[1]).toMatchObject({name:'垃圾袋',userQuantity:'一包',manual:true});await click('编辑采购清单 '+list.id);fireEvent.change(screen.getByLabelText('手改用量 rice'),{target:{value:'取消这个输入'}});const before=await repo.read();await click('取消采购编辑');expect(await repo.read()).toEqual(before);});
  it('source edits only mark stale, regeneration shows differences and old edits, cancel retains original and confirmation saves independent version',async()=>{const repo=await setup();await seed(repo);app(repo);const list=await create(repo);await click('编辑采购清单 '+list.id);fireEvent.change(screen.getByLabelText('手改用量 rice'),{target:{value:'买一袋'}});fireEvent.click(screen.getByLabelText('已购 rice'));await click('保存采购编辑');await screen.findByText('采购编辑已保存');const old=structuredClone((await data(repo)).shoppingLists[0]!);await click('日历');await click('编辑计划 采购测试菜');fireEvent.change(screen.getByLabelText('计划人数'),{target:{value:'2'}});await click('保存计划编辑');await screen.findByText('计划编辑已保存');await click('我的');expect(await screen.findByText('来源已变更')).not.toBeNull();expect((await data(repo)).shoppingLists[0]).toEqual(old);await click('重新生成采购清单 '+list.id);await click('预览采购合计');expect(screen.getByText('变化 1 项')).not.toBeNull();expect(screen.getByText('旧手改/已购/手动项：rice · 买一袋 · 已购')).not.toBeNull();const before=await repo.read();await click('取消新清单');expect(await repo.read()).toEqual(before);await click('重新生成采购清单 '+list.id);await click('预览采购合计');await click('确认另存新版本');await screen.findByText('采购清单已保存');const d=await data(repo);expect(d.shoppingLists).toHaveLength(2);expect(d.shoppingLists[0]).toEqual(old);expect(d.shoppingLists[1]!.items[0]).toMatchObject({userQuantity:null,purchased:false,quantity:{value:100}});});
  it('deleted source still expands complete facts, and regeneration requires removing/reselecting missing sources',async()=>{const repo=await setup();await seed(repo);app(repo);const list=await create(repo);await click('日历');await click('删除计划 采购测试菜');await click('确认移入回收站');await screen.findByText('已移入回收站，保留 30 天');await click('我的');expect(await screen.findByText('来源计划已删除，快照仍保留')).not.toBeNull();expect(screen.getAllByText(/大米 100g/).length).toBeGreaterThan(0);await click('重新生成采购清单 '+list.id);expect(screen.getByText('有来源已删除或不可用，请重新选择来源；旧版快照仍保留。')).not.toBeNull();expect(screen.getByRole('button',{name:'预览采购合计'})).toHaveProperty('disabled',true);await click('取消新清单');expect((await data(repo)).shoppingLists[0]).toEqual(list);});
  it('current manual draft works when API fails and Today/Calendar expose shopping entry points',async()=>{const repo=await setup();app(repo);await click('我的');await click('新建自定义菜谱');fireEvent.change(screen.getByLabelText('自定义菜名'),{target:{value:'手写菜'}});fireEvent.change(screen.getByLabelText('原料及用量原文，每行一项，可留空'),{target:{value:'盐 适量'}});await click('保存自定义菜谱');await screen.findByText('自定义菜谱已保存');await click('手选 手写菜');await screen.findByText('草稿已保存');await click('今天吃什么');await click('从当前草稿建采购清单');await click('预览采购合计');expect(screen.getByText('待确认 1 项')).not.toBeNull();await click('确认保存新清单');await screen.findByText('采购清单已保存');expect((await data(repo)).shoppingLists[0]!.sources[0]!.snapshots[0]!.ingredients[0]!.trust).toBe('unknown');await click('日历');expect(screen.queryByRole('button',{name:/按实际建采购/})).toBeNull();});
  it('shopping success leaves a failed unsaved draft retry and exact request identity intact',async()=>{const repo=await setup();const original=repo.commit.bind(repo);let id='';let calls=0;vi.spyOn(repo,'commit').mockImplementation((command,revision,request)=>{if(command.type==='saveDraft'){if(++calls===1){id=request;return Promise.resolve({ok:false,error:{code:'QUOTA',message:'full'}});}expect(request).toBe(id);}return original(command,revision,request);});app(repo,async()=>({ok:true,value:catalog}) as never);await click('菜谱');await click('手选 采购测试菜');await screen.findByText(/存储空间不足/);await click('今天吃什么');await click('从当前草稿建采购清单');expect(screen.getByText('当前本地未保存草稿')).not.toBeNull();await click('预览采购合计');await click('确认保存新清单');await screen.findByText('采购清单已保存');expect(screen.getByRole('button',{name:'重试保存当前编辑'})).not.toBeNull();expect((await data(repo)).shoppingLists[0]!.sources[0]!.revision).toBeNull();await click('重试保存当前编辑');await screen.findByText('草稿已保存');expect((await data(repo)).draft?.dishes[0]!.recipe.name).toBe('采购测试菜');});
  it('shopping quota retry retains input/request and foreign conflict requires explicit actual latest review',async()=>{const repo=await setup();await seed(repo);const p=(await data(repo)).plans[0]!;await repo.commit({type:'saveShoppingList',list:buildShopping([sourceFromPlan(p)]),expectedObjectRevision:null},1,'seed-list');app(repo);await click('我的');const list=(await data(repo)).shoppingLists[0]!;await click('编辑采购清单 '+list.id);fireEvent.change(screen.getByLabelText('手改用量 rice'),{target:{value:'保留我的用量'}});const original=repo.commit.bind(repo);let uuid='',attempts=0;vi.spyOn(repo,'commit').mockImplementation((c,rev,id)=>{if(c.type==='saveShoppingList'){if(++attempts===1){uuid=id;return Promise.resolve({ok:false,error:{code:'QUOTA',message:'full'}});}expect(id).toBe(uuid);}return original(c,rev,id);});await click('保存采购编辑');await screen.findByText(/存储空间不足/);expect(screen.getByLabelText('手改用量 rice')).toHaveProperty('value','保留我的用量');await click('保存采购编辑');await screen.findByText('采购编辑已保存');vi.restoreAllMocks();await click('编辑采购清单 '+list.id);fireEvent.change(screen.getByLabelText('手改用量 rice'),{target:{value:'再次保留'}});const current=(await data(repo)).shoppingLists[0]!;await repo.commit({type:'saveShoppingList',list:{id:current.id,sources:current.sources,items:current.items.map(i=>({...i,userQuantity:'他页用量',purchased:true}))},expectedObjectRevision:current.revision},3,'foreign');await click('保存采购编辑');await screen.findByText('另一个页面有更新，输入已保留。');await click('查看此表单的最新记录');expect(await screen.findByText('最新采购条目：rice · 手改 他页用量 · 已购')).not.toBeNull();expect(screen.getByLabelText('手改用量 rice')).toHaveProperty('value','再次保留');const before=await repo.read();await click('保存采购编辑');expect(await repo.read()).toEqual(before);await click('保留此表单编辑并继续');await click('保存采购编辑');await screen.findByText('采购编辑已保存');expect((await data(repo)).shoppingLists[0]!.items[0]!.userQuantity).toBe('再次保留');});
});

it('saved stale/deleted labels are visible without expanding source details',async()=>{const repo=await setup();await seed(repo);app(repo);const list=await create(repo);await click('日历');await click('编辑计划 采购测试菜');fireEvent.change(screen.getByLabelText('计划人数'),{target:{value:'2'}});await click('保存计划编辑');await screen.findByText('计划编辑已保存');await click('我的');const label=await screen.findByText('来源已变更');expect(label.closest('details')).toBeNull();expect((await data(repo)).shoppingLists[0]).toEqual(list);});
it('a complete-fragment size failure preserves selected inputs, old versions and zero partial writes',async()=>{const repo=await setup();const ingredients=Array.from({length:35},(_,i)=>({...rice,ingredientId:null,raw:`原料${i} `+'x'.repeat(18_000)}));await repo.commit({type:'savePlan',plan:{date:'2026-10-09' as LocalDate,meal:'dinner',servings:4,snapshots:[snapshotRecipe(recipe({name:'超大来源',baseServings:2,ingredients}))],timeZone:'UTC' as TimeZone},expectedObjectRevision:null},0,'large-plan');app(repo);await click('我的');await click('新建采购清单');const checkbox=await screen.findByLabelText('选择计划 2026-10-09 晚餐 超大来源');fireEvent.click(checkbox);const before=await repo.readRawSnapshot();await click('预览采购合计');expect(await screen.findByText('Data exceeds 20 MiB')).not.toBeNull();expect(checkbox).toHaveProperty('checked',true);expect(await repo.readRawSnapshot()).toEqual(before);await click('取消新清单');},20_000);
it('unsaved current draft is identified accurately rather than falsely shown as removed',async()=>{const repo=await setup();const original=repo.commit.bind(repo);vi.spyOn(repo,'commit').mockImplementation((c,rev,id)=>c.type==='saveDraft'?Promise.resolve({ok:false,error:{code:'QUOTA',message:'full'}}):original(c,rev,id));app(repo,async()=>({ok:true,value:catalog}) as never);await click('菜谱');await click('手选 采购测试菜');await screen.findByText(/存储空间不足/);await click('今天吃什么');await click('从当前草稿建采购清单');expect(screen.getByText('当前本地未保存草稿')).not.toBeNull();expect(screen.queryByText('来源草稿已移除，快照仍保留')).toBeNull();});
it('a completed Calendar shopping entry is consumed and does not reopen a stale builder on return',async()=>{const repo=await setup();await seed(repo);app(repo);await click('日历');await click('按计划建采购清单 采购测试菜');await click('预览采购合计');await click('确认保存新清单');await screen.findByText('采购清单已保存');await click('日历');await click('编辑计划 采购测试菜');fireEvent.change(screen.getByLabelText('计划人数'),{target:{value:'2'}});await click('保存计划编辑');await screen.findByText('计划编辑已保存');await click('我的');expect(screen.queryByRole('heading',{name:'新建采购清单'})).toBeNull();expect(screen.getAllByText('来源已变更')).toHaveLength(1);});
it('a confirmed clear resets an unfinished shopping selection so deleted input cannot reappear as a new draft source',async()=>{const repo=await setup();app(repo,async()=>({ok:true,value:catalog}) as never);await click('菜谱');await click('手选 采购测试菜');await screen.findByText('草稿已保存');await click('今天吃什么');await click('从当前草稿建采购清单');expect(screen.getByRole('heading',{name:'新建采购清单'})).not.toBeNull();await click('清空本应用全部数据');await click('我已了解影响，继续');await click('最终确认清空本应用');await screen.findByText('本应用个人数据已清空');expect(screen.queryByRole('heading',{name:'新建采购清单'})).toBeNull();expect((await data(repo)).shoppingLists).toEqual([]);});
it('a schema-valid high-count source rejects its projected expansion before snapshot copies and retains checked selection/raw storage',async()=>{const repo=await setup();const ingredients=Array.from({length:1000},(_,i)=>({...rice,ingredientId:null,raw:`item ${i}: `+'x'.repeat(2000),quantity:null}));const snapshot=snapshotRecipe(recipe({name:'高数量来源',baseServings:2,ingredients}));await repo.commit({type:'savePlan',plan:{date:'2026-10-09' as LocalDate,meal:'dinner',servings:4,snapshots:[snapshot],timeZone:'UTC' as TimeZone},expectedObjectRevision:null},0,'many-plan');app(repo);await click('我的');await click('新建采购清单');const checkbox=await screen.findByLabelText('选择计划 2026-10-09 晚餐 高数量来源');fireEvent.click(checkbox);const before=await repo.readRawSnapshot();const native=globalThis.structuredClone;let fullCopies=0;const clone=vi.spyOn(globalThis,'structuredClone').mockImplementation((value:any)=>{if(value?.recipeId===snapshot.recipeId&&value?.ingredients?.length===1000||value?.snapshot?.ingredients?.length===1000){if(++fullCopies>2)throw new Error('TEST_BOUNDED_ALLOCATION_GUARD');}return native(value);});await click('预览采购合计');expect(await screen.findByText('Data exceeds 20 MiB')).not.toBeNull();expect(fullCopies).toBe(0);expect(checkbox).toHaveProperty('checked',true);clone.mockRestore();expect(await repo.readRawSnapshot()).toEqual(before);await click('取消新清单');},20_000);
